---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_management_node.html 
summary: Como parte de uma atualização do sistema de armazenamento NetApp SolidFire , você atualiza o nó de gerenciamento. 
keywords: netapp, cluster, management node, mNode, upgrade, 10, 11.0, 11.1, 11.3, 11.5, 11.7, 12.0, 12.2, 12.3, 12.3.1, 12.3.2, 12.3.x, 12.5, 12.7, 12.8 
---
= Atualizar um nó de gerenciamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode atualizar seu nó de gerenciamento para a versão 12.5 ou posterior a partir da versão 12.3.x ou posterior.

A atualização do sistema operacional do nó de gerenciamento não é mais necessária para atualizar o software Element no cluster de armazenamento.  Para realizar atualizações do Element usando o NetApp Hybrid Cloud Control, basta atualizar os serviços de gerenciamento para a versão mais recente.  Siga o procedimento de atualização do nó de gerenciamento para o seu cenário se desejar atualizar o sistema operacional do nó de gerenciamento por outros motivos, como correção de segurança.


NOTE: Se precisar de informações sobre como atualizar nós de gerenciamento da versão 12.2 ou anterior, consulte o seguinte: https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_management_node.html["Documentação de atualização do nó de gerenciamento do Element 12.3.x"^] .



== Etapa 1: Atualize a versão do hardware da VM em um nó de gerenciamento.

Se você estiver realizando uma atualização in-place de um nó de gerenciamento existente para o Element 12.8, antes de atualizar, certifique-se de que a versão do hardware da máquina virtual no nó de gerenciamento seja compatível com o ESXi 6.7 (versão de hardware da máquina virtual 14) ou posterior, dependendo do seu ambiente.

.Passos
. Faça login no vSphere Web Client como administrador do vCenter.
. No menu do vSphere Client, selecione *VMs e Modelos*.
. Clique com o botão direito do mouse na máquina virtual (VM) e selecione *Energia* > *Desligar SO convidado*.
+
Aguarde até que a máquina virtual seja desligada.

. Clique com o botão direito do mouse na máquina virtual e selecione *Compatibilidade* > *Atualizar compatibilidade da máquina virtual*.
. Selecione *Sim*.
. Selecione o ESXi 6.7 ou uma versão posterior, dependendo da versão do seu ambiente vSphere.
. Selecione *OK*.
. Após a conclusão da atualização, clique com o botão direito do mouse na máquina virtual e selecione *Energia* > *Ligar*.
. Selecione *atualização do cliente vSphere* e verifique se a compatibilidade da VM está na versão desejada.




== Etapa 2: Atualize um nó de gerenciamento para o Element 12.5 ou posterior.

Escolha uma das seguintes opções de atualização:

* <<Atualize um nó de gerenciamento para a versão 12.5 ou posterior a partir da versão 12.3.x ou posterior.>>
* <<Reconfigure a autenticação usando a API REST do nó de gerenciamento.>>
+
Escolha esta opção se você atualizou *sequencialmente* (1) a versão dos seus serviços de gerenciamento e (2) a versão do seu armazenamento de elementos e deseja *manter* seu nó de gerenciamento existente:




NOTE: Se você não atualizar sequencialmente seus serviços de gerenciamento seguidos pelo armazenamento de elementos, não poderá reconfigurar a reautenticação usando este procedimento.  Siga o procedimento de atualização apropriado.



=== Atualize um nó de gerenciamento para a versão 12.5 ou posterior a partir da versão 12.3.x ou posterior.

Você pode realizar uma atualização in-place do nó de gerenciamento da versão 12.3.x ou posterior para a versão 12.5 ou posterior sem precisar provisionar uma nova VM de nó de gerenciamento.


NOTE: O nó de gerenciamento Element 12.5 ou posterior é uma atualização opcional.  Não é necessário para implantações existentes.

.Antes de começar
* A memória RAM da máquina virtual do nó de gerenciamento é de 24 GB.
* O nó de gerenciamento que você pretende atualizar é da versão 12.0 e utiliza rede IPv4.  A versão 12.5 ou posterior do nó de gerenciamento não oferece suporte a IPv6.
+

TIP: Para verificar a versão do seu nó de gerenciamento, faça login no seu nó de gerenciamento e visualize o número da versão do Elemento no banner de login.

* Você atualizou seu pacote de serviços de gerenciamento para a versão mais recente usando o NetApp Hybrid Cloud Control.  Você pode acessar o NetApp Hybrid Cloud Control a partir do seguinte endereço IP: `\https://<ManagementNodeIP>`
* Se você estiver atualizando seu nó de gerenciamento para a versão 12.5 ou posterior, precisará dos serviços de gerenciamento 2.21.61 ou posterior para prosseguir.
* Você configurou um adaptador de rede adicional (se necessário) seguindo as instruções paralink:../mnode/task_mnode_install_add_storage_NIC.html["Configurando uma placa de rede de armazenamento adicional"] .
+

NOTE: Volumes persistentes podem exigir um adaptador de rede adicional caso a interface eth0 não possa ser roteada para o SVIP.  Configure um novo adaptador de rede na rede de armazenamento iSCSI para permitir a configuração de volumes persistentes.

* Os nós de armazenamento estão executando o Element 12.3.x ou posterior.


.Passos
. Faça login na máquina virtual do nó de gerenciamento usando SSH ou acesso via console.
. Baixe o https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["nó de gerenciamento ISO"^] para o software Element do site de suporte da NetApp para a VM do nó de gerenciamento.
+

NOTE: O nome da ISO é semelhante a `solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso`

. Verifique a integridade do download executando o comando md5sum no arquivo baixado e compare o resultado com o que está disponível no site de suporte da NetApp para o software Element, como no exemplo a seguir:
+
`sudo md5sum -b <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso`

. Monte a imagem ISO do nó de gerenciamento e copie o conteúdo para o sistema de arquivos usando os seguintes comandos:
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. Acesse o diretório inicial e desmonte o arquivo ISO. `/mnt` :
+
[listing]
----
sudo umount /mnt
----
. Exclua a ISO para liberar espaço no nó de gerenciamento:
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. No nó de gerenciamento que você está atualizando, execute o seguinte comando para atualizar a versão do sistema operacional do nó de gerenciamento.  O script preserva todos os arquivos de configuração necessários após a atualização, como as configurações do coletor Active IQ e do proxy.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
O nó de gerenciamento é reiniciado com um novo sistema operacional após a conclusão do processo de atualização.

+

NOTE: Após executar o comando sudo descrito nesta etapa, a sessão SSH será encerrada.  O acesso ao console é necessário para o monitoramento contínuo.  Caso não consiga acessar o console durante a atualização, tente novamente o login SSH e verifique a conectividade após 15 a 30 minutos.  Após efetuar o login, você poderá confirmar a nova versão do sistema operacional no banner SSH, que indicará que a atualização foi bem-sucedida.

. No nó de gerenciamento, execute o `redeploy-mnode` Script para manter as configurações anteriores dos serviços de gerenciamento:
+

NOTE: O script mantém a configuração anterior dos serviços de gerenciamento, incluindo a configuração do serviço coletor Active IQ , controladores (vCenters) ou proxy, dependendo das suas configurações.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: Se você desativou anteriormente a funcionalidade SSH no nó de gerenciamento, você precisalink:../mnode/task_mnode_ssh_management.html["Desative o SSH novamente"] no nó de gerenciamento recuperado.  Capacidade SSH que fornecelink:../mnode/task_mnode_enable_remote_support_connections.html["Acesso à sessão do túnel de suporte remoto (RST) do Suporte NetApp"] Está habilitado no nó de gerenciamento por padrão.



=== Reconfigure a autenticação usando a API REST do nó de gerenciamento.

Você pode manter seu nó de gerenciamento existente se tiver atualizado sequencialmente (1) os serviços de gerenciamento e (2) o armazenamento de elementos.  Se você seguiu uma ordem de atualização diferente, consulte os procedimentos para atualizações de nós de gerenciamento no local.

.Antes de começar
* Você atualizou seus serviços de gerenciamento para a versão 2.20.69 ou posterior.
* Seu cluster de armazenamento está executando o Element 12.3 ou posterior.
* Você atualizou sequencialmente seus serviços de gerenciamento e, em seguida, atualizou seu armazenamento de elementos.  Não é possível reconfigurar a autenticação usando este procedimento, a menos que você tenha concluído as atualizações na sequência descrita.


.Passos
. Abra a interface de usuário da API REST do nó de gerenciamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. Selecione *Autorizar* e complete o seguinte:
+
.. Insira o nome de usuário e a senha do cluster.
.. Insira o ID do cliente como `mnode-client` se o valor ainda não estiver preenchido.
.. Selecione *Autorizar* para iniciar uma sessão.


. Na interface de usuário da API REST, selecione *POST /services/reconfigure-auth*.
. Selecione *Experimentar*.
. Para o parâmetro *load_images*, selecione `true` .
. Selecione *Executar*.
+
O corpo da resposta indica que a reconfiguração foi bem-sucedida.





== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

