---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_element_software.html 
summary: Como parte de uma atualização do sistema NetApp SolidFire , você atualiza o software NetApp Element . 
keywords: netapp, solidfire, cluster, element, H610S upgrade, hcc, upgrade role 
---
= Atualize o software Element.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para atualizar o software NetApp Element , você pode usar a interface de usuário do NetApp Hybrid Cloud Control ou a API REST.  Durante uma atualização do software Element, certas operações são suprimidas, como adicionar e remover nós, adicionar e remover unidades e comandos associados a iniciadores, grupos de acesso a volumes e redes virtuais, entre outros.

[CAUTION]
====
O pacote de serviços de gerenciamento 2.27 inclui o Element Plug-in para vCenter Server 5.5, que é compatível apenas com o nó de gerenciamento 12.8. Ao atualizar para os serviços de gerenciamento 2.27, você deve alterar a sequência de atualização e atualizar o pacote de serviços de gerenciamento _após_ a atualização para o Element 12.8 para ter compatibilidade entre o nó de gerenciamento e os serviços de gerenciamento.

Se você estiver atualizando para os serviços de gerenciamento 2.21.61 a 2.26.40, deverá atualizar o pacote de serviços de gerenciamento _antes_ de atualizar para o Element 12.8.

====
.Antes de começar
* *Privilégios de administrador*: Você tem permissões de administrador do cluster de armazenamento para realizar a atualização.
* *Caminho de atualização válido*: Você verificou as informações do caminho de atualização para a versão do Element para a qual está atualizando e confirmou que o caminho de atualização é válido.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["NetApp KB: Matriz de atualização para clusters de armazenamento executando o software NetApp Element"^]
+
A partir da versão 12.5 do Element, o NetApp HealthTools deixou de ser compatível com as atualizações de software do Element.  Se você estiver executando o Element 11.0 ou 11.1, primeiro você develink:https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Atualize para o Element 12.3.x usando o HealthTools."^] Em seguida, atualize para o Element 12.5 ou posterior usando o NetApp Hybrid Cloud Control.

* *Sincronização de horário do sistema*: Você garantiu que o horário do sistema em todos os nós esteja sincronizado e que o NTP esteja configurado corretamente para o cluster de armazenamento e os nós.  Cada nó deve ser configurado com um servidor de nomes DNS na interface web de cada nó.(`https://[IP address]:442` ) sem falhas de cluster não resolvidas relacionadas à distorção de tempo.
* *Portas do sistema*: Se você estiver usando o NetApp Hybrid Cloud Control para atualizações, você garantiu que as portas necessárias estejam abertas. Verlink:../storage/reference_prereq_network_port_requirements.html["Portas de rede"] para mais informações.
* *Nó de gerenciamento*: Para a interface de usuário e API do NetApp Hybrid Cloud Control, o nó de gerenciamento em seu ambiente está executando a versão 11.3.
* *Saúde do cluster*: Você verificou que o cluster está pronto para ser atualizado. Verlink:task_hcc_upgrade_element_prechecks.html["Execute verificações de integridade do armazenamento Element antes de atualizar o armazenamento."] .
* *Controlador de gerenciamento da placa-mãe (BMC) atualizado para nós de armazenamento H610S*: Você atualizou a versão do BMC para seus nós H610S. Veja olink:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["Notas de lançamento e instruções de atualização"^] .


[[element-upgrade-tim]]
* *Tempo limite para o processo de atualização*: Você reservou tempo suficiente para realizar a atualização.  Ao atualizar para o software Element versão 12.5 ou posterior, o tempo do processo de atualização varia dependendo da sua versão atual do software Element e das atualizações de firmware.
+
[cols="20,20,20,20,20"]
|===
| Nó de armazenamento | Versão atual do software Element | Tempo aproximado de instalação de software e firmware por nó^1^ | Tempo aproximado de sincronização de dados por nó^2^ | Tempo total aproximado de atualização por nó 


| Todos os nós SolidFire e NetApp da série H com firmware atualizado^3^ | 12.x | 15 minutos | 10 a 15 minutos | 20 a 30 minutos 


| H610S e H410S | 12.x e 11.8 | 60 minutos | 30 a 60 minutos | 90 a 120 minutos 


| H610S | 11.7 e anteriores | 90 minutos | 40 a 70 minutos | 130 a 160 minutos Você também deve https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Executar um desligamento completo do nó e desconexão de energia"^] para cada nó H610S. 
|===
+
^1^Para obter uma matriz completa de firmware e firmware de driver para seu hardware, consultelink:../hardware/fw_storage_nodes.html["Versões de firmware de armazenamento compatíveis com nós de armazenamento SolidFire"] .

+
^2^Se você combinar um cluster com uma carga pesada de IOPS de gravação com um tempo de atualização de firmware mais longo, o tempo de sincronização de dados aumentará.

+
^3^ Os seguintes nós não são suportados.  Se você tentar atualizar um desses nós para uma versão não compatível do Element, verá um erro informando que o nó não é compatível com o Element 12.x:

+
** A partir dos nós de armazenamento Element 12.8, SF4805, SF9605, SF19210 e SF38410.
** A partir do Elemento 12.7, nós de armazenamento SF2405 e SF9608 e nós FC FC0025 e SF-FCN-01.


* *Contrato de Licença de Usuário Final (EULA)*: A partir da versão 2.20.69 dos serviços de gerenciamento, você deve aceitar e salvar o EULA antes de usar a interface do usuário ou a API do NetApp Hybrid Cloud Control para atualizar o software Element:
+
.. Abra o endereço IP do nó de gerenciamento em um navegador da web:
+
[listing]
----
https://<ManagementNodeIP>
----
.. Faça login no NetApp Hybrid Cloud Control fornecendo as credenciais de administrador do cluster de armazenamento.
.. Selecione *Atualizar* próximo ao canto superior direito da interface.
.. O Contrato de Licença de Usuário Final (EULA) aparece na tela.  Deslize a tela para baixo, selecione *Aceito esta atualização e todas as futuras* e selecione *Salvar*.




.Opções de atualização
Escolha uma das seguintes opções de atualização do software Element:

* <<Use a interface de usuário do NetApp Hybrid Cloud Control para atualizar o armazenamento Element.>>
* <<Use a API NetApp Hybrid Cloud Control para atualizar o armazenamento Element.>>



IMPORTANT: Se você estiver atualizando um nó da série H610S para o Element 12.5 ou posterior e o nó estiver executando uma versão do Element anterior à 11.8, será necessário executar as etapas de atualização adicionais descritas neste guia. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da Base de Conhecimento"^] para cada nó de armazenamento.  Se você estiver executando o Element 11.8 ou posterior, as etapas adicionais de atualização não são necessárias.



== Use a interface de usuário do NetApp Hybrid Cloud Control para atualizar o armazenamento Element.

Utilizando a interface de usuário do NetApp Hybrid Cloud Control, você pode atualizar um cluster de armazenamento.


CAUTION: Para obter informações sobre possíveis problemas durante a atualização de clusters de armazenamento usando o NetApp Hybrid Cloud Control e suas soluções alternativas, consulte este link. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["Artigo da Base de Conhecimento"^] .

.Passos
. Abra o endereço IP do nó de gerenciamento em um navegador da web:
+
[listing]
----
https://<ManagementNodeIP>
----
. Faça login no NetApp Hybrid Cloud Control fornecendo as credenciais de administrador do cluster de armazenamento.
. Selecione *Atualizar* próximo ao canto superior direito da interface.
. Na página *Upgrades*, selecione *Storage*.
+
A aba *Armazenamento* lista os clusters de armazenamento que fazem parte da sua instalação.  Se um cluster estiver inacessível pelo NetApp Hybrid Cloud Control, ele não será exibido na página *Atualizações*.

. Escolha uma das opções a seguir e execute o conjunto de etapas aplicáveis ao seu cluster:
+
[cols="2*"]
|===
| Opção | Passos 


| Todos os clusters que executam o Element 11.8 ou posterior  a| 
.. Selecione *Procurar* para carregar o pacote de atualização que você baixou.
.. Aguarde a conclusão do upload.  Uma barra de progresso mostra o status do upload.
+

CAUTION: O arquivo enviado será perdido se você sair da janela do navegador.

+
Uma mensagem é exibida na tela após o arquivo ser carregado e validado com sucesso.  A validação pode demorar alguns minutos.  Se você fechar a janela do navegador neste momento, o arquivo carregado será preservado.

.. Selecione *Iniciar atualização*.
+

TIP: O *Status da Atualização* muda durante a atualização para refletir o andamento do processo.  Ele também muda em resposta a ações que você realiza, como pausar a atualização ou se a atualização retornar um erro. Ver<<Alterações no status da atualização>> .

+

NOTE: Enquanto a atualização estiver em andamento, você pode sair da página e voltar mais tarde para continuar monitorando o progresso.  A página não atualiza dinamicamente o status e a versão atual se a linha do cluster estiver recolhida.  A linha do cluster precisa ser expandida para atualizar a tabela, ou você pode atualizar a página.

+
Você poderá baixar os registros após a conclusão da atualização.





| Você está atualizando um cluster H610S que executa uma versão do Element anterior à 11.8.  a| 
.. Selecione a seta suspensa ao lado do cluster que você está atualizando e escolha uma das versões de atualização disponíveis.
.. Selecione *Iniciar atualização*.  Após a conclusão da atualização, a interface do usuário solicitará que você execute etapas adicionais de atualização.
.. Conclua as etapas adicionais necessárias em https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da Base de Conhecimento"^] e confirme na interface do usuário que você concluiu a fase 2.


Você poderá baixar os registros após a conclusão da atualização.  Para obter informações sobre as várias alterações de status de atualização, consulte<<Alterações no status da atualização>> .

|===




=== Alterações no status da atualização

Aqui estão os diferentes estados que a coluna *Status da Atualização* na interface do usuário mostra antes, durante e depois do processo de atualização:

[cols="2*"]
|===
| Atualizar estado | Descrição 


| Atualizado | O cluster foi atualizado para a versão mais recente do Element disponível. 


| Versões disponíveis | Novas versões do firmware do Element e/ou do sistema de armazenamento estão disponíveis para atualização. 


| Em andamento | A atualização está em andamento.  Uma barra de progresso mostra o status da atualização.  As mensagens na tela também mostram falhas no nível do nó e exibem o ID de cada nó no cluster à medida que a atualização progride.  Você pode monitorar o status de cada nó usando a interface do usuário do Element ou o plug-in NetApp Element para a interface do usuário do vCenter Server. 


| Atualização em pausa | Você pode optar por pausar a atualização.  Dependendo do estado do processo de atualização, a operação de pausa pode ser bem-sucedida ou falhar.  Você verá uma mensagem na interface do usuário solicitando a confirmação da operação de pausa.  Para garantir que o cluster esteja em um local seguro antes de pausar uma atualização, a operação pode levar até duas horas para ser completamente interrompida.  Para retomar a atualização, selecione *Retomar*. 


| Em pausa | Você pausou a atualização.  Selecione *Retomar* para continuar o processo. 


| Erro | Ocorreu um erro durante a atualização.  Você pode baixar o registro de erros e enviá-lo para o suporte da NetApp .  Após resolver o erro, você pode retornar à página e selecionar *Retomar*.  Ao retomar a atualização, a barra de progresso retrocede por alguns minutos enquanto o sistema executa a verificação de integridade e verifica o estado atual da atualização. 


| Completo com acompanhamento | Apenas para nós H610S que estejam sendo atualizados a partir de uma versão do Element anterior à 11.8.  Após a conclusão da fase 1 do processo de atualização, este estado solicita que você execute etapas adicionais de atualização (consulte o https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da Base de Conhecimento"^] ).  Após concluir a fase 2 e confirmar que a concluiu, o status mudará para *Atualizado*. 
|===


== Use a API NetApp Hybrid Cloud Control para atualizar o armazenamento Element.

Você pode usar APIs para atualizar os nós de armazenamento em um cluster para a versão mais recente do software Element.  Você pode usar uma ferramenta de automação de sua escolha para executar as APIs.  O fluxo de trabalho da API documentado aqui usa a interface de usuário da API REST disponível no nó de gerenciamento como exemplo.

.Passos
. Faça o download do pacote de atualização de armazenamento para um dispositivo acessível ao nó de gerenciamento.
+
Acesse o software Element. https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["página de downloads"^] e faça o download da imagem mais recente do nó de armazenamento.

. Faça o upload do pacote de atualização de armazenamento para o nó de gerenciamento:
+
.. Abra a interface de usuário da API REST do nó de gerenciamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Selecione *Autorizar* e complete o seguinte:
+
... Insira o nome de usuário e a senha do cluster.
... Insira o ID do cliente como `mnode-client` .
... Selecione *Autorizar* para iniciar uma sessão.
... Feche a janela de autorização.


.. Na interface de usuário da API REST, selecione *POST /packages*.
.. Selecione *Experimentar*.
.. Selecione *Procurar* e escolha o pacote de atualização.
.. Selecione *Executar* para iniciar o upload.
.. Na resposta, copie e salve o ID do pacote.(`"id"` ) para uso em uma etapa posterior.


. Verifique o status do upload.
+
.. Na interface de usuário da API REST, selecione *GET​ /packages​/{id}​/status*.
.. Selecione *Experimentar*.
.. Insira o ID do pacote que você copiou na etapa anterior em *id*.
.. Selecione *Executar* para iniciar a solicitação de status.
+
A resposta indica `state` como `SUCCESS` quando estiver concluído.



. Localize o ID do cluster de armazenamento:
+
.. Abra a interface de usuário da API REST do nó de gerenciamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Selecione *Autorizar* e complete o seguinte:
+
... Insira o nome de usuário e a senha do cluster.
... Insira o ID do cliente como `mnode-client` .
... Selecione *Autorizar* para iniciar uma sessão.
... Feche a janela de autorização.


.. Na interface de usuário da API REST, selecione *GET /installations*.
.. Selecione *Experimentar*.
.. Selecione *Executar*.
.. Na resposta, copie o ID do ativo de instalação.(`"id"` ).
.. Na interface de usuário da API REST, selecione *GET /installations/{id}*.
.. Selecione *Experimentar*.
.. Cole o ID do recurso de instalação no campo *id*.
.. Selecione *Executar*.
.. A partir da resposta, copie e salve o ID do cluster de armazenamento.(`"id"` ) do cluster que você pretende atualizar para uso em uma etapa posterior.


. Execute a atualização de armazenamento:
+
.. Abra a interface de usuário da API REST de armazenamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Selecione *Autorizar* e complete o seguinte:
+
... Insira o nome de usuário e a senha do cluster.
... Insira o ID do cliente como `mnode-client` .
... Selecione *Autorizar* para iniciar uma sessão.
... Feche a janela de autorização.


.. Selecione *POST /upgrades*.
.. Selecione *Experimentar*.
.. Insira o ID do pacote de atualização no campo de parâmetros.
.. Insira o ID do cluster de armazenamento no campo de parâmetro.
+
A carga útil deve ser semelhante ao exemplo a seguir:

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. Selecione *Executar* para iniciar a atualização.
+
A resposta deve indicar o estado como `initializing` :

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copie o ID da atualização.(`"upgradeId"` ) que faz parte da resposta.


. Verifique o progresso e os resultados da atualização:
+
.. Selecione *GET /upgrades/{upgradeId}*.
.. Selecione *Experimentar*.
.. Insira o ID da atualização da etapa anterior em *upgradeId*.
.. Selecione *Executar*.
.. Se ocorrerem problemas ou se houver requisitos especiais durante a atualização, faça um dos seguintes procedimentos:
+
[cols="2*"]
|===
| Opção | Passos 


| Você precisa corrigir problemas de integridade do cluster devido a `failedHealthChecks` mensagem no corpo da resposta.  a| 
... Acesse o artigo específico da Base de Conhecimento listado para cada problema ou execute a solução especificada.
... Se uma Base de Conhecimento (KB) for especificada, conclua o processo descrito no artigo da KB correspondente.
... Depois de resolver os problemas do cluster, autentique-se novamente, se necessário, e selecione *PUT ​/upgrades/{upgradeId}*.
... Selecione *Experimentar*.
... Insira o ID da atualização da etapa anterior em *upgradeId*.
... Digitar `"action":"resume"` no corpo da requisição.
+
[listing]
----
{
  "action": "resume"
}
----
... Selecione *Executar*.




| Você precisa pausar a atualização porque a janela de manutenção está se fechando ou por outro motivo.  a| 
... Autentique-se novamente, se necessário, e selecione *PUT /upgrades/{upgradeId}*.
... Selecione *Experimentar*.
... Insira o ID da atualização da etapa anterior em *upgradeId*.
... Digitar `"action":"pause"` no corpo da requisição.
+
[listing]
----
{
  "action": "pause"
}
----
... Selecione *Executar*.




| Se você estiver atualizando um cluster H610S executando uma versão do Element anterior à 11.8, você verá o estado `finishedNeedsAck` no corpo da resposta. Você deve executar etapas de atualização adicionais para cada nó de armazenamento H610S.  a| 
... Conclua as etapas adicionais de atualização neste guia. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da Base de Conhecimento"^] para cada nó.
... Autentique-se novamente, se necessário, e selecione *PUT /upgrades/{upgradeId}*.
... Selecione *Experimentar*.
... Insira o ID da atualização da etapa anterior em *upgradeId*.
... Digitar `"action":"acknowledge"` no corpo da requisição.
+
[listing]
----
{
  "action": "acknowledge"
}
----
... Selecione *Executar*.


|===
.. Execute a API *GET /upgrades/{upgradeId}* várias vezes, conforme necessário, até que o processo seja concluído.
+
Durante a atualização, o `status` indica `running` se nenhum erro for encontrado.  À medida que cada nó é atualizado, o `step` alterações de valor para `NodeFinished` .

+
A atualização foi concluída com sucesso quando o `percent` valor é `100` e o `state` indica `finished` .







== O que acontece se uma atualização falhar usando o NetApp Hybrid Cloud Control?

Se uma unidade ou nó falhar durante uma atualização, a interface do usuário do Element exibirá falhas no cluster.  O processo de atualização não prossegue para o próximo nó e aguarda a resolução das falhas do cluster.  A barra de progresso na interface do usuário mostra que a atualização está aguardando a resolução das falhas do cluster.  Nesta fase, selecionar *Pausar* na interface do usuário não funcionará, pois a atualização aguarda que o cluster esteja íntegro.  Você precisará contatar o suporte da NetApp para obter ajuda na investigação da falha.

O NetApp Hybrid Cloud Control possui um período de espera predefinido de três horas, durante o qual um dos seguintes cenários pode ocorrer:

* As falhas do cluster são resolvidas dentro do período de três horas e a atualização é retomada.  Você não precisa tomar nenhuma providência nessa situação.
* O problema persiste após três horas, e o status da atualização mostra *Erro* com uma faixa vermelha.  Você pode retomar a atualização selecionando *Retomar* após o problema ser resolvido.
* O suporte da NetApp determinou que a atualização precisa ser temporariamente interrompida para que medidas corretivas sejam tomadas antes do prazo de três horas.  A equipe de suporte usará a API para abortar a atualização.



CAUTION: Interromper a atualização do cluster enquanto um nó está sendo atualizado pode resultar na remoção abrupta dos discos do nó.  Caso as unidades sejam removidas de forma inadequada, a adição delas novamente durante uma atualização exigirá intervenção manual do Suporte da NetApp .  O nó pode estar demorando mais para realizar atualizações de firmware ou atividades de sincronização pós-atualização.  Caso o processo de atualização pareça estar parado, entre em contato com o Suporte da NetApp para obter assistência.

[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

