---
permalink: hardware/concept_rtfi_configure.html 
sidebar: sidebar 
keywords: rtfi, return, factory, image, nodes, solidfire, software, image 
summary: Os sistemas de armazenamento NetApp SolidFire utilizam o processo RTFI para gravar uma imagem de software em um novo nó ou restaurar um nó ao seu estado original de fábrica. 
---
= Configure a imagem de retorno às configurações de fábrica.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas de armazenamento NetApp SolidFire utilizam o processo Return To Factory Image (RTFI) para gravar uma imagem de software em um novo nó ou restaurar um nó ao seu estado original de fábrica.  O processo RTFI apaga com segurança todos os dados e configurações existentes (se houver) e instala uma imagem de software NetApp Element não configurada.  O processo RTFI está disponível para todos os nós SolidFire .

Os sistemas SolidFire utilizam um único processo RTFI para todas as instalações do software Element.  Isso inclui instalações manuais internas realizadas por desenvolvedores, instalações automáticas por testes automatizados de frameworks, instalações em campo realizadas por engenheiros de serviço e clientes, e instalações realizadas por diversos integradores e parceiros.  O mesmo processo RTFI é utilizado em todos os nós SolidFire , independentemente do chassi ou tipo de nó em uso, para corrigir automaticamente quaisquer problemas.

O público-alvo deste guia são os integradores que instalam, configuram, utilizam ou solucionam problemas relacionados ao armazenamento.

* Linux: Você tem alguma experiência com sistemas Linux.
* Redes: Você possui familiaridade com redes de servidores e armazenamento em rede, incluindo endereços IP, máscaras de rede e gateways.



WARNING: O processo RTFI destrói os dados e apaga com segurança todos os dados e detalhes de configuração do nó, instalando em seguida um novo sistema operacional.  Verifique se o nó usado para o processo RTFI não está ativo como parte de um cluster.

Implante e instale a imagem RTFI da Organização Internacional de Normalização (ISO) e execute o processo RTFI:

* xref:task_rtfi_deployment_and_install_options.adoc[Opções de implantação e instalação do RTFI]
* xref:task_rtfi_process.adoc[Realizar o processo RTFI]
* xref:task_rtfi_options_menu.adoc[Menu de opções RTFI]




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

