---
permalink: hardware/task_sfseries_psurepl.html 
sidebar: sidebar 
keywords: solidfire chassis, power supply replacement, sf-series nodes 
summary: Cada chassi SolidFire inclui duas unidades de fonte de alimentação para redundância de energia.  Se uma fonte de alimentação falhar, você deve substituí-la o mais rápido possível para garantir que o chassi tenha uma fonte de alimentação redundante. 
---
= Substitua uma fonte de alimentação.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada chassi SolidFire inclui duas unidades de fonte de alimentação para redundância de energia.  Se uma fonte de alimentação falhar, você deve substituí-la o mais rápido possível para garantir que o chassi tenha uma fonte de alimentação redundante.

.O que você vai precisar
* Você determinou que a fonte de alimentação precisa ser substituída.
* Você tem uma fonte de alimentação de substituição.
* Você verificou que a segunda unidade de alimentação está funcionando.
* Você possui uma pulseira antiestática (ESD) ou tomou outras precauções antiestáticas.


.Sobre esta tarefa
As instruções se aplicam se você tiver um chassi de uma unidade de rack (1U) com qualquer um dos seguintes nós:

* SF2405
* SF4805
* SF9605
* SF9608
* SF19210
* SF38410
* SF-FCN-01
* FC0025


[NOTE]
====
Dependendo da versão do seu software Element, os seguintes nós não são suportados:

* A partir dos nós de armazenamento Element 12.8, SF4805, SF9605, SF19210 e SF38410.
* A partir do Elemento 12.7, nós de armazenamento SF2405 e SF9608, e nós FC0025 e SF-FCN-01.
* A partir do Element 12.0, os nós de armazenamento SF3010, SF6010 e SF9010.


====
.Passos
. Desconecte o cabo de alimentação da fonte de alimentação que você está substituindo.
. Pressione o botão de liberação para deslizar a unidade de alimentação para fora do chassi.
+

IMPORTANT: Certifique-se de usar ambas as mãos para suportar o peso da fonte de alimentação.

. Usando ambas as mãos, alinhe as bordas da fonte de alimentação de substituição com a abertura no chassi e empurre-a suavemente para dentro do chassi.
+

IMPORTANT: Ao deslizar a fonte de alimentação para dentro do chassi, não utilize força excessiva para evitar danos ao hardware.

. Conecte o cabo de alimentação.
. Devolva a unidade com defeito à NetApp seguindo as instruções na caixa que lhe foi enviada.
+
Você pode entrar em contato com o Suporte da NetApp para obter ajuda com o procedimento de substituição.





== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

