---
sidebar: sidebar 
permalink: mnode/task_mnode_multi_vcenter_config.html 
summary: Você pode configurar o NetApp Hybrid Cloud Control para usar vários vCenters através da interface de usuário da API REST. 
keywords: netapp, mnode, management node, multi-vcenter, Element 
---
= Configure o NetApp Hybrid Cloud Control para vários vCenters
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode configurar o NetApp Hybrid Cloud Control para gerenciar ativos de dois ou mais vCenters que não estejam usando o Modo Vinculado.

Você deve usar esse processo após a instalação inicial, quando precisar adicionar recursos para uma instalação recentemente ampliada ou quando novos recursos não forem adicionados automaticamente à sua configuração.  Utilize essas APIs para adicionar recursos que foram recentemente incluídos na sua instalação.

.O que você vai precisar
* A versão do seu cluster está executando o software NetApp Element 11.3 ou posterior.
* Você implantou um nó de gerenciamento executando a versão 11.3 ou posterior.


.Passos
. link:task_mnode_add_assets.html["Adicionar novos vCenters como ativos de controlador"]para a configuração do nó de gerenciamento.
. Atualize a API do serviço de inventário no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
+

NOTE: Como alternativa, você pode aguardar 2 minutos para que o inventário seja atualizado na interface do usuário do NetApp Hybrid Cloud Control.

+
.. Selecione *Autorizar* e complete o seguinte:
+
... Insira o nome de usuário e a senha do cluster.
... Insira o ID do cliente como `mnode-client` .
... Selecione *Autorizar* para iniciar uma sessão.
... Fechar a janela.


.. Na interface de usuário da API REST, selecione *GET /installations*.
.. Selecione *Experimentar*.
.. Selecione *Executar*.
.. Na resposta, copie o ID do ativo de instalação.(`"id"` ).
.. Na interface de usuário da API REST, selecione *GET /installations/{id}*.
.. Selecione *Experimentar*.
.. Defina a atualização para `True` .
.. Cole o ID do recurso de instalação no campo *id*.
.. Selecione *Executar*.


. Atualize o navegador do NetApp Hybrid Cloud Control para visualizar as alterações.


[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]

