---
sidebar: sidebar 
permalink: mnode/task_mnode_api_find_mgmt_svcs_version.html 
summary: É possível encontrar as versões do sistema operacional e dos serviços de gerenciamento utilizados pelo nó de gerenciamento por meio da API REST. 
keywords: netapp, Element, management node, management services, version, bundle version, what is 
---
= Verifique as versões do sistema operacional e dos serviços do nó de gerenciamento.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
É possível verificar os números de versão do sistema operacional do nó de gerenciamento, do pacote de serviços de gerenciamento e dos serviços individuais em execução no nó de gerenciamento usando a API REST no próprio nó de gerenciamento.

.O que você vai precisar
* Seu cluster está executando o software NetApp Element versão 11.3 ou posterior.
* Você implantou um nó de gerenciamento executando a versão 11.3 ou posterior.


.Opções
* <<Comandos API>>
* <<Etapas da interface do usuário da API REST>>




== Comandos API

* Obtenha informações sobre a versão do sistema operacional do nó de gerenciamento, do pacote de serviços de gerenciamento e do serviço da API do nó de gerenciamento (mnode-api) que estão em execução no nó de gerenciamento:
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/about" -H  "accept: application/json"
----
* Obtenha informações sobre a versão de serviços individuais em execução no nó de gerenciamento:
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/services?status=running" -H  "accept: */*" -H  "Authorization: ${TOKEN}"
----
+

NOTE: Você pode encontrar o portador `${TOKEN}` usado pelo comando da API quando vocêlink:task_mnode_api_get_authorizationtouse.html["autorizar"] .  O portador `${TOKEN}` está na resposta do curl.





== Etapas da interface do usuário da API REST

. Acesse a interface de usuário da API REST do serviço inserindo o endereço IP do nó de gerenciamento seguido por `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Faça um dos seguintes:
+
** Obtenha informações sobre a versão do sistema operacional do nó de gerenciamento, do pacote de serviços de gerenciamento e do serviço da API do nó de gerenciamento (mnode-api) que estão em execução no nó de gerenciamento:
+
... Selecione *GET /about*.
... Selecione *Experimentar*.
... Selecione *Executar*.
+
A versão do pacote de serviços de gerenciamento(`"mnode_bundle_version"` ), versão do SO do nó de gerenciamento(`"os_version"` ), e versão da API do nó de gerenciamento(`"version"` ) são indicados no corpo da resposta.



** Obtenha informações sobre a versão de serviços individuais em execução no nó de gerenciamento:
+
... Selecione *GET /services*.
... Selecione *Experimentar*.
... Selecione o status como *Em execução*.
... Selecione *Executar*.
+
Os serviços que estão sendo executados no nó de gerenciamento são indicados no corpo da resposta.







[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]

