---
sidebar: sidebar 
permalink: mnode/task_mnode_work_overview.html 
summary: 'Você pode usar o nó de gerenciamento (mNode) para acessar serviços do sistema, gerenciar ativos e configurações do cluster, executar testes e utilitários do sistema, configurar o Active IQ para monitoramento do sistema e habilitar o acesso do Suporte da NetApp para solução de problemas.' 
keywords: netapp, mnode, api, rest api, mnode ui, management node ui 
---
= Visão geral do nó de gerenciamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode usar o nó de gerenciamento (mNode) para acessar serviços do sistema, gerenciar ativos e configurações do cluster, executar testes e utilitários do sistema, configurar o Active IQ para monitoramento do sistema e habilitar o acesso do Suporte da NetApp para solução de problemas.


NOTE: Como prática recomendada, associe apenas um nó de gerenciamento a uma instância do VMware vCenter e evite definir os mesmos recursos de armazenamento e computação ou instâncias do vCenter em vários nós de gerenciamento.

Para clusters que executam o software Element versão 11.3 ou posterior, você pode interagir com o nó de gerenciamento usando uma das duas interfaces:

* Com a interface de usuário do nó de gerenciamento(`https://[mNode IP]:442` ), você pode fazer alterações nas configurações de rede e cluster, executar testes de sistema ou usar utilitários do sistema.
* Com a interface de usuário da API REST integrada.(`https://[mNode IP]/mnode` ), você pode executar ou entender APIs relacionadas aos serviços do nó de gerenciamento, incluindo configuração do servidor proxy, atualizações de nível de serviço ou gerenciamento de ativos.


Instalar ou recuperar um nó de gerenciamento:

* link:task_mnode_install.html["Instale um nó de gerenciamento"]
* link:task_mnode_install_add_storage_NIC.html["Configure um controlador de interface de rede (NIC) de armazenamento."]
* link:task_mnode_recover.html["Recuperar um nó de gerenciamento"]


Acesse o nó de gerenciamento:

* link:task_mnode_access_ui.html["Acesse o nó de gerenciamento (interface do usuário ou API REST)"]


Alterar o certificado SSL padrão:

* link:reference_change_mnode_default_ssl_certificate.html["Alterar o certificado SSL padrão do nó de gerenciamento"]


Execute tarefas com a interface de usuário do nó de gerenciamento:

* link:task_mnode_work_overview_UI.html["Visão geral da interface do usuário do nó de gerenciamento"]


Execute tarefas com as APIs REST do nó de gerenciamento:

* link:task_mnode_work_overview_API.html["Visão geral da interface do usuário da API REST do nó de gerenciamento"]


Desative ou ative a funcionalidade SSH remota ou inicie uma sessão de túnel de suporte remoto com o Suporte da NetApp para ajudá-lo a solucionar problemas:

* link:task_mnode_enable_node_troubleshooting_sessions.html["Acessando nós de armazenamento usando SSH para solução de problemas básicos"]
+
** link:task_mnode_enable_remote_support_connections.html["Habilitar conexões remotas de suporte da NetApp"]
** link:task_mnode_ssh_management.html["Gerenciar a funcionalidade SSH no nó de gerenciamento"]




[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]

