---
sidebar: sidebar 
permalink: mnode/task_mnode_edit_vcenter_assets.html 
summary: Você pode editar os controladores de nós de gerenciamento do vCenter usando a interface de usuário da API REST. 
keywords: netapp, mnode, management node, rest api, Element 
---
= Visualizar ou editar ativos de controlador existentes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode visualizar informações e editar controladores VMware vCenter existentes na configuração do nó de gerenciamento usando a API REST.  Os controladores são instâncias do VMware vCenter registradas no nó de gerenciamento da sua instalação do NetApp SolidFire .

.Antes de começar
* Certifique-se de que a versão do seu cluster esteja executando o software NetApp Element 11.3 ou posterior.
* Certifique-se de ter implantado um nó de gerenciamento executando a versão 11.3 ou posterior.




== Acesse a API REST dos serviços de gerenciamento.

.Passos
. Acesse a interface de usuário da API REST para serviços de gerenciamento inserindo o endereço IP do nó de gerenciamento seguido por `/vcenter/1/` :
+
[listing]
----
https://<ManagementNodeIP>/vcenter/1/
----
. Selecione *Autorizar* ou qualquer ícone de cadeado e complete o seguinte:
+
.. Insira o nome de usuário e a senha do cluster.
.. Insira o ID do cliente como `mnode-client` .
.. Selecione *Autorizar* para iniciar uma sessão.
.. Fechar a janela.






== Visualizar informações armazenadas sobre controladores existentes

Você pode listar os controladores vCenter existentes que estão registrados no nó de gerenciamento e visualizar as informações armazenadas sobre eles usando a API REST.

.Passos
. Selecione *GET /compute/controllers*.
. Selecione *Experimentar*.
. Selecione *Executar*.
+
A API retorna uma lista de todos os controladores vCenter conhecidos, juntamente com o endereço IP, ID do controlador, nome do host e ID do usuário usado para se comunicar com cada controlador.

. Se você deseja obter o status de conexão de um controlador específico, copie o ID do controlador do arquivo. `id` Copie o campo desse controlador para a sua área de transferência e veja<<Veja o status de um controlador existente.>> .




== Veja o status de um controlador existente.

Você pode visualizar o status de qualquer um dos controladores vCenter existentes registrados no nó de gerenciamento.  A API retorna um status indicando se o NetApp Hybrid Cloud Control consegue se conectar com o controlador vCenter, bem como o motivo desse status.

.Passos
. Selecione *GET /compute/controllers/{controller_id}/status*.
. Selecione *Experimentar*.
. Insira o ID do controlador que você copiou anteriormente no `controller_id` parâmetro.
. Selecione *Executar*.
+
A API retorna o status desse controlador vCenter específico, juntamente com o motivo desse status.





== Editar as propriedades armazenadas de um controlador

Você pode editar o nome de usuário ou a senha armazenados para qualquer um dos controladores vCenter existentes registrados no nó de gerenciamento.  Não é possível editar o endereço IP armazenado de um controlador vCenter existente.

.Passos
. Selecione *PUT /compute/controllers/{controller_id}*.
. Insira o ID do controlador do vCenter no campo `controller_id` parâmetro.
. Selecione *Experimentar*.
. Altere um dos seguintes parâmetros no campo *Corpo da solicitação*:
+
|===
| Parâmetro | Tipo | Descrição 


| `userId` | corda | Altere o ID do usuário usado para se comunicar com o controlador do vCenter (o usuário deve ter privilégios de administrador). 


| `password` | corda | Altere a senha usada para se comunicar com o controlador vCenter. 
|===
. Selecione *Executar*.
+
A API retorna informações atualizadas do controlador.



[discrete]
== Encontre mais informações

* link:task_mnode_add_assets.html["Adicione um recurso de controlador ao nó de gerenciamento."]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]

