---
sidebar: sidebar 
permalink: mnode/task_mnode_configure_proxy_server.html 
summary: Se o seu cluster estiver atrás de um servidor proxy, você deve configurar as definições de proxy para alcançar uma rede pública. 
keywords: netapp, Element, mnode, api, management node, add proxy, proxy server 
---
= Configure um servidor proxy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o seu cluster estiver atrás de um servidor proxy, você deve configurar as definições de proxy para poder aceder a uma rede pública.

Um servidor proxy é usado para coletores de telemetria e conexões de túnel reverso.  Você pode habilitar e configurar um servidor proxy usando a interface de usuário da API REST, caso ainda não tenha configurado um servidor proxy durante a instalação ou atualização.  Você também pode modificar as configurações existentes do servidor proxy ou desativar um servidor proxy.

O comando para configurar um servidor proxy atualiza e, em seguida, retorna as configurações de proxy atuais para o nó de gerenciamento.  As configurações de proxy são usadas pelo Active IQ, o serviço de monitoramento da NetApp , e por outros utilitários de software Element instalados no nó de gerenciamento, incluindo o túnel de suporte reverso para o Suporte da NetApp .

.Antes de começar
* Você deve saber as informações de host e credenciais do servidor proxy que está configurando.
* Certifique-se de que a versão do seu cluster esteja executando o software NetApp Element 11.3 ou posterior.
* Certifique-se de ter implantado um nó de gerenciamento executando a versão 11.3 ou posterior.
* (Nó de gerenciamento 12.0 e posterior) Você atualizou o NetApp Hybrid Cloud Control para a versão 2.16 dos serviços de gerenciamento antes de configurar um servidor proxy.


.Passos
. Acesse a interface de usuário da API REST no nó de gerenciamento inserindo o endereço IP do nó de gerenciamento seguido por `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. Selecione *Autorizar* ou qualquer ícone de cadeado e complete o seguinte:
+
.. Insira o nome de usuário e a senha do cluster.
.. Insira o ID do cliente como `mnode-client` .
.. Selecione *Autorizar* para iniciar uma sessão.
.. Fechar a janela.


. Selecione *PUT /settings*.
. Selecione *Experimentar*.
. Para ativar um servidor proxy, você deve configurar `use_proxy` verdadeiro.  Insira o endereço IP ou o nome do host e as portas de destino do proxy.
+
O nome de usuário do proxy, a senha do proxy e a porta SSH são opcionais e devem ser omitidos caso não sejam utilizados.

+
[listing]
----
{
"proxy_ip_or_hostname": "[IP or name]",
"use_proxy": [true/false],
"proxy_username": "[username]",
"proxy_password": "[password]",
"proxy_port": [port value],
"proxy_ssh_port": [port value: default is 443]
}
----
. Selecione *Executar*.



NOTE: Dependendo do seu ambiente, pode ser necessário reiniciar o nó de gerenciamento.

[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]

