= Parâmetro
:allow-uri-read: 


Você pode usar o `GetNodeFipsDrivesReport` Método para verificar o status da capacidade de criptografia de unidade FIPS 140-2 de um único nó no cluster de armazenamento.  Você deve executar este método em um nó de armazenamento individual.



== Parâmetro

Este método não possui parâmetro de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
fipsDrives
 a| 
Um objeto JSON contendo o status do suporte ao recurso FIPS 140-2 para este nó. Valores possíveis:

* Nenhum: O nó não é compatível com FIPS.
* Parcial: O nó é compatível com FIPS, mas nem todas as unidades no nó são unidades FIPS.
* Pronto: O nó é compatível com FIPS e todas as unidades no nó são unidades FIPS (ou nenhuma unidade está presente).

 a| 
corda

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetNodeFipsDrivesReport",
  "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id": 1,
    "result": {
        "fipsDrives": "None"
    }
}
----


== Novidade desde a versão

11,5
