= Encontre mais informações
:allow-uri-read: 


Você pode alterar o certificado SSL padrão e a chave privada do nó de armazenamento no cluster usando a API do NetApp Element .

Quando um cluster de software NetApp Element é criado, o cluster gera um certificado SSL (Secure Sockets Layer) autoassinado exclusivo e uma chave privada que é usada para toda a comunicação HTTPS por meio da interface do usuário do Element, da interface do usuário por nó ou das APIs.  O software Element suporta certificados autoassinados, bem como certificados emitidos e verificados por uma Autoridade Certificadora (AC) confiável.

Você pode usar os seguintes métodos da API para obter mais informações sobre o certificado SSL padrão e fazer alterações.

* *Obter certificado SSL*
+
Você pode usar olink:../api/reference_element_api_getsslcertificate.html["Método GetSSLCertificate"] Para obter informações sobre o certificado SSL atualmente instalado, incluindo todos os detalhes do certificado.

* *Definir certificado SSL*
+
Você pode usar olink:../api/reference_element_api_setsslcertificate.html["Método SetSSLCertificate"] Para configurar os certificados SSL do cluster e de cada nó com o certificado e a chave privada fornecidos.  O sistema valida o certificado e a chave privada para impedir que um certificado inválido seja aplicado.

* *Remover certificado SSL*
+
Olink:../api/reference_element_api_removesslcertificate.html["Método RemoveSSLCertificate"] Remove o certificado SSL e a chave privada atualmente instalados.  Em seguida, o cluster gera um novo certificado autoassinado e uma chave privada.




NOTE: O certificado SSL do cluster é aplicado automaticamente a todos os novos nós adicionados ao cluster.  Qualquer nó removido do cluster retorna a um certificado autoassinado e todas as informações de certificado e chave definidas pelo usuário são removidas do nó.



== Encontre mais informações

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["Alterar o certificado SSL padrão do nó de gerenciamento"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["Quais são os requisitos para configurar certificados SSL personalizados no Element Software?"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

