---
sidebar: sidebar 
permalink: hccstorage/task-hcc-manage-vol-access-groups.html 
summary: 'Aprenda como adicionar novos grupos de acesso a volumes (VAGs) para trabalhar com volumes de armazenamento all-flash do SolidFire , remover VAGs do sistema, editar VAGs existentes e visualizar detalhes dos VAGs.' 
keywords: netapp, element, cluster, volume, access 
---
= Criar e gerenciar grupos de acesso por volume
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode criar novos grupos de acesso a volumes, alterar o nome, os iniciadores associados ou os volumes associados aos grupos de acesso, ou excluir grupos de acesso a volumes existentes usando o NetApp Hybrid Cloud Control.

.O que você vai precisar
* Você possui credenciais de administrador para este sistema de armazenamento totalmente em flash SolidFire .
* Você atualizou seus serviços de gerenciamento para pelo menos a versão 2.15.28.  O gerenciamento de armazenamento do NetApp Hybrid Cloud Control não está disponível em versões anteriores do pacote de serviços.
* Assegure-se de ter um esquema de nomenclatura lógico para os grupos de acesso a volumes.




== Adicionar um grupo de acesso a volumes

Você pode adicionar um grupo de acesso a volumes a um cluster de armazenamento usando o NetApp Hybrid Cloud Control.

.Passos
. Faça login no NetApp Hybrid Cloud Control fornecendo as credenciais de administrador do cluster de armazenamento Element.
. No painel de controle, expanda o nome do seu cluster de armazenamento no menu de navegação à esquerda.
. Selecione *Volumes*.
. Selecione a guia *Grupos de Acesso*.
. Selecione o botão *Criar Grupo de Acesso*.
. Na caixa de diálogo que aparecer, insira um nome para o novo grupo de acesso ao volume.
. (Opcional) Na seção *Iniciadores*, selecione um ou mais iniciadores para associar ao novo grupo de acesso ao volume.
+
Se você associar um iniciador ao grupo de acesso ao volume, esse iniciador poderá acessar cada volume do grupo sem a necessidade de autenticação.

. (Opcional) Na seção *Volumes*, selecione um ou mais volumes para incluir neste grupo de acesso a volumes.
. Selecione *Criar Grupo de Acesso*.




== Editar um grupo de acesso a volume

Você pode editar as propriedades de um grupo de acesso a volumes existente usando o NetApp Hybrid Cloud Control.  Você pode alterar o nome, os iniciadores associados ou os volumes associados de um grupo de acesso.

.Passos
. Faça login no NetApp Hybrid Cloud Control fornecendo as credenciais de administrador do cluster de armazenamento Element.
. No painel de controle, expanda o nome do seu cluster de armazenamento no menu de navegação à esquerda.
. Selecione *Volumes*.
. Selecione a guia *Grupos de Acesso*.
. Na coluna *Ações* da tabela de grupos de acesso, expanda o menu de opções do grupo de acesso que você precisa editar.
. No menu de opções, selecione *Editar*.
. Faça as alterações necessárias no nome, nos iniciadores associados ou nos volumes associados.
. Confirme as alterações selecionando *Salvar*.
. Na tabela *Grupos de Acesso*, verifique se o grupo de acesso reflete suas alterações.




== Excluir um grupo de acesso a volume

É possível remover um grupo de acesso a volumes usando o NetApp Hybrid Cloud Control e, ao mesmo tempo, remover os iniciadores associados a esse grupo de acesso do sistema.

.Passos
. Faça login no NetApp Hybrid Cloud Control fornecendo as credenciais de administrador do cluster de armazenamento Element.
. No painel de controle, expanda o nome do seu cluster de armazenamento no menu de navegação à esquerda.
. Selecione *Volumes*.
. Selecione a guia *Grupos de Acesso*.
. Na coluna *Ações* da tabela de grupos de acesso, expanda o menu de opções do grupo de acesso que você precisa excluir.
. No menu de opções, selecione *Excluir*.
. Caso não deseje excluir os iniciadores associados ao grupo de acesso, desmarque a caixa de seleção *Excluir iniciadores neste grupo de acesso*.
. Confirme a operação de exclusão selecionando *Sim*.


[discrete]
== Encontre mais informações

* link:../concepts/concept_solidfire_concepts_volume_access_groups.html["Saiba mais sobre grupos de acesso por volume"]
* link:task-hcc-manage-initiators.html#add-initiators-to-a-volume-access-group["Adicionar iniciador a um grupo de acesso a volume"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]

