---
permalink: concepts/concept_solidfire_concepts_accounts_and_permissions.html 
sidebar: sidebar 
keywords: solidfire, element, cluster admin, storage, account, authoritative cluster 
summary: Para administrar e fornecer acesso aos recursos de armazenamento do seu sistema, você precisará configurar contas para esses recursos. 
---
= Contas e permissões
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para administrar e fornecer acesso aos recursos de armazenamento do seu sistema, você precisará configurar contas para esses recursos.

Utilizando o armazenamento Element, você pode criar e gerenciar os seguintes tipos de contas:

* <<Contas de administrador de cluster de armazenamento,Contas de usuário administrador para o cluster de armazenamento>>
* <<Contas de usuário,Contas de usuário para acesso ao volume de armazenamento>>
* <<Contas de usuário autorizadas do cluster,Contas de usuário autorizadas para o cluster do NetApp Hybrid Cloud Control.>>




== Contas de administrador de cluster de armazenamento

Existem dois tipos de contas de administrador que podem existir em um cluster de armazenamento executando o software NetApp Element :

* *Conta de administrador do cluster principal*: Esta conta de administrador é criada quando o cluster é criado.  Esta conta é a conta administrativa principal com o nível mais alto de acesso ao cluster.  Essa conta é análoga a um usuário root em um sistema Linux.  Você pode alterar a senha desta conta de administrador.
* *Conta de administrador do cluster*: Você pode conceder a uma conta de administrador do cluster um acesso administrativo limitado para executar tarefas específicas dentro de um cluster.  As credenciais atribuídas a cada conta de administrador de cluster são usadas para autenticar solicitações de API e da interface do usuário do Element dentro do sistema de armazenamento.



NOTE: É necessária uma conta de administrador de cluster local (não LDAP) para acessar os nós ativos em um cluster por meio da interface de usuário de cada nó.  Não são necessárias credenciais de conta para acessar um nó que ainda não faz parte de um cluster.

Você podelink:../storage/concept_system_manage_manage_cluster_administrator_users.html["gerenciar contas de administrador de cluster"] através da criação, exclusão e edição de contas de administrador de cluster, alteração da senha do administrador de cluster e configuração das definições de LDAP para gerir o acesso dos utilizadores ao sistema.



== Contas de usuário

As contas de usuário são utilizadas para controlar o acesso aos recursos de armazenamento em uma rede baseada no software NetApp Element .  É necessário ter pelo menos uma conta de usuário para que um volume possa ser criado.

Ao criar um volume, ele é atribuído a uma conta.  Se você criou um volume virtual, a conta é o contêiner de armazenamento.

Aqui estão algumas considerações adicionais:

* A conta contém a autenticação CHAP necessária para acessar os volumes a ela atribuídos.
* Uma conta pode ter até 2000 volumes atribuídos a ela, mas um volume só pode pertencer a uma conta.
* As contas de usuário podem ser gerenciadas a partir do ponto de extensão NetApp Element Management.




== Contas de usuário autorizadas do cluster

As contas de usuário autorizadas do cluster podem se autenticar em qualquer recurso de armazenamento associado à instância de nós e clusters do NetApp Hybrid Cloud Control.  Com esta conta, você pode gerenciar volumes, contas, grupos de acesso e muito mais em todos os clusters.

As contas de usuário autorizadas são gerenciadas na opção Gerenciamento de Usuários, no menu superior direito do NetApp Hybrid Cloud Control.

Olink:../concepts/concept_intro_clusters.html#authoritative-storage-clusters["cluster de armazenamento autoritativo"] é o cluster de armazenamento que o NetApp Hybrid Cloud Control usa para autenticar usuários.

Todos os usuários criados no cluster de armazenamento autoritativo podem fazer login no NetApp Hybrid Cloud Control.  Usuários criados em outros clusters de armazenamento _não podem_ fazer login no Hybrid Cloud Control.

* Se o seu nó de gerenciamento tiver apenas um cluster de armazenamento, então ele será o cluster autoritativo.
* Se o seu nó de gerenciamento tiver dois ou mais clusters de armazenamento, um desses clusters será designado como o cluster autoritativo e somente os usuários desse cluster poderão fazer login no NetApp Hybrid Cloud Control.


Embora muitos recursos do NetApp Hybrid Cloud Control funcionem com vários clusters de armazenamento, a autenticação e a autorização têm limitações inerentes.  A limitação relacionada à autenticação e autorização é que os usuários do cluster autoritativo podem executar ações em outros clusters vinculados ao NetApp Hybrid Cloud Control, mesmo que não sejam usuários nesses outros clusters de armazenamento.  Antes de prosseguir com o gerenciamento de vários clusters de armazenamento, você deve garantir que os usuários definidos nos clusters autorizados estejam definidos em todos os outros clusters de armazenamento com as mesmas permissões.  Você pode gerenciar usuários a partir do NetApp Hybrid Cloud Control.



== Contas de volume

As contas específicas de volume são exclusivas do cluster de armazenamento no qual foram criadas.  Essas contas permitem definir permissões em volumes específicos na rede, mas não têm efeito fora desses volumes.

As contas de volume são gerenciadas na tabela de Volumes de Controle do NetApp Hybrid Cloud.
