---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: A rede virtual no armazenamento SolidFire permite que o tráfego entre vários clientes que estão em redes lógicas separadas seja conectado a um único cluster.  As conexões com o cluster são segregadas na pilha de rede por meio do uso de VLAN tagging. 
---
= Gerenciar redes virtuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A rede virtual no armazenamento SolidFire permite que o tráfego entre vários clientes que estão em redes lógicas separadas seja conectado a um único cluster.  As conexões com o cluster são segregadas na pilha de rede por meio do uso de VLAN tagging.



== Encontre mais informações

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Adicionar uma rede virtual]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Habilitar roteamento e encaminhamento virtuais]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Editar uma rede virtual]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[Editar VLANs VRF]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Excluir uma rede virtual]

