---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: Você pode gerenciar contas de administrador de cluster para um sistema de armazenamento SolidFire .  As funções de gerenciamento de administrador de cluster disponíveis incluem a criação, exclusão e edição de contas de administrador de cluster, a alteração da senha do administrador de cluster e a configuração das definições de LDAP para gerenciar o acesso dos usuários ao sistema. 
---
= Gerenciar contas de usuário administradoras de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar contas de administrador de cluster para um sistema de armazenamento SolidFire criando, excluindo e editando contas de administrador de cluster, alterando a senha do administrador de cluster e configurando as definições de LDAP para gerenciar o acesso dos usuários ao sistema.



== tipos de conta de administrador de cluster de armazenamento

Existem dois tipos de contas de administrador que podem existir em um cluster de armazenamento executando o software NetApp Element : a conta de administrador primário do cluster e uma conta de administrador do cluster.

* *Conta de administrador do cluster principal*
+
Essa conta de administrador é criada quando o cluster é criado.  Esta conta é a conta administrativa principal com o nível mais alto de acesso ao cluster.  Essa conta é análoga a um usuário root em um sistema Linux.  Você pode alterar a senha desta conta de administrador.

* *Conta de administrador do cluster*
+
Você pode conceder a uma conta de administrador de cluster um conjunto limitado de acesso administrativo para executar tarefas específicas dentro do cluster.  As credenciais atribuídas a cada conta de administrador de cluster são usadas para autenticar solicitações de API e da interface do usuário do Element dentro do sistema de armazenamento.




NOTE: É necessária uma conta de administrador de cluster local (não LDAP) para acessar os nós ativos em um cluster por meio da interface de usuário de cada nó.  Não são necessárias credenciais de conta para acessar um nó que ainda não faz parte de um cluster.



== Ver detalhes do administrador do cluster

. Para criar uma conta de administrador de cluster (não LDAP) para todo o cluster, execute as seguintes ações:
+
.. Clique em *Usuários* > *Administradores do cluster*.


. Na página Administradores do Cluster, na aba Usuários, você pode visualizar as seguintes informações.
+
** *ID*: Número sequencial atribuído à conta de administrador do cluster.
** *Nome de usuário*: O nome atribuído à conta de administrador do cluster quando ela foi criada.
** *Acesso*: As permissões de usuário atribuídas à conta do usuário. Valores possíveis:
+
*** ler
*** reportagem
*** nós
*** dirige
*** volumes
*** contas
*** Administradores do cluster
*** administrador
*** suporteAdministrador




+
[NOTE]
====
Todas as permissões estão disponíveis para o tipo de acesso de administrador.

Existem tipos de acesso disponíveis através da API que não estão disponíveis na interface do usuário do Element.

====
+
** *Tipo*: O tipo de administrador do cluster. Valores possíveis:
+
*** Conjunto
*** Ldap


** *Atributos*: Se a conta de administrador do cluster foi criada usando a API Element, esta coluna mostra quaisquer pares nome-valor que foram definidos usando esse método.
+
Verlink:../api/concept_element_api_about_the_api.html["Referência da API do NetApp Element Software"] .







== Crie uma conta de administrador de cluster.

Você pode criar novas contas de administrador de cluster com permissões para permitir ou restringir o acesso a áreas específicas do sistema de armazenamento.  Ao configurar as permissões da conta de administrador do cluster, o sistema concede direitos somente leitura para quaisquer permissões que você não atribuir ao administrador do cluster.

Se você deseja criar uma conta de administrador de cluster LDAP, certifique-se de que o LDAP esteja configurado no cluster antes de começar.

link:concept_system_manage_manage_ldap.html["Habilite a autenticação LDAP com a interface de usuário do Element."]

Posteriormente, você poderá alterar os privilégios da conta de administrador do cluster para relatórios, nós, unidades, volumes, contas e acesso em nível de cluster.  Ao habilitar uma permissão, o sistema atribui acesso de gravação para esse nível.  O sistema concede ao usuário administrador acesso somente leitura para os níveis que você não selecionar.

Você também poderá remover posteriormente qualquer conta de usuário administrador de cluster criada por um administrador de sistema.  Não é possível remover a conta de administrador principal do cluster que foi criada quando o cluster foi criado.

. Para criar uma conta de administrador de cluster (não LDAP) para todo o cluster, execute as seguintes ações:
+
.. Clique em *Usuários* > *Administradores do cluster*.
.. Clique em *Criar administrador de cluster*.
.. Selecione o tipo de usuário *Cluster*.
.. Insira um nome de usuário e uma senha para a conta e confirme a senha.
.. Selecione as permissões de usuário que deseja aplicar à conta.
.. Selecione a caixa de seleção para concordar com o Contrato de Licença do Usuário Final.
.. Clique em *Criar administrador de cluster*.


. Para criar uma conta de administrador de cluster no diretório LDAP, execute as seguintes ações:
+
.. Clique em *Cluster* > *LDAP*.
.. Certifique-se de que a autenticação LDAP esteja habilitada.
.. Clique em *Testar autenticação do usuário* e copie o nome distinto que aparece para o usuário ou para um dos grupos aos quais o usuário pertence, para que você possa colá-lo posteriormente.
.. Clique em *Usuários* > *Administradores do cluster*.
.. Clique em *Criar administrador de cluster*.
.. Selecione o tipo de usuário LDAP.
.. No campo Nome Distinto, siga o exemplo na caixa de texto para inserir um nome distinto completo para o usuário ou grupo.  Alternativamente, cole o nome distinto que você copiou anteriormente.
+
Se o nome distinto fizer parte de um grupo, qualquer usuário que seja membro desse grupo no servidor LDAP terá as permissões dessa conta de administrador.

+
Para adicionar usuários ou grupos de Administradores de Cluster LDAP, o formato geral do nome de usuário é "`LDAP:<Nome Distinto Completo>`".

.. Selecione as permissões de usuário que deseja aplicar à conta.
.. Selecione a caixa de seleção para concordar com o Contrato de Licença do Usuário Final.
.. Clique em *Criar administrador de cluster*.






== Editar permissões de administrador do cluster

Você pode alterar os privilégios da conta de administrador do cluster para relatórios, nós, unidades, volumes, contas e acesso em nível de cluster.  Ao habilitar uma permissão, o sistema atribui acesso de gravação para esse nível.  O sistema concede ao usuário administrador acesso somente leitura para os níveis que você não selecionar.

. Clique em *Usuários* > *Administradores do cluster*.
. Clique no ícone Ações do administrador do cluster que você deseja editar.
. Clique em *Editar*.
. Selecione as permissões de usuário que deseja aplicar à conta.
. Clique em *Salvar alterações*.




== Alterar senhas para contas de administrador do cluster

Você pode usar a interface do Element para alterar as senhas do administrador do cluster.

. Clique em *Usuários* > *Administradores do cluster*.
. Clique no ícone Ações do administrador do cluster que você deseja editar.
. Clique em *Editar*.
. No campo Alterar Senha, digite uma nova senha e confirme-a.
. Clique em *Salvar alterações*.


.Informações relacionadas
* link:../api/reference_element_api_app_b_access_control.html["Saiba mais sobre os tipos de acesso disponíveis para as APIs do Element."]
* link:concept_system_manage_manage_ldap.html["Habilite a autenticação LDAP com a interface de usuário do Element."]
* link:concept_system_manage_manage_ldap.html["Desativar LDAP"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

