---
permalink: storage/concept_system_manage_nodes_cluster_capacity_in_a_mixed_node_environment.html 
sidebar: sidebar 
keywords: nodes, mixed environment, capacity, cluster capacity, mixed nodes, encrypted, non-encrypted, threshold 
summary: Você pode misturar diferentes tipos de nós em um cluster.  Os modelos SF-Series 2405, 3010, 4805, 6010, 9605, 9010, 19210, 38410 e H-Series podem coexistir em um cluster. 
---
= Capacidade do cluster em um ambiente de nós mistos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode misturar diferentes tipos de nós em um cluster.  Os modelos SF-Series 2405, 3010, 4805, 6010, 9605, 9010, 19210, 38410 e H-Series podem coexistir em um cluster.

A Série H é composta pelos nós H610S-1, H610S-2, H610S-4 e H410S.  Esses nós são compatíveis com 10GbE e 25GbE.

É melhor não misturar nós criptografados com nós não criptografados.  Em um cluster de nós mistos, nenhum nó pode ser maior que 33% da capacidade total do cluster.  Por exemplo, em um cluster com quatro nós da série SF 4805, o maior nó que pode ser adicionado individualmente é um SF 9605.  O limite de capacidade do cluster é calculado com base na perda potencial do maior nó nessa situação.

Dependendo da versão do seu software Element, os seguintes nós de armazenamento da série SF não são suportados:

[cols="40,40"]
|===
| Começando por... | Nó de armazenamento não suportado... 


| Elemento 12.8  a| 
* SF4805
* SF9605
* SF19210
* SF38410




| Elemento 12.7  a| 
* SF2405
* SF9608




| Elemento 12.0  a| 
* SF3010
* SF6010
* SF9010


|===
Se você tentar atualizar um desses nós para uma versão não suportada do Element, verá um erro informando que o nó não é compatível com o Element 12.x.
