---
permalink: storage/concept_intro_management_node.html 
sidebar: sidebar 
keywords: what is the management node, what is the mNode 
summary: 'O nó de gerenciamento (mNode) é uma máquina virtual que funciona em paralelo com um ou mais clusters de armazenamento baseados no software Element.  É utilizado para atualizar e fornecer serviços de sistema, incluindo monitoramento e telemetria, gerenciar ativos e configurações de cluster, executar testes e utilitários de sistema e habilitar o acesso do Suporte da NetApp para solução de problemas.' 
---
= Nó de gerenciamento para o software Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O nó de gerenciamento (mNode) é uma máquina virtual que funciona em paralelo com um ou mais clusters de armazenamento baseados no software Element.  É utilizado para atualizar e fornecer serviços de sistema, incluindo monitoramento e telemetria, gerenciar ativos e configurações de cluster, executar testes e utilitários de sistema e habilitar o acesso do Suporte da NetApp para solução de problemas.

A partir da versão 11.3 do Element, o nó de gerenciamento funciona como um host de microsserviços, permitindo atualizações mais rápidas de serviços de software selecionados fora das versões principais.  Esses microsserviços ou serviços de gerenciamento, como o coletor Active IQ , o QoSSIOC para o plug-in do vCenter e o serviço mNode, são atualizados frequentemente como pacotes de serviços.  Serviços adicionais para atualizações de software do nó de armazenamento e ferramentas de suporte (tunelamento de suporte remoto) também estão disponíveis a partir do nó de gerenciamento.


NOTE: Como prática recomendada, associe apenas um nó de gerenciamento a uma instância do VMware vCenter e evite definir os mesmos recursos de armazenamento e computação ou instâncias do vCenter em vários nós de gerenciamento.
