---
permalink: storage/concept_system_manage_key_external_key_management_api_commands.html 
sidebar: sidebar 
keywords: ekm, api commands, key providers 
summary: Lista de todas as APIs disponíveis para gerenciar e configurar o EKM. 
---
= Comandos da API de gerenciamento de chaves externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lista de todas as APIs disponíveis para gerenciar e configurar o EKM.

Utilizado para estabelecer uma relação de confiança entre o cluster e servidores externos pertencentes ao cliente:

* CriarParDeChavesPúblicasPrivadas
* Solicitação de assinatura de certificado de cliente


Utilizado para definir os detalhes específicos de servidores externos pertencentes ao cliente:

* CriarKeyServerKmip
* ModifyKeyServerKmip
* DeleteKeyServerKmip
* GetKeyServerKmip
* ListKeyServersKmip
* TestKeyServerKmip


Utilizado para criar e manter provedores de chaves que gerenciam servidores de chaves externos:

* CriarProvedorDeChavesKmip
* DeleteKeyProviderKmip
* AddKeyServerToProviderKmip
* RemoverKeyServerFromProviderKmip
* GetKeyProviderKmip
* ListKeyProvidersKmip
* RekeySoftwareEncryptionAtRestMasterKey
* TestKeyProviderKmip


Para obter informações sobre os métodos da API, consulte link:../api/concept_element_api_about_the_api.html["Informações de referência da API"].
