---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: 'Você pode gerenciar os dados em um cluster que executa o software Element a partir da guia Gerenciamento na interface do usuário do Element.  As funções de gerenciamento de cluster disponíveis incluem a criação e o gerenciamento de volumes de dados, contas de usuário, grupos de acesso a volumes, iniciadores e políticas de Qualidade de Serviço (QoS).' 
---
= Aprenda sobre como gerenciar volumes e volumes virtuais.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar os dados em um cluster que executa o software Element a partir da guia Gerenciamento na interface do usuário do Element.  As funções de gerenciamento de cluster disponíveis incluem a criação e o gerenciamento de volumes de dados, grupos de acesso a volumes, iniciadores e políticas de Qualidade de Serviço (QoS).



== Trabalhar com volumes

O sistema SolidFire provisiona armazenamento usando volumes.  Os volumes são dispositivos de bloco acessados ​​pela rede por clientes iSCSI ou Fibre Channel.  Na página Volumes da guia Gerenciamento, você pode criar, modificar, clonar e excluir volumes em um nó.  Você também pode visualizar estatísticas sobre largura de banda e uso de E/S.

link:../storage/concept_data_manage_volumes_quality_of_service_policies.html["Aprenda a trabalhar com volumes"]



== Trabalhar com volumes virtuais

Você pode visualizar informações e executar tarefas para volumes virtuais e seus respectivos contêineres de armazenamento, endpoints de protocolo, associações e hosts usando a interface do usuário do Element.

O sistema de armazenamento de software NetApp Element é fornecido com o recurso de Volumes Virtuais (VVols) desativado.  Você deve executar uma tarefa única de habilitar manualmente a funcionalidade vSphere VVol por meio da interface do usuário do Element.

Após habilitar a funcionalidade VVol, uma aba VVols aparece na interface do usuário, oferecendo opções de monitoramento e gerenciamento limitado relacionadas a VVols.  Além disso, um componente de software do lado do armazenamento, conhecido como VASA Provider, atua como um serviço de reconhecimento de armazenamento para o vSphere.  A maioria dos comandos VVols, como criação, clonagem e edição de VVols, são iniciados por um servidor vCenter ou host ESXi e traduzidos pelo provedor VASA para APIs do Element, o sistema de armazenamento de software do Element.  Os comandos para criar, excluir e gerenciar contêineres de armazenamento, bem como excluir volumes virtuais, podem ser iniciados usando a interface do usuário do Element.

A maioria das configurações necessárias para usar a funcionalidade de Volumes Virtuais com os sistemas de armazenamento de software Element são feitas no vSphere.  Consulte o _Guia de Configuração do VMware vSphere Virtual Volumes para SolidFire Storage_ para registrar o provedor VASA no vCenter, criar e gerenciar datastores VVol e gerenciar o armazenamento com base em políticas.


NOTE: Para o Element 12.5 e versões anteriores, não registre mais de um provedor NetApp Element VASA em uma única instância do vCenter.  Quando um segundo provedor NetApp Element VASA é adicionado, todos os datastores VVOL ficam inacessíveis.


NOTE: O suporte VASA para múltiplos vCenters está disponível como um patch de atualização caso você já tenha registrado um provedor VASA em seu vCenter.  Para instalar, baixe o arquivo VASA39.tar.gz do site. https://mysupport.netapp.com/products/element_software/VASA39/index.html["Downloads de software da NetApp"] Acesse o site e siga as instruções no manifesto.  O provedor NetApp Element VASA utiliza um certificado NetApp .  Com essa correção, o certificado é usado sem modificações pelo vCenter para oferecer suporte a vários vCenters para uso com VASA e VVols.  Não modifique o certificado.  A VASA não oferece suporte a certificados SSL personalizados.

link:../storage/task_data_manage_vvol_enable_virtual_volumes.html["Aprenda a trabalhar com volumes virtuais."]



== Trabalhar com grupos de acesso em volume e iniciadores

Você pode usar iniciadores iSCSI ou iniciadores Fibre Channel para acessar os volumes definidos em grupos de acesso a volumes.

Você pode criar grupos de acesso mapeando IQNs de iniciadores iSCSI ou WWPNs de Fibre Channel em uma coleção de volumes.  Cada IQN adicionado a um grupo de acesso pode acessar todos os volumes do grupo sem a necessidade de autenticação CHAP.

Existem dois tipos de métodos de autenticação CHAP:

* Autenticação CHAP em nível de conta: você pode atribuir a autenticação CHAP à conta.
* Autenticação CHAP em nível de iniciador: você pode atribuir destinos e segredos CHAP exclusivos para iniciadores específicos sem ficar vinculado a um único CHAP em uma única conta.  Essa autenticação CHAP em nível de iniciador substitui as credenciais em nível de conta.


Opcionalmente, com o CHAP por iniciador, você pode impor a autorização do iniciador e a autenticação CHAP por iniciador.  Essas opções podem ser definidas individualmente para cada iniciador, e um grupo de acesso pode conter uma combinação de iniciadores com opções diferentes.

Cada WWPN que você adiciona a um grupo de acesso habilita o acesso à rede Fibre Channel aos volumes no grupo de acesso.


NOTE: Os grupos de acesso por volume têm as seguintes limitações:

* É permitido um máximo de 64 IQNs ou WWPNs em um grupo de acesso.
* Um grupo de acesso pode ser composto por, no máximo, 2000 volumes.
* Um IQN ou WWPN pode pertencer a apenas um grupo de acesso.
* Um único volume pode pertencer a, no máximo, quatro grupos de acesso.


link:../storage/task_data_manage_vol_access_group_create_a_volume_access_group.html["Saiba mais sobre como trabalhar com grupos e iniciadores de acesso em volume."]



== Para maiores informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

