---
permalink: storage/concept_system_manage_nodes_node_versioning_and_compatibility.html 
sidebar: sidebar 
keywords: compatibility, node version, clusters, software version, compatible versions, major, minor, micro 
summary: A compatibilidade do nó é baseada na versão do software Element instalada no nó.  Os clusters de armazenamento baseados no software Element criam automaticamente uma imagem de um nó para a versão do software Element presente no cluster, caso o nó e o cluster não estejam em versões compatíveis. 
---
= Versionamento e compatibilidade do Node.js
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A compatibilidade do nó é baseada na versão do software Element instalada no nó.  Os clusters de armazenamento baseados no software Element criam automaticamente uma imagem de um nó para a versão do software Element presente no cluster, caso o nó e o cluster não estejam em versões compatíveis.

A lista a seguir descreve os níveis de importância das versões de software que compõem o número da versão do software Element:

* *Principal*
+
O primeiro número indica a versão do software.  Um nó com um número de componente principal específico não pode ser adicionado a um cluster que contenha nós com números de patch principal diferentes, nem é possível criar um cluster com nós de versões principais mistas.

* *Menor*
+
O segundo número designa funcionalidades de software menores ou melhorias em funcionalidades de software existentes que foram adicionadas a uma versão principal.  Este componente é incrementado dentro de um componente de versão principal para indicar que esta versão incremental não é compatível com nenhuma outra versão incremental do software Element que possua um componente secundário diferente.  Por exemplo, a versão 11.0 não é compatível com a 11.1, e a versão 11.1 não é compatível com a 11.2.

* *Micro*
+
O terceiro número designa um patch compatível (versão incremental) para a versão do software Element representada pelos componentes major.minor.  Por exemplo, a versão 11.0.1 é compatível com a 11.0.2, e a versão 11.0.2 é compatível com a 11.0.3.



Os números de versão principal e secundária devem corresponder para garantir a compatibilidade.  Os números dos microamplificadores não precisam ser idênticos para serem compatíveis.
