---
permalink: storage/concept_data_manage_vvol_protocol_endpoints.html 
sidebar: sidebar 
keywords: protocol endpoint, access, cluster, storage node, iscsi supported 
summary: Os endpoints de protocolo são pontos de acesso usados ​​por um host para endereçar o armazenamento em um cluster que executa o software NetApp Element .  Os endpoints do protocolo não podem ser excluídos ou modificados por um usuário, não estão associados a uma conta e não podem ser adicionados a um grupo de acesso a volume. 
---
= Saiba mais sobre os pontos de extremidade do protocolo.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os endpoints de protocolo são pontos de acesso usados ​​por um host para endereçar o armazenamento em um cluster que executa o software NetApp Element .  Os endpoints do protocolo não podem ser excluídos ou modificados por um usuário, não estão associados a uma conta e não podem ser adicionados a um grupo de acesso a volume.

Um cluster que executa o software Element cria automaticamente um ponto de extremidade de protocolo por nó de armazenamento no cluster.  Por exemplo, um cluster de armazenamento de seis nós possui seis endpoints de protocolo que são mapeados para cada host ESXi.  Os endpoints do protocolo são gerenciados dinamicamente pelo software Element e são criados, movidos ou removidos conforme necessário, sem qualquer intervenção.  Os endpoints do protocolo são o alvo do multipathing e atuam como um proxy de E/S para LUNs subsidiários.  Cada ponto de extremidade do protocolo consome um endereço SCSI disponível, assim como um alvo iSCSI padrão.  Os endpoints do protocolo aparecem como um dispositivo de armazenamento de bloco único (512 bytes) no cliente vSphere, mas esse dispositivo de armazenamento não está disponível para ser formatado ou usado como armazenamento.

O iSCSI é o único protocolo suportado.  O protocolo Fibre Channel não é suportado.
