---
permalink: storage/concept_system_manage_system_management.html 
sidebar: sidebar 
keywords: element, cluster, fips, cluster, multi-factor authentication, authentication 
summary: 'Você pode gerenciar seu sistema na interface do usuário do Element.  Isso inclui habilitar a autenticação multifator, gerenciar configurações de cluster, oferecer suporte aos Padrões Federais de Processamento de Informações (FIPS) e usar o gerenciamento de chaves externas.' 
---
= Gerencie seu sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar seu sistema na interface do usuário do Element.  Isso inclui habilitar a autenticação multifator, gerenciar configurações de cluster, oferecer suporte aos Padrões Federais de Processamento de Informações (FIPS) e usar o gerenciamento de chaves externas.

* link:task_system_manage_mfa_set_up_multi_factor_authentication.html["Habilitar autenticação multifator"]
* link:task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["Configurar as definições do cluster"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["Crie um cluster que suporte unidades FIPS."]
* link:concept_system_manage_key_get_started_with_external_key_management.html["Comece a gerenciar chaves externas."]




== Para maiores informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

