---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Direitos autorais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. Todos os direitos reservados.  Impresso nos EUA

Nenhuma parte deste documento protegida por direitos autorais pode ser reproduzida de qualquer forma ou por qualquer meio – gráfico, eletrônico ou mecânico, incluindo fotocópia, gravação, fita magnética ou armazenamento em um sistema eletrônico de recuperação – sem a prévia autorização por escrito do detentor dos direitos autorais.

O software derivado do material da NetApp protegido por direitos autorais está sujeito à seguinte licença e isenção de responsabilidade:

Este software é fornecido pela NetApp "tal como está" e sem quaisquer garantias expressas ou implícitas, incluindo, entre outras, as garantias implícitas de comercialização e adequação a um propósito específico, as quais são aqui expressamente excluídas. EM HIPÓTESE ALGUMA A NETAPP SERÁ RESPONSÁVEL POR QUALQUER DANO DIRETO, INDIRETO, INCIDENTAL, ESPECIAL, EXEMPLAR OU CONSEQUENCIAL (INCLUINDO, SEM LIMITAÇÕES, AQUISIÇÃO DE PRODUTOS OU SERVIÇOS SOBRESSALENTES; PERDA DE USO, DADOS OU LUCROS; OU INTERRUPÇÃO DOS NEGÓCIOS), INDEPENDENTEMENTE DA CAUSA E DO PRINCÍPIO DE RESPONSABILIDADE, SEJA EM CONTRATO, POR RESPONSABILIDADE OBJETIVA OU PREJUÍZO (INCLUINDO NEGLIGÊNCIA OU DE OUTRO MODO), RESULTANTE DO USO DESTE SOFTWARE, MESMO SE ADVERTIDA DA RESPONSABILIDADE DE TAL DANO.

A NetApp reserva-se o direito de alterar quaisquer produtos descritos neste documento, a qualquer momento e sem aviso. A NetApp não assume nenhuma responsabilidade nem obrigação decorrentes do uso dos produtos descritos neste documento, exceto conforme expressamente acordado por escrito pela NetApp. O uso ou a compra deste produto não representam uma licença sob quaisquer direitos de patente, direitos de marca comercial ou quaisquer outros direitos de propriedade intelectual da NetApp.

O produto descrito neste manual pode estar protegido por uma ou mais patentes dos EUA, patentes estrangeiras ou pedidos pendentes.

Os dados aqui contidos referem-se a um item comercial (conforme definido em FAR 2.101) e são propriedade da NetApp, Inc. O Governo dos EUA possui uma licença não exclusiva, intransferível, não sublicenciável, mundial, limitada e irrevogável para usar os Dados somente em conexão com e em apoio ao contrato do Governo dos EUA sob o qual os Dados foram fornecidos.  Exceto conforme disposto neste documento, os Dados não podem ser usados, divulgados, reproduzidos, modificados, executados ou exibidos sem a aprovação prévia por escrito da NetApp, Inc. Os direitos de licença do Governo dos Estados Unidos para o Departamento de Defesa são limitados aos direitos identificados na cláusula DFARS 252.227-7015(b).
