---
permalink: storage/reference_snapmirror_relationship_actions.html 
sidebar: sidebar 
keywords: element, ui, relationships, snapmirror, actions, configure 
summary: Você pode configurar um relacionamento na página Relacionamentos do SnapMirror , na guia Proteção de Dados.  As opções do ícone Ações são descritas aqui. 
---
= Ações de relacionamento do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar um relacionamento na página Relacionamentos do SnapMirror , na guia Proteção de Dados.  As opções do ícone Ações são descritas aqui.

* *Editar*: Edita a política ou o cronograma utilizado para o relacionamento.
* *Excluir*: Exclui a relação SnapMirror .  Esta função não exclui o volume de destino.
* *Inicializar*: Executa a primeira transferência inicial de dados para estabelecer um novo relacionamento.
* *Atualização*: Executa uma atualização sob demanda do relacionamento, replicando quaisquer novos dados e cópias de Snapshot incluídas desde a última atualização para o destino.
* *Quiescer*: Impede quaisquer atualizações futuras para um relacionamento.
* *Retomar*: Retoma uma relação que estava em pausa.
* *Break*: Torna o volume de destino de leitura e gravação e interrompe todas as transferências atuais e futuras.  Verifique se os clientes não estão usando o volume de origem original, pois a operação de ressincronização reversa torna o volume de origem original somente leitura.
* *Ressincronizar*: Restabelece uma relação interrompida na mesma direção em que a interrupção ocorreu.
* *Ressincronização Reversa*: Automatiza os passos necessários para criar e inicializar uma nova relação na direção oposta.  Isso só pode ser feito se o relacionamento existente estiver rompido.  Esta operação não excluirá o relacionamento atual.  O volume de origem original retorna à cópia Snapshot comum mais recente e ressincroniza com o destino.  Quaisquer alterações feitas no volume de origem original desde a última atualização bem-sucedida do SnapMirror serão perdidas.  Quaisquer alterações feitas ou novos dados gravados no volume de destino atual são enviados de volta para o volume de origem original.
* *Abortar*: Cancela uma transferência em andamento.  Se uma atualização do SnapMirror for emitida para um relacionamento interrompido, o relacionamento continuará com a última transferência do último ponto de verificação de reinicialização criado antes da interrupção.

