---
permalink: storage/reference_monitor_cluster_fault_codes.html 
sidebar: sidebar 
keywords: cluster fault codes, alerts, error codes, view 
summary: O sistema reporta um erro ou um estado que pode ser de interesse, gerando um código de falha, que é listado na página de Alertas.  Esses códigos ajudam a determinar qual componente do sistema gerou o alerta e por que ele foi acionado. 
---
= Códigos de falha do painel de instrumentos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema reporta um erro ou um estado que pode ser de interesse, gerando um código de falha, que é listado na página de Alertas.  Esses códigos ajudam a determinar qual componente do sistema gerou o alerta e por que ele foi acionado.

A lista a seguir descreve os diferentes tipos de códigos:

* *falha no serviço de autenticação*
+
O serviço de autenticação em um ou mais nós do cluster não está funcionando como esperado.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *disponibilidade de endereços IP de rede virtual baixa*
+
O número de endereços de rede virtuais no bloco de endereços IP é baixo.

+
Para resolver essa falha, adicione mais endereços IP ao bloco de endereços de rede virtuais.

* *blockClusterFull*
+
Não há espaço de armazenamento em bloco livre suficiente para suportar a perda de um único nó.  Consulte o método de API GetClusterFullThreshold para obter detalhes sobre os níveis de preenchimento do cluster.  Essa falha no cluster indica uma das seguintes condições:

+
** estágio3Baixo (Aviso): O limite definido pelo usuário foi ultrapassado.  Ajuste as configurações do Cluster Completo ou adicione mais nós.
** estágio4Crítico (Erro): Não há espaço suficiente para recuperar de uma falha de 1 nó.  A criação de volumes, snapshots e clones não é permitida.
** estágio5CompletamenteConsumido (Crítico)1; Nenhuma gravação ou nova conexão iSCSI é permitida.  As conexões iSCSI atuais serão mantidas.  As gravações falharão até que mais capacidade seja adicionada ao cluster.


+
Para resolver essa falha, limpe ou exclua volumes ou adicione outro nó de armazenamento ao cluster de armazenamento.

* *blocosDegradados*
+
Os dados em bloco não estão mais sendo replicados completamente devido a uma falha.

+
|===


| Gravidade | Descrição 


 a| 
Aviso
 a| 
Apenas duas cópias completas dos dados do bloco estão acessíveis.



 a| 
Erro
 a| 
Apenas uma única cópia completa dos dados do bloco está acessível.



 a| 
Crítico
 a| 
Não há cópias completas dos dados do bloco disponíveis.

|===
+
*Nota:* O estado de aviso só pode ocorrer em um sistema Triple Helix.

+
Para resolver essa falha, restaure quaisquer nós offline ou serviços de bloco, ou entre em contato com o Suporte da NetApp para obter assistência.

* *blockServiceTooFull*
+
Um serviço em bloco está utilizando muito espaço.

+
Para resolver essa falha, adicione mais capacidade provisionada.

* *blockServiceUnhealthy*
+
Um serviço de bloco foi detectado como não íntegro:

+
** Gravidade = Aviso: Nenhuma ação será tomada.  Este período de aviso expirará em cTimeUntilBSIsKilledMSec=330000 milissegundos.
** Gravidade = Erro: O sistema está desativando dados automaticamente e replicando-os para outras unidades em bom estado.
** Gravidade = Crítica: Existem serviços de bloco com falha em vários nós, em número igual ou superior à contagem de replicação (2 para dupla hélice).  Os dados não estão disponíveis e a sincronização dos contêineres não será concluída.
+
Verifique se há problemas de conectividade de rede e erros de hardware.  Outros problemas podem ocorrer se componentes de hardware específicos falharem.  A falha será corrigida quando o serviço de bloqueio estiver acessível ou quando o serviço for desativado.



* *Teste automático BmcFalhou*
+
O Controlador de Gerenciamento da Placa-Mãe (BMC) falhou no autoteste.

+
Entre em contato com o suporte da NetApp para obter assistência.

+
Durante uma atualização para o Element 12.5 ou posterior, o `BmcSelfTestFailed` Não é gerada uma falha para um nó que já possui um BMC com falha, ou quando o BMC de um nó falha durante a atualização.  Os BMCs que falharem nos autotestes durante a atualização emitirão um aviso. `BmcSelfTestFailed` Aviso de falha após a conclusão da atualização em todo o cluster.

* *clockSkewExceedsFaultThreshold*
+
A diferença de tempo entre o nó mestre do cluster e o nó que está apresentando um token excede o limite recomendado.  O cluster de armazenamento não consegue corrigir automaticamente a diferença de tempo entre os nós.

+
Para resolver esse problema, utilize servidores NTP internos à sua rede, em vez dos servidores padrão de instalação.  Se você estiver usando um servidor NTP interno, entre em contato com o Suporte da NetApp para obter assistência.

* *clusterNãoPodeSincronizar*
+
Há uma condição de falta de espaço e os dados nas unidades de armazenamento em bloco offline não podem ser sincronizados com as unidades que ainda estão ativas.

+
Para resolver esse problema, adicione mais espaço de armazenamento.

* *clusterFull*
+
Não há mais espaço de armazenamento livre no cluster de armazenamento.

+
Para resolver esse problema, adicione mais espaço de armazenamento.

* *clusterIOPSAreOverProvisioned*
+
O cluster possui IOPS superdimensionados.  A soma de todos os IOPS mínimos de QoS é maior que o IOPS esperado do cluster.  Não é possível manter a qualidade de serviço mínima para todos os volumes simultaneamente.

+
Para resolver esse problema, reduza as configurações mínimas de IOPS de QoS para os volumes.

* *Limite de Eventos Térmicos da CPU*
+
O número de eventos térmicos da CPU em uma ou mais CPUs excede o limite configurado.

+
Se nenhum novo evento térmico da CPU for detectado dentro de dez minutos, o aviso desaparecerá automaticamente.

* *disableDriveSecurityFailed*
+
O cluster não está configurado para habilitar a segurança de unidade (Criptografia em Repouso), mas pelo menos uma unidade tem a segurança de unidade habilitada, o que significa que desabilitar a segurança de unidade nessas unidades falhou.  Essa falha foi registrada com a severidade "`Aviso``".

+
Para resolver essa falha, verifique os detalhes da falha para descobrir o motivo pelo qual a segurança da unidade não pôde ser desativada.  Possíveis razões são:

+
** Não foi possível obter a chave de criptografia. Investigue o problema de acesso à chave ou ao servidor de chaves externo.
** A operação de desativação falhou na unidade; verifique se foi possível que tenha sido adquirida a chave errada.


+
Se nenhuma dessas for a causa da falha, o disco rígido pode precisar ser substituído.

+
Você pode tentar recuperar uma unidade que não desativa a segurança com sucesso, mesmo quando a chave de autenticação correta é fornecida.  Para realizar esta operação, remova a(s) unidade(s) do sistema movendo-a(s) para Disponível, execute uma exclusão segura na unidade e mova-a(s) de volta para Ativa.

* *par de clusters desconectados*
+
Um par de clusters está desconectado ou configurado incorretamente.

+
Verifique a conectividade de rede entre os clusters.

* *nó remoto desconectado*
+
Um nó remoto está desconectado ou configurado incorretamente.

+
Verifique a conectividade de rede entre os nós.

* *Ponto de extremidade SnapMirror desconectado*
+
Um endpoint remoto do SnapMirror está desconectado ou configurado incorretamente.

+
Verifique a conectividade de rede entre o cluster e o SnapMirrorEndpoint remoto.

* *Vaga de motorista disponível*
+
Um ou mais discos rígidos estão disponíveis no cluster.  Em geral, todos os clusters devem ter todas as unidades adicionadas e nenhuma no estado disponível.  Caso essa falha ocorra inesperadamente, entre em contato com o Suporte da NetApp .

+
Para resolver essa falha, adicione quaisquer unidades disponíveis ao cluster de armazenamento.

* *driveFailed*
+
O cluster retorna essa falha quando uma ou mais unidades falham, indicando uma das seguintes condições:

+
** O gerenciador de unidades não consegue acessar a unidade.
** O serviço de fatia ou bloco falhou muitas vezes, presumivelmente devido a falhas de leitura ou gravação na unidade, e não pode ser reiniciado.
** O disco rígido está desaparecido.
** O serviço principal do nó está inacessível (todos os discos do nó são considerados ausentes/com falha).
** A unidade está bloqueada e não foi possível obter a chave de autenticação da unidade.
** A unidade está bloqueada e a operação de desbloqueio falha.
+
Para resolver esse problema:

** Verifique a conectividade de rede do nó.
** Substitua a unidade.
** Certifique-se de que a chave de autenticação esteja disponível.


* *driveHealthFault*
+
A unidade falhou na verificação de integridade SMART e, como resultado, suas funções estão comprometidas.  Existe um nível de gravidade Crítico para esta falha:

+
** A unidade com número de série: <número de série> no slot: <slot do nó><slot da unidade> falhou na verificação geral de integridade SMART.


+
Para resolver esse problema, substitua a unidade.

* *falha no desgaste do motor*
+
A vida útil restante de um disco rígido caiu abaixo dos limites predefinidos, mas ele ainda está funcionando. Existem dois níveis de gravidade possíveis para essa falha: Crítico e Aviso.

+
** A unidade com número de série: <número de série> no slot: <slot do nó><slot da unidade> apresenta níveis críticos de desgaste.
** A unidade com número de série: <número de série> no slot: <slot do nó><slot da unidade> tem baixas reservas de desgaste.
+
Para resolver esse problema, substitua o disco rígido o mais breve possível.



* *Candidatos a ClusterMaster duplicados*
+
Foi detectado mais de um candidato a mestre de cluster de armazenamento.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *enableDriveSecurityFailed*
+
O cluster está configurado para exigir segurança de unidade (criptografia em repouso), mas a segurança de unidade não pôde ser ativada em pelo menos uma unidade.  Essa falha foi registrada com a severidade "`Aviso``".

+
Para resolver esse problema, verifique os detalhes da falha para descobrir o motivo pelo qual a segurança da unidade não pôde ser ativada.  Possíveis razões são:

+
** Não foi possível obter a chave de criptografia. Investigue o problema de acesso à chave ou ao servidor de chaves externo.
** A operação de habilitação falhou na unidade; verifique se foi possível que uma chave incorreta tenha sido adquirida.  Se nenhuma dessas for a causa da falha, o disco rígido pode precisar ser substituído.


+
Você pode tentar recuperar uma unidade que não consegue ativar a segurança mesmo quando a chave de autenticação correta é fornecida.  Para realizar esta operação, remova a(s) unidade(s) do sistema movendo-a(s) para Disponível, execute uma exclusão segura na unidade e mova-a(s) de volta para Ativa.

* *conjuntoDegradado*
+
A conectividade de rede ou a energia foi perdida em um ou mais nós do conjunto.

+
Para resolver essa falha, restaure a conectividade de rede ou a energia.

* *exceção*
+
Uma falha relatada que não seja uma falha de rotina.  Essas falhas não são removidas automaticamente da fila de falhas.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *espaçomuitocheio*
+
Um serviço de blocos não está respondendo às solicitações de gravação de dados.  Isso faz com que o serviço de fatiamento fique sem espaço para armazenar gravações com falha.

+
Para resolver essa falha, restaure a funcionalidade dos serviços de bloco para permitir que as gravações continuem normalmente e que o espaço com falha seja liberado do serviço de fatiamento.

* *sensor de ventilador*
+
Um sensor da ventoinha falhou ou está ausente.

+
Para resolver esse problema, substitua qualquer componente defeituoso.

* *AcessoFibreChannelDegradado*
+
Um nó Fibre Channel não responde a outros nós no cluster de armazenamento através de seu endereço IP de armazenamento por um determinado período de tempo.  Nesse estado, o nó será considerado não responsivo e gerará uma falha no cluster.

+
Verifique a conectividade da rede.

* *Acesso ao canal de fibra indisponível*
+
Todos os nós Fibre Channel estão sem resposta.  Os IDs dos nós são exibidos.

+
Verifique a conectividade da rede.

* *fibreChannelActiveIxL*
+
O número de IxL Nexus está se aproximando do limite suportado de 8000 sessões ativas por nó Fibre Channel.

+
** O limite recomendado é de 5500.
** O limite de aviso é 7500.
** O limite máximo (não obrigatório) é 8192.


+
Para resolver essa falha, reduza a contagem de IxL Nexus abaixo do limite recomendado de 5500.

* *configuração de canal de fibra*
+
Essa falha no cluster indica uma das seguintes condições:

+
** Existe uma porta Fibre Channel inesperada em um slot PCI.
** Existe um modelo de HBA Fibre Channel inesperado.
** Existe um problema com o firmware de um HBA Fibre Channel.
** Uma porta Fibre Channel não está online.
** Existe um problema persistente na configuração do Fibre Channel passthrough.


+
Entre em contato com o suporte da NetApp para obter assistência.

* *IOPS de canal de fibra*
+
O número total de IOPS está se aproximando do limite de IOPS para nós Fibre Channel no cluster.  Os limites são:

+
** FC0025: Limite de 450 mil IOPS com tamanho de bloco de 4K por nó Fibre Channel.
** FCN001: Limite de 625 mil operações por segundo (OPS) com tamanho de bloco de 4 KB por nó Fibre Channel.


+
Para resolver essa falha, distribua a carga entre todos os nós Fibre Channel disponíveis.

* *fibreChannelStaticIxL*
+
O número de IxL Nexus está se aproximando do limite suportado de 16.000 sessões estáticas por nó Fibre Channel.

+
** O limite recomendado é de 11.000.
** O limite de aviso é 15000.
** O limite máximo (imposto) é 16384.


+
Para resolver essa falha, reduza a contagem de IxL Nexus abaixo do limite recomendado de 11.000.

* *Capacidade do sistema de arquivos baixa*
+
Não há espaço suficiente em um dos sistemas de arquivos.

+
Para resolver esse problema, adicione mais capacidade ao sistema de arquivos.

* *SistemaDeArquivosÉSomenteLeitura*
+
O sistema de arquivos passou para o modo somente leitura.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *fipsDrivesMismatch*
+
Uma unidade não compatível com FIPS foi fisicamente inserida em um nó de armazenamento compatível com FIPS, ou uma unidade FIPS foi fisicamente inserida em um nó de armazenamento não compatível com FIPS.  É gerada uma única falha por nó, listando todas as unidades afetadas.

+
Para resolver essa falha, remova ou substitua a(s) unidade(s) incompatível(is) em questão.

* *fipsDrivesOutOfCompliance*
+
O sistema detectou que a criptografia em repouso foi desativada após a ativação do recurso de unidades FIPS.  Essa falha também é gerada quando o recurso de unidades FIPS está ativado e uma unidade ou nó não FIPS está presente no cluster de armazenamento.

+
Para resolver essa falha, habilite a criptografia em repouso ou remova o hardware não compatível com FIPS do cluster de armazenamento.

* *fipsFalhaNoAutoteste*
+
O subsistema FIPS detectou uma falha durante o autoteste.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *Incompatibilidade de configuração de hardware*
+
Essa falha no cluster indica uma das seguintes condições:

+
** A configuração não corresponde à definição do nó.
** Existe um tamanho de unidade incorreto para este tipo de nó.
** Foi detectada uma unidade de disco não suportada.  Uma possível razão é que a versão do Element instalada não reconhece esta unidade.  Recomenda-se atualizar o software Element neste nó.
** Existe uma incompatibilidade no firmware da unidade.
** O estado de criptografia de unidade não corresponde ao nó.


+
Entre em contato com o suporte da NetApp para obter assistência.

* *idPCertificateExpiration*
+
O certificado SSL do provedor de serviços do cluster, para uso com um provedor de identidade (IdP) de terceiros, está próximo do vencimento ou já expirou.  Esta falha utiliza as seguintes classificações de gravidade com base na urgência:

+
|===


| Gravidade | Descrição 


 a| 
Aviso
 a| 
O certificado expira em 30 dias.



 a| 
Erro
 a| 
O certificado expira em 7 dias.



 a| 
Crítico
 a| 
O certificado expira em 3 dias ou já expirou.

|===
+
Para resolver esse problema, atualize o certificado SSL antes que ele expire.  Utilize o método da API UpdateIdpConfiguration com `refreshCertificateExpirationTime=true` Para fornecer o certificado SSL atualizado.

* *modos de ligação inconsistentes*
+
Os modos de agregação de links no dispositivo VLAN estão ausentes.  Essa falha exibirá o modo de emparelhamento esperado e o modo de emparelhamento atualmente em uso.



* *Mtus inconsistentes*
+
Essa falha no cluster indica uma das seguintes condições:

+
** Incompatibilidade Bond1G: MTUs inconsistentes foram detectadas nas interfaces Bond1G.
** Incompatibilidade no Bond10G: MTUs inconsistentes foram detectadas nas interfaces Bond10G.


+
Esta falha exibe o nó ou nós em questão juntamente com o valor MTU associado.

* *regras de roteamento inconsistentes*
+
As regras de roteamento para esta interface são inconsistentes.

* *Máscaras de sub-rede inconsistentes*
+
A máscara de rede no dispositivo VLAN não corresponde à máscara de rede internamente registrada para a VLAN.  Esta falha exibe a máscara de rede esperada e a máscara de rede atualmente em uso.

* *contagem incorreta de portas de ligação*
+
O número de portas de ligação está incorreto.

* *contagem de nós de fibra do canal configurados inválidos*
+
Uma das duas conexões de nó Fibre Channel esperadas está degradada.  Essa falha ocorre quando apenas um nó Fibre Channel está conectado.

+
Para resolver essa falha, verifique a conectividade da rede do cluster e o cabeamento da rede, e verifique se há serviços com falha.  Caso não haja problemas de rede ou de serviço, entre em contato com o Suporte da NetApp para a substituição do nó Fibre Channel.

* *irqBalanceFailed*
+
Ocorreu uma exceção ao tentar equilibrar as interrupções.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *kmipCertificateFault*
+
** O certificado da Autoridade de Certificação (AC) raiz está perto de expirar.
+
Para resolver essa falha, obtenha um novo certificado da CA raiz com data de expiração de pelo menos 30 dias e use o ModifyKeyServerKmip para fornecer o certificado da CA raiz atualizado.

** O certificado do cliente está perto de expirar.
+
Para resolver essa falha, crie uma nova CSR usando GetClientCertificateSigningRequest, assine-a garantindo que a nova data de expiração seja de pelo menos 30 dias e use ModifyKeyServerKmip para substituir o certificado de cliente KMIP expirado pelo novo certificado.

** O certificado da Autoridade de Certificação Raiz (CA) expirou.
+
Para resolver essa falha, obtenha um novo certificado da CA raiz com data de expiração de pelo menos 30 dias e use o ModifyKeyServerKmip para fornecer o certificado da CA raiz atualizado.

** O certificado do cliente expirou.
+
Para resolver essa falha, crie uma nova CSR usando GetClientCertificateSigningRequest, assine-a garantindo que a nova data de expiração seja de pelo menos 30 dias e use ModifyKeyServerKmip para substituir o certificado de cliente KMIP expirado pelo novo certificado.

** Erro no certificado da Autoridade de Certificação Raiz (CA).
+
Para resolver esse problema, verifique se o certificado fornecido está correto e, se necessário, obtenha-o novamente da autoridade certificadora raiz.  Utilize a ferramenta ModifyKeyServerKmip para instalar o certificado de cliente KMIP correto.

** Erro no certificado do cliente.
+
Para resolver esse problema, verifique se o certificado de cliente KMIP correto está instalado.  A autoridade certificadora raiz do certificado do cliente deve ser instalada no EKS.  Utilize a ferramenta ModifyKeyServerKmip para instalar o certificado de cliente KMIP correto.



* *kmipServerFault*
+
** Falha na conexão
+
Para resolver essa falha, verifique se o servidor de chaves externo está ativo e acessível pela rede.  Use TestKeyServerKimp e TestKeyProviderKmip para testar sua conexão.

** Falha na autenticação
+
Para resolver essa falha, verifique se os certificados de CA raiz e de cliente KMIP corretos estão sendo usados e se a chave privada e o certificado de cliente KMIP correspondem.

** Erro do servidor
+
Para resolver essa falha, verifique os detalhes do erro.  Dependendo do erro retornado, pode ser necessário solucionar problemas no servidor de chaves externo.



* *limiar de memória Ecc*
+
Um grande número de erros ECC, corrigíveis ou não corrigíveis, foi detectado.  Esta falha utiliza as seguintes classificações de gravidade com base na urgência:

+
|===


| Evento | Gravidade | Descrição 


 a| 
Um único DIMM cErrorCount atinge o limite cDimmCorrectableErrWarnThreshold.
 a| 
Aviso
 a| 
Erros de memória ECC corrigíveis acima do limite no DIMM: <Processador> <Slot DIMM>



 a| 
Um único módulo DIMM permanece com o valor de cErrorCount acima de cDimmCorrectableErrWarnThreshold até que o tempo limite cErrorFaultTimer expire para o módulo DIMM.
 a| 
Erro
 a| 
Erros de memória ECC corrigíveis acima do limite no DIMM: <Processador> <DIMM>



 a| 
Um controlador de memória reporta um valor de cErrorCount acima de cMemCtlrCorrectableErrWarnThreshold, e cMemCtlrCorrectableErrWarnDuration foi especificado.
 a| 
Aviso
 a| 
Erros de memória ECC corrigíveis acima do limite no controlador de memória: <Processador> <Controlador de Memória>



 a| 
Um controlador de memória reporta cErrorCount acima de cMemCtlrCorrectableErrWarnThreshold até que cErrorFaultTimer expire para o controlador de memória.
 a| 
Erro
 a| 
Erros de memória ECC corrigíveis acima do limite no DIMM: <Processador> <DIMM>



 a| 
Um único módulo DIMM reporta um uErrorCount acima de zero, mas menor que cDimmUncorrectableErrFaultThreshold.
 a| 
Aviso
 a| 
Erro(s) de memória ECC incorrigível(eis) detectado(s) no DIMM: <Processador> <Slot DIMM>



 a| 
Um único módulo DIMM reporta um uErrorCount de pelo menos cDimmUncorrectableErrFaultThreshold.
 a| 
Erro
 a| 
Erro(s) de memória ECC incorrigível(eis) detectado(s) no DIMM: <Processador> <Slot DIMM>



 a| 
Um controlador de memória reporta um uErrorCount acima de zero, mas menor que cMemCtlrUncorrectableErrFaultThreshold.
 a| 
Aviso
 a| 
Erro(s) de memória ECC não corrigível(is) detectado(s) no controlador de memória: <Processador> <Controlador de Memória>



 a| 
Um controlador de memória reporta um uErrorCount de pelo menos cMemCtlrUncorrectableErrFaultThreshold.
 a| 
Erro
 a| 
Erro(s) de memória ECC não corrigível(is) detectado(s) no controlador de memória: <Processador> <Controlador de Memória>

|===
+
Para resolver esse problema, entre em contato com o suporte da NetApp para obter assistência.

* *limite de uso de memória*
+
O uso de memória está acima do normal.  Esta falha utiliza as seguintes classificações de gravidade com base na urgência:

+

NOTE: Consulte a seção *Detalhes* na descrição da falha para obter informações mais detalhadas sobre o tipo de falha.

+
|===


| Gravidade | Descrição 


 a| 
Aviso
 a| 
A memória do sistema está baixa.



 a| 
Erro
 a| 
A memória do sistema está muito baixa.



 a| 
Crítico
 a| 
A memória do sistema está completamente consumida.

|===
+
Para resolver esse problema, entre em contato com o suporte da NetApp para obter assistência.

* *metadataClusterFull*
+
Não há espaço de armazenamento de metadados livre suficiente para suportar a perda de um único nó.  Consulte o método de API GetClusterFullThreshold para obter detalhes sobre os níveis de preenchimento do cluster.  Essa falha no cluster indica uma das seguintes condições:

+
** estágio3Baixo (Aviso): O limite definido pelo usuário foi ultrapassado.  Ajuste as configurações do Cluster Completo ou adicione mais nós.
** estágio4Crítico (Erro): Não há espaço suficiente para recuperar de uma falha de 1 nó.  A criação de volumes, snapshots e clones não é permitida.
** estágio5CompletamenteConsumido (Crítico)1; Nenhuma gravação ou nova conexão iSCSI é permitida.  As conexões iSCSI atuais serão mantidas.  As gravações falharão até que mais capacidade seja adicionada ao cluster.  Limpar ou excluir dados ou adicionar mais nós.


+
Para resolver essa falha, limpe ou exclua volumes ou adicione outro nó de armazenamento ao cluster de armazenamento.

* *falha na verificação mtu*
+
Um dispositivo de rede não está configurado com o tamanho MTU adequado.

+
Para resolver essa falha, certifique-se de que todas as interfaces de rede e portas do switch estejam configuradas para jumbo frames (MTUs de até 9000 bytes).

* *configuração de rede*
+
Essa falha no cluster indica uma das seguintes condições:

+
** A interface esperada não está presente.
** Existe uma interface duplicada.
** Uma interface configurada está inativa.
** É necessário reiniciar a rede.


+
Entre em contato com o suporte da NetApp para obter assistência.

* *nenhum endereço IP de rede virtual disponível*
+
Não existem endereços de rede virtual disponíveis no bloco de endereços IP.

+
** virtualNetworkID # TAG(\###) não possui endereços IP de armazenamento disponíveis.  Não é possível adicionar nós adicionais ao cluster.


+
Para resolver essa falha, adicione mais endereços IP ao bloco de endereços de rede virtuais.

* *nodeHardwareFault (Interface de rede <nome> inativa ou cabo desconectado)*
+
A interface de rede está inativa ou o cabo está desconectado.

+
Para resolver essa falha, verifique a conectividade de rede do(s) nó(s).

* *nodeHardwareFault (O estado de capacidade de criptografia da unidade não corresponde ao estado de capacidade de criptografia do nó para a unidade no slot <slot do nó><slot da unidade>)*
+
Uma unidade não possui capacidades de criptografia compatíveis com o nó de armazenamento em que está instalada.

* *nodeHardwareFault (Tamanho incorreto da unidade <tipo de unidade> <tamanho real> para a unidade no slot <slot do nó><slot da unidade> para este tipo de nó - tamanho esperado <tamanho esperado>)*
+
Um nó de armazenamento contém uma unidade de disco com tamanho incorreto para esse nó.

* *nodeHardwareFault (Unidade não suportada detectada no slot <node slot><drive slot>; as estatísticas e informações de integridade da unidade não estarão disponíveis)*
+
Um nó de armazenamento contém uma unidade que não suporta.

* *nodeHardwareFault (A unidade no slot <node slot><drive slot> deveria estar usando a versão de firmware <versão esperada>, mas está usando uma versão não suportada <versão atual>)*
+
Um nó de armazenamento contém uma unidade executando uma versão de firmware não suportada.

* *modo de manutenção de nó*
+
Um nó foi colocado em modo de manutenção.  Esta falha utiliza as seguintes classificações de gravidade com base na urgência:

+
|===


| Gravidade | Descrição 


 a| 
Aviso
 a| 
Indica que o nó ainda está em modo de manutenção.



 a| 
Erro
 a| 
Indica que o modo de manutenção não pôde ser desativado, provavelmente devido a falhas ou dispositivos em espera ativos.

|===
+
Para resolver essa falha, desative o modo de manutenção assim que a manutenção for concluída.  Se o erro persistir, entre em contato com o Suporte da NetApp para obter assistência.

* *nodeOffline*
+
O software Element não consegue se comunicar com o nó especificado.  Verifique a conectividade da rede.

* *nãoUsandoModoLACPond*
+
O modo de agregação LACP não está configurado.

+
Para resolver essa falha, utilize o recurso de agregação de links LACP ao implantar nós de armazenamento; os clientes podem apresentar problemas de desempenho se o LACP não estiver habilitado e configurado corretamente.

* *Servidor NTP inacessível*
+
O cluster de armazenamento não consegue se comunicar com o servidor ou servidores NTP especificados.

+
Para resolver esse problema, verifique a configuração do servidor NTP, da rede e do firewall.

* *ntpTimeNotInSync*
+
A diferença entre o horário do cluster de armazenamento e o horário especificado do servidor NTP é muito grande.  O cluster de armazenamento não consegue corrigir a diferença automaticamente.

+
Para resolver esse problema, utilize servidores NTP internos à sua rede, em vez dos servidores padrão de instalação.  Se você estiver usando servidores NTP internos e o problema persistir, entre em contato com o Suporte da NetApp para obter assistência.

* *nvramDeviceStatus*
+
Um dispositivo NVRAM apresenta um erro, está com defeito ou já apresentou falha.  Essa falha apresenta as seguintes gravidades:

+
|===


| Gravidade | Descrição 


 a| 
Aviso
 a| 
O hardware detectou um aviso.  Essa condição pode ser transitória, como um alerta de temperatura.

** Erro de tempo de vida da nvm
** nvmLifetimeStatus
** status de vida útil da fonte de energia
** status da temperatura da fonte de energia
** avisoLimiteExcedido




 a| 
Erro
 a| 
O hardware detectou um erro ou um estado crítico.  O nó mestre do cluster tenta remover a unidade de partição de operação (isso gera um evento de remoção de unidade).  Caso os serviços de partição secundária não estejam disponíveis, a unidade não será removida.  Erros retornados além dos erros de nível de aviso:

** O ponto de montagem do dispositivo NVRAM não existe.
** A partição do dispositivo NVRAM não existe.
** A partição do dispositivo NVRAM existe, mas não está montada.




 a| 
Crítico
 a| 
O hardware detectou um erro ou um estado crítico.  O nó mestre do cluster tenta remover a unidade de partição de operação (isso gera um evento de remoção de unidade).  Caso os serviços de partição secundária não estejam disponíveis, a unidade não será removida.

** persistênciaPerdida
** armStatusSaveNArmed
** csaveStatusError


|===
+
Substitua qualquer componente de hardware com defeito no nó.  Se isso não resolver o problema, entre em contato com o Suporte da NetApp para obter assistência.

* *Erro na fonte de alimentação*
+
Essa falha no cluster indica uma das seguintes condições:

+
** Não há fonte de alimentação presente.
** A fonte de alimentação falhou.
** A entrada de alimentação está ausente ou fora do intervalo.


+
Para resolver essa falha, verifique se há alimentação redundante em todos os nós.  Entre em contato com o suporte da NetApp para obter assistência.

* *EspaçoProvisionadoMuitoCheio*
+
A capacidade total provisionada do cluster está sobrecarregada.

+
Para resolver essa falha, adicione mais espaço provisionado ou exclua e limpe os volumes.

* *remoteRepAsyncDelayExceeded*
+
O atraso assíncrono configurado para a replicação foi excedido.  Verifique a conectividade de rede entre os clusters.

* *remoteRepClusterFull*
+
Os volumes interromperam a replicação remota porque o cluster de armazenamento de destino está muito cheio.

+
Para resolver essa falha, libere algum espaço no cluster de armazenamento de destino.

* *remoteRepSnapshotClusterFull*
+
Os volumes pausaram a replicação remota de snapshots porque o cluster de armazenamento de destino está muito cheio.

+
Para resolver essa falha, libere algum espaço no cluster de armazenamento de destino.

* *limite de snapshots de resposta remota excedido*
+
Os volumes pausaram a replicação remota de snapshots porque o volume do cluster de armazenamento de destino excedeu seu limite de snapshots.

+
Para resolver essa falha, aumente o limite de snapshots no cluster de armazenamento de destino.

* *Erro de ação de agendamento*
+
Uma ou mais das atividades agendadas foram executadas, mas falharam.

+
A falha desaparece se a atividade agendada for executada novamente e com sucesso, se a atividade agendada for excluída ou se a atividade for pausada e retomada.

* *Falha na leitura do sensor*
+
Um sensor não conseguiu se comunicar com o Controlador de Gerenciamento da Placa-Mãe (BMC).

+
Entre em contato com o suporte da NetApp para obter assistência.

* *serviçoNãoEmExecução*
+
Um serviço necessário não está em execução.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *sliceServiceMuitoCheio*
+
Um serviço de fatiamento tem capacidade provisionada insuficiente.

+
Para resolver essa falha, adicione mais capacidade provisionada.

* *sliceServiceUnhealthy*
+
O sistema detectou que um serviço de fatiamento não está íntegro e está desativando-o automaticamente.

+
** Gravidade = Aviso: Nenhuma ação será tomada.  Este período de aviso expirará em 6 minutos.
** Gravidade = Erro: O sistema está desativando dados automaticamente e replicando-os para outras unidades em bom estado.


+
Verifique se há problemas de conectividade de rede e erros de hardware.  Outros problemas podem ocorrer se componentes de hardware específicos falharem.  A falha será corrigida quando o serviço de fatiamento estiver acessível ou quando o serviço for desativado.

* *sshAtivado*
+
O serviço SSH está habilitado em um ou mais nós do cluster de armazenamento.

+
Para resolver essa falha, desative o serviço SSH no(s) nó(s) apropriado(s) ou entre em contato com o Suporte da NetApp para obter assistência.

* *expiração do certificado SSL*
+
O certificado SSL associado a este nó está perto de expirar ou já expirou.  Esta falha utiliza as seguintes classificações de gravidade com base na urgência:

+
|===


| Gravidade | Descrição 


 a| 
Aviso
 a| 
O certificado expira em 30 dias.



 a| 
Erro
 a| 
O certificado expira em 7 dias.



 a| 
Crítico
 a| 
O certificado expira em 3 dias ou já expirou.

|===
+
Para resolver esse problema, renove o certificado SSL.  Caso necessário, entre em contato com o Suporte da NetApp para obter assistência.

* *capacidade ociosa*
+
Um único nó é responsável por mais da metade da capacidade do cluster de armazenamento.

+
Para manter a redundância de dados, o sistema reduz a capacidade do nó maior, de modo que parte de sua capacidade de bloco fique ociosa (não utilizada).

+
Para resolver essa falha, adicione mais unidades aos nós de armazenamento existentes ou adicione nós de armazenamento ao cluster.

* *sensor de temperatura*
+
Um sensor de temperatura está registrando temperaturas acima do normal.  Essa falha pode ser desencadeada em conjunto com falhas powerSupplyError ou fanSensor.

+
Para resolver essa falha, verifique se há obstruções no fluxo de ar perto do cluster de armazenamento.  Caso necessário, entre em contato com o Suporte da NetApp para obter assistência.

* *atualizar*
+
Uma atualização está em andamento há mais de 24 horas.

+
Para resolver essa falha, retome a atualização ou entre em contato com o Suporte da NetApp para obter assistência.

* *Serviço não responsivo*
+
Um serviço deixou de responder.

+
Entre em contato com o suporte da NetApp para obter assistência.

* *Configuração de rede virtual*
+
Essa falha no cluster indica uma das seguintes condições:

+
** Não há interface presente.
** Existe um namespace incorreto em uma interface.
** Existe uma máscara de rede incorreta.
** O endereço IP está incorreto.
** A interface não está ativa e funcionando.
** Existe uma interface supérflua em um nó.


+
Entre em contato com o suporte da NetApp para obter assistência.

* *volumesDegradados*
+
Os volumes secundários ainda não terminaram de ser replicados e sincronizados.  A mensagem desaparece quando a sincronização é concluída.

* *volumesOffline*
+
Um ou mais volumes no cluster de armazenamento estão offline.  A falha *volumeDegraded* também estará presente.

+
Entre em contato com o suporte da NetApp para obter assistência.


