---
permalink: storage/reference_monitor_fibre_channel_session_details.html 
sidebar: sidebar 
keywords: fibre channel sessions, fc, FC, sessions 
summary: 'Você pode encontrar informações sobre as sessões Fibre Channel (FC) ativas que estão conectadas ao cluster.' 
---
= Detalhes da sessão Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode encontrar informações sobre as sessões Fibre Channel (FC) ativas que estão conectadas ao cluster.

A lista a seguir descreve as informações que você pode encontrar sobre as sessões FC conectadas ao cluster:

* *ID do nó*
+
O nó que hospeda a sessão da conexão.

* *Nome do nó*
+
Nome do nó gerado pelo sistema.

* *ID do Iniciador*
+
Um ID gerado pelo sistema para o iniciador.

* *Iniciador WWPN*
+
O nome do porto que deu origem a ele em todo o mundo.

* *Alias do Iniciador*
+
Um nome opcional para o iniciador que facilita a sua localização em uma lista longa.

* *Alvo WWPN*
+
O nome do porto alvo em todo o mundo.

* *Grupo de Acesso por Volume*
+
Nome do grupo de acesso ao volume ao qual a sessão pertence.

* *ID do Grupo de Acesso por Volume*
+
ID gerado pelo sistema para o grupo de acesso.


