---
permalink: storage/task_intro_view_api_activity_in_real_time.html 
sidebar: sidebar 
keywords: solidfire api, element api, element os, element, viewing the API log, viewing API calls 
summary: O sistema Element utiliza a API NetApp Element como base para seus recursos e funcionalidades.  A interface de usuário Element UI permite visualizar vários tipos de atividade de API em tempo real no sistema enquanto você usa a interface.  Com o registro da API, você pode visualizar a atividade da API iniciada pelo usuário e em segundo plano pelo sistema, bem como as chamadas de API feitas na página que você está visualizando no momento. 
---
= Visualizar atividade da API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema Element utiliza a API NetApp Element como base para seus recursos e funcionalidades.  A interface de usuário Element UI permite visualizar vários tipos de atividade de API em tempo real no sistema enquanto você usa a interface.  Com o registro da API, você pode visualizar a atividade da API iniciada pelo usuário e em segundo plano pelo sistema, bem como as chamadas de API feitas na página que você está visualizando no momento.

Você pode usar o registro da API para identificar quais métodos da API são usados para determinadas tarefas e ver como usar os métodos e objetos da API para criar aplicativos personalizados.

Para obter informações sobre cada método, consulte link:../api/concept_element_api_about_the_api.html["Referência da API do Element Software"].

. Na barra de navegação da interface do usuário do Element, clique em *Log da API*.
. Para modificar o tipo de atividade da API exibida na janela de registro da API, execute as seguintes etapas:
+
.. Selecione *Solicitações* para exibir o tráfego de solicitações da API.
.. Selecione *Respostas* para exibir o tráfego de respostas da API.
.. Filtre os tipos de tráfego da API selecionando uma das seguintes opções:
+
*** *Iniciado pelo usuário*: Tráfego de API gerado por suas atividades durante esta sessão da interface web.
*** *Solicitação em segundo plano*: Tráfego de API gerado pela atividade do sistema em segundo plano.
*** *Página atual*: Tráfego da API gerado por tarefas na página que você está visualizando.








== Encontre mais informações

* link:../api/concept_element_api_about_the_api.html["Gerenciando o armazenamento com a API Element"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

