---
permalink: storage/task_system_manage_cluster_set_the_cluster_full_threshold.html 
sidebar: sidebar 
keywords: cluster fullness, setting threshold, metadata, warning 
summary: Você pode alterar o nível em que o sistema gera um aviso de preenchimento do cluster de blocos seguindo os passos abaixo.  Além disso, você pode usar o método de API ModifyClusterFullThreshold para alterar o nível em que o sistema gera um aviso de bloqueio ou de metadados. 
---
= Defina o limite máximo de clusters cheios.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar o nível em que o sistema gera um aviso de preenchimento do cluster de blocos seguindo os passos abaixo.  Além disso, você pode usar o método de API ModifyClusterFullThreshold para alterar o nível em que o sistema gera um aviso de bloqueio ou de metadados.

.O que você vai precisar
Você precisa ter privilégios de administrador de cluster.

.Passos
. Clique em *Cluster* > *Configurações*.
. Na seção Configurações Completas do Cluster, insira uma porcentagem em *Exibir um alerta de aviso quando _% da capacidade permanecer antes que o Helix não consiga se recuperar de uma falha de nó*.
. Clique em *Salvar alterações*.




== Encontre mais informações

https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/SF_Series/How_are_the_blockSpace_thresholds_calculated_for_Element["Como são calculados os limites do blockSpace para o Elemento?"^]
