---
permalink: storage/task_data_manage_vvol_enable_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volumes, enable, functionality on the cluster, vvols 
summary: 'Você deve habilitar manualmente a funcionalidade de Volumes Virtuais do vSphere (VVols) por meio do software NetApp Element .  O sistema de software Element vem com a funcionalidade VVols desativada por padrão e não é ativada automaticamente como parte de uma nova instalação ou atualização.  Habilitar o recurso VVols é uma tarefa de configuração única.' 
---
= Ativar volumes virtuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve habilitar manualmente a funcionalidade de Volumes Virtuais do vSphere (VVols) por meio do software NetApp Element .  O sistema de software Element vem com a funcionalidade VVols desativada por padrão e não é ativada automaticamente como parte de uma nova instalação ou atualização.  Habilitar o recurso VVols é uma tarefa de configuração única.

.O que você vai precisar
* O cluster deve estar executando o Element 9.0 ou posterior.
* O cluster deve estar conectado a um ambiente ESXi 6.0 ou posterior que seja compatível com VVols.
* Se você estiver usando o Element 11.3 ou posterior, o cluster deve estar conectado a um ambiente ESXi 6.0 update 3 ou posterior.



IMPORTANT: Habilitar a funcionalidade de Volumes Virtuais do vSphere altera permanentemente a configuração do software Element.  Você só deve habilitar a funcionalidade VVols se o seu cluster estiver conectado a um ambiente VMware ESXi compatível com VVols.  Você pode desativar o recurso VVols e restaurar as configurações padrão somente retornando o cluster à imagem de fábrica, o que exclui todos os dados do sistema.

.Passos
. Selecione *Clusters* > *Configurações*.
. Encontre as configurações específicas do cluster para Volumes Virtuais.
. Clique em *Ativar volumes virtuais*.
. Clique em *Sim* para confirmar a alteração na configuração dos Volumes Virtuais.
+
A aba *VVols* aparece na interface do usuário do Element.

+

NOTE: Quando a funcionalidade VVols está habilitada, o cluster SolidFire inicia o provedor VASA, abre a porta 8444 para o tráfego VASA e cria endpoints de protocolo que podem ser descobertos pelo vCenter e por todos os hosts ESXi.

. Copie o URL do provedor VASA das configurações de Volumes Virtuais (VVols) em *Clusters* > *Configurações*.  Você usará este URL para registrar o provedor VASA no vCenter.
. Crie um contêiner de armazenamento em *VVols* > *Contêineres de armazenamento*.
+

NOTE: Você deve criar pelo menos um contêiner de armazenamento para que as VMs possam ser provisionadas em um datastore VVol.

. Selecione *VVols* > *Pontos finais do protocolo*.
. Verifique se um ponto de extremidade do protocolo foi criado para cada nó do cluster.
+

NOTE: São necessárias tarefas de configuração adicionais no vSphere.  Consulte o _Guia de Configuração do VMware vSphere Virtual Volumes para SolidFire Storage_ para registrar o provedor VASA no vCenter, criar e gerenciar datastores VVol e gerenciar o armazenamento com base em políticas.





== Encontre mais informações

https://www.netapp.com/pdf.html?item=/media/10516-tr4642pdf.pdf["Guia de configuração de volumes virtuais do VMware vSphere para armazenamento SolidFire"^]
