---
permalink: storage/task-element-replication-make-destination-volume-writeable.html 
sidebar: sidebar 
keywords: ontap, cli, make, destination, volume, write 
summary: 'Você precisa tornar o volume de destino gravável antes de poder fornecer dados desse volume aos clientes.  Você pode usar o comando `snapmirror quiesce` para interromper as transferências agendadas para o destino, o comando `snapmirror abort` para interromper as transferências em andamento e o comando `snapmirror break` para tornar o destino gravável.' 
---
= Torne o volume de destino gravável.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um desastre desabilita o site primário de um relacionamento de recuperação de desastres do SnapMirror , você pode fornecer dados do volume de destino com interrupção mínima.  Você poderá reativar o volume de origem quando o serviço for restaurado no site principal.

Você precisa tornar o volume de destino gravável antes de poder fornecer dados desse volume aos clientes.  Você pode usar o `snapmirror quiesce` comando para interromper as transferências programadas para o destino, o `snapmirror abort` comando para interromper as transferências em andamento, e o `snapmirror break` comando para tornar o destino gravável.

.Sobre esta tarefa
Você deve especificar o caminho de origem do elemento no formato `<hostip:>/lun/<name>` , onde "`lun`" é a string real "`lun`" e `name` é o nome do volume do Elemento.

.Passos
. Interrompa as transferências programadas para o destino:
+
`snapmirror quiesce -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obter a sintaxe completa dos comandos, consulte a página do manual.

+
O exemplo a seguir interrompe as transferências agendadas entre o volume de origem `0005` no endereço IP 10.0.0.11 e o volume de destino `volA_dst` sobre `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Interrompa as transferências em andamento para o destino:
+
`snapmirror abort -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obter a sintaxe completa dos comandos, consulte a página do manual.

+
O exemplo a seguir interrompe as transferências em andamento entre o volume de origem e o volume de origem. `0005` no endereço IP 10.0.0.11 e o volume de destino `volA_dst` sobre `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror abort -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Romper o relacionamento de resposta a desastres (DR) com o SnapMirror :
+
`snapmirror break -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obter a sintaxe completa dos comandos, consulte a página do manual.

+
O exemplo a seguir quebra a relação entre o volume de origem `0005` no endereço IP 10.0.0.11 e o volume de destino `volA_dst` sobre `svm_backup` e o volume de destino `volA_dst` sobre `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror break -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

