---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: Você pode adicionar vários iniciadores a um grupo de acesso a volumes existente para permitir o acesso a volumes no grupo de acesso a volumes com ou sem a necessidade de autenticação CHAP. 
---
= Adicionar vários iniciadores a um grupo de acesso a volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar vários iniciadores a um grupo de acesso a volumes existente para permitir o acesso a volumes no grupo de acesso a volumes com ou sem a necessidade de autenticação CHAP.

Ao adicionar iniciadores a um grupo de acesso a volumes, os iniciadores passam a ter acesso a todos os volumes desse grupo.


TIP: Você pode encontrar o iniciador de cada volume clicando no ícone Ações e, em seguida, em *Ver detalhes* do volume na lista de volumes ativos.

Você pode adicionar vários iniciadores a um grupo de acesso a volumes existente para habilitar o acesso a volumes e atribuir credenciais CHAP exclusivas para cada iniciador dentro desse grupo de acesso a volumes.  Isso permite que você aplique essa opção a grupos de acesso por volume que já existem.

Você pode atribuir atributos CHAP baseados no iniciador usando uma chamada de API.  Para adicionar um nome de conta CHAP e credenciais por iniciador, você deve usar a chamada de API ModifyInitiator para remover e adicionar acesso e atributos CHAP.

Para mais detalhes, vejalink:../api/concept_element_api_about_the_api.html["Gerencie o armazenamento com a API Element."] .

.Passos
. Clique em *Gestão* > *Iniciadores*.
. Selecione os iniciadores que deseja adicionar a um grupo de acesso.
. Clique no botão *Ações em massa*.
. Clique em *Adicionar ao Grupo de Acesso por Volume*.
. Na caixa de diálogo Adicionar ao Grupo de Acesso ao Volume, selecione um grupo de acesso na lista *Grupo de Acesso ao Volume*.
. Clique em *Adicionar*.

