---
permalink: storage/task_system_manage_snmp_configure_an_snmp_requestor.html 
sidebar: sidebar 
keywords: SNMP requestor, config, enable, disable, snmp requests 
summary: Quando o SNMP versão 2 está habilitado, você pode ativar ou desativar um solicitante e configurar os solicitantes para receber solicitações SNMP autorizadas. 
---
= Configure um solicitante SNMP.
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o SNMP versão 2 está habilitado, você pode ativar ou desativar um solicitante e configurar os solicitantes para receber solicitações SNMP autorizadas.

. Clique no menu: Cluster [SNMP].
. Em *Configurações gerais de SNMP*, clique em *Sim* para ativar o SNMP.
. Na lista *Versão*, selecione *Versão 2*.
. Na seção *Solicitantes*, insira as informações de *Comunidade* e *Rede*.
+

NOTE: Por padrão, a string da comunidade é pública e a rede é localhost.  Você pode alterar essas configurações padrão.

. *Opcional:* Para adicionar outro solicitante, clique em *Adicionar um Solicitante* e insira as informações de *Nome da Comunidade* e *Rede*.
. Clique em *Salvar alterações*.




== Encontre mais informações

* xref:task_system_manage_snmp_configure_snmp_traps.adoc[Configurar traps SNMP]
* xref:task_system_manage_snmp_view_managed_object_data.adoc[Visualize os dados do objeto gerenciado usando arquivos de base de informações de gerenciamento.]

