---
permalink: storage/task-element-replication-initialize-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, initialize, replication, relationship 
summary: 'Para todos os tipos de relacionamento, a inicialização realiza uma transferência de linha de base: ela cria uma cópia instantânea do volume de origem e, em seguida, transfere essa cópia e todos os blocos de dados aos quais ela faz referência para o volume de destino.' 
---
= Inicializar uma relação de replicação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para todos os tipos de relacionamento, a inicialização realiza uma _transferência de linha de base_: ela cria uma cópia instantânea do volume de origem e, em seguida, transfere essa cópia e todos os blocos de dados aos quais ela faz referência para o volume de destino.

.Antes de começar
* O nó Element que contém o volume a ser replicado deve ter sido disponibilizado ao ONTAP.
* O volume Element deve ter sido habilitado para replicação SnapMirror .
* Se você estiver usando o tipo de política "`mirror-vault`", um rótulo SnapMirror deve ter sido configurado para que as cópias de snapshot do Elemento sejam replicadas.
+
[NOTE]
====
Você só pode realizar esta tarefa nolink:concept_snapmirror_labels.html["Interface web do software Element"] ou usando olink:../api/concept_element_api_snapshots_overview.html["Métodos API"] .

====


.Sobre esta tarefa
Você deve especificar o caminho de origem do elemento no formato `<hostip:>/lun/<name>` , onde "`lun`" é a string real "`lun`" e `_name_` é o nome do volume do Elemento.

A inicialização pode ser demorada.  Você pode querer executar a transferência de linha de base fora dos horários de pico.

[NOTE]
====
Se a inicialização de um relacionamento de uma origem ONTAP para um destino Element falhar por qualquer motivo, ela continuará falhando mesmo depois que você corrigir o problema (um nome de LUN inválido, por exemplo).  A solução alternativa é a seguinte:

. Exclua o relacionamento.
. Exclua o volume de destino do elemento.
. Crie um novo volume de destino Element.
. Crie e inicialize um novo relacionamento da origem ONTAP para o volume de destino do Elemento.


====
.Etapa
. Inicializar uma relação de replicação:
+
`snapmirror initialize -source-path <hostip:>/lun/<name> -destination-path <SVM:volume|cluster://SVM/volume>`

+
Para obter a sintaxe completa dos comandos, consulte a página do manual.

+
O exemplo a seguir inicializa a relação entre o volume de origem `0005` no endereço IP 10.0.0.11 e o volume de destino `volA_dst` sobre `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

