---
permalink: storage/task_system_manage_virtual_add_a_virtual_network.html 
sidebar: sidebar 
keywords: virtual network, add, cluster configuration, cluster nodes, svip, vlans, vrf, view, network details, 
summary: Você pode adicionar uma nova rede virtual a uma configuração de cluster para habilitar uma conexão de ambiente multi-inquilino a um cluster que executa o software Element. 
---
= Adicionar uma rede virtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar uma nova rede virtual a uma configuração de cluster para habilitar uma conexão de ambiente multi-inquilino a um cluster que executa o software Element.

.O que você vai precisar
* Identifique o bloco de endereços IP que será atribuído às redes virtuais nos nós do cluster.
* Identifique um endereço IP de rede de armazenamento (SVIP) que será usado como ponto final para todo o tráfego de armazenamento do NetApp Element .



IMPORTANT: Para esta configuração, você deve considerar os seguintes critérios:

* As VLANs que não possuem VRF habilitado exigem que os iniciadores estejam na mesma sub-rede que o SVIP.
* As VLANs com suporte a VRF não exigem que os iniciadores estejam na mesma sub-rede que o SVIP, e o roteamento é suportado.
* O SVIP padrão não exige que os iniciadores estejam na mesma sub-rede que o SVIP, e o roteamento é suportado.


Ao adicionar uma rede virtual, é criada uma interface para cada nó, e cada uma delas requer um endereço IP de rede virtual.  O número de endereços IP que você especificar ao criar uma nova rede virtual deve ser igual ou maior que o número de nós no cluster.  Os endereços de rede virtuais são provisionados em massa e atribuídos a nós individuais automaticamente.  Não é necessário atribuir manualmente endereços de rede virtuais aos nós do cluster.

.Passos
. Clique em *Cluster* > *Rede*.
. Clique em *Criar VLAN*.
. Na caixa de diálogo *Criar uma nova VLAN*, insira os valores nos seguintes campos:
+
** *Nome da VLAN*
** *Etiqueta VLAN*
** *SVIP*
** *Máscara de rede*
** (Opcional) *Descrição*


. Insira o endereço *IP inicial* para o intervalo de endereços IP em *Blocos de Endereços IP*.
. Insira o *Tamanho* do intervalo de IP como o número de endereços IP a serem incluídos no bloco.
. Clique em *Adicionar um bloco* para adicionar um bloco não contínuo de endereços IP para esta VLAN.
. Clique em *Criar VLAN*.




== Veja os detalhes da rede virtual

.Passos
. Clique em *Cluster* > *Rede*.
. Revise os detalhes.
+
** *ID*: Identificação única da rede VLAN, atribuída pelo sistema.
** *Nome*: Nome exclusivo atribuído pelo usuário para a rede VLAN.
** *Etiqueta VLAN*: Etiqueta VLAN atribuída quando a rede virtual foi criada.
** *SVIP*: Endereço IP virtual de armazenamento atribuído à rede virtual.
** *Máscara de rede*: Máscara de rede para esta rede virtual.
** *Gateway*: Endereço IP exclusivo de um gateway de rede virtual.  O VRF deve estar ativado.
** *VRF ativado*: Indica se o roteamento e encaminhamento virtual está ativado ou não.
** *IPs Utilizados*: O intervalo de endereços IP da rede virtual utilizados para a rede virtual.



