---
permalink: storage/task_data_protection_using_volume_snapshots.html 
sidebar: sidebar 
keywords: data protection, volume snapshots, roll back volume, replicate snapshots 
summary: Um instantâneo de volume é uma cópia de um volume em um determinado momento.  Você pode tirar um instantâneo de um volume e usar esse instantâneo posteriormente, caso precise restaurar o volume ao estado em que se encontrava no momento da criação do instantâneo. 
---
= Utilize snapshots de volume para proteção de dados.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um instantâneo de volume é uma cópia de um volume em um determinado momento.  Você pode tirar um instantâneo de um volume e usar esse instantâneo posteriormente, caso precise restaurar o volume ao estado em que se encontrava no momento da criação do instantâneo.

Os snapshots são semelhantes aos clones de volume.  No entanto, os snapshots são simplesmente réplicas dos metadados do volume, portanto, você não pode montá-los nem gravar neles.  A criação de um snapshot de volume também requer apenas uma pequena quantidade de recursos e espaço do sistema, o que torna a criação de snapshots mais rápida do que a clonagem.

Você pode tirar uma foto instantânea de um volume individual ou de um conjunto de volumes.

Opcionalmente, replique os snapshots para um cluster remoto e use-os como uma cópia de backup do volume.  Isso permite reverter um volume para um ponto específico no tempo usando o snapshot replicado.  Alternativamente, você pode criar um clone de um volume a partir de um snapshot replicado.



== Encontre mais informações

* xref:task_data_protection_use_individual_volume_snapshots.adoc[Utilize snapshots de volume individuais para proteção de dados.]
* xref:task_data_protection_use_group_snapshots_for_data_protection.adoc[Utilizando snapshots de grupo para tarefas de proteção de dados]
* xref:task_data_protection_schedule_a_snapshot_task.adoc[Agendando um instantâneo]

