---
permalink: storage/task_snapmirror_transfer_or_one_time_migration_from_ontap_to_element.html 
sidebar: sidebar 
keywords: element, ui, transfer, perform, source, volume, snapmirror, dr, disaster, recovery, one-time, migration 
summary: Normalmente, quando você usa o SnapMirror para recuperação de desastres de um cluster de armazenamento SolidFire executando o software NetApp Element para o software ONTAP , o Element é a origem e o ONTAP é o destino.  No entanto, em alguns casos, o sistema de armazenamento ONTAP pode servir como origem e o Element como destino. 
---
= Realize uma transferência ou migração única do ONTAP para o Element.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Normalmente, quando você usa o SnapMirror para recuperação de desastres de um cluster de armazenamento SolidFire executando o software NetApp Element para o software ONTAP , o Element é a origem e o ONTAP é o destino.  No entanto, em alguns casos, o sistema de armazenamento ONTAP pode servir como origem e o Element como destino.

* Existem dois cenários:
+
** Não existe histórico de relacionamento em recuperação de desastres.  Siga todos os passos deste procedimento.
** Existe um histórico de recuperação de desastres, mas não entre os volumes que estão sendo usados para essa mitigação.  Nesse caso, siga apenas os passos 3 e 4 abaixo.




.O que você vai precisar
* O nó de destino do elemento deve ter sido tornado acessível ao ONTAP.
* O volume Element deve ter sido habilitado para replicação SnapMirror .


Você deve especificar o caminho de destino do Elemento no formato hostip:/lun/<id_number>, onde lun é a string "`lun`" e id_number é o ID do volume do Elemento.

.Passos
. Utilizando o ONTAP, crie o relacionamento com o cluster Element:
+
[listing]
----
snapmirror create -source-path SVM:volume|cluster://SVM/volume
-destination-path hostip:/lun/name -type XDP -schedule schedule -policy
    policy
----
+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst
-destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
. Verifique se a relação SnapMirror foi criada usando o comando ONTAP snapmirror show.
+
Consulte as informações sobre como criar uma relação de replicação na documentação do ONTAP e, para obter a sintaxe completa dos comandos, consulte a página de manual do ONTAP .

. Usando o `ElementCreateVolume` API, crie o volume de destino e defina o modo de acesso do volume de destino como SnapMirror:
+
Crie um volume de Elemento usando a API de Elemento.

+
[listing]
----
{
   "method": "CreateVolume",
   "params": {
        "name": "SMTargetVolumeTest2",
        "accountID": 1,
        "totalSize": 100000000000,
        "enable512e": true,
        "attributes": {},
        "qosPolicyID": 1,
        "enableSnapMirrorReplication": true,
        "access": "snapMirrorTarget"
    },
    "id": 1
}
----
. Inicialize a relação de replicação usando o ONTAP. `snapmirror initialize` comando:
+
[listing]
----
snapmirror initialize -source-path hostip:/lun/name
-destination-path SVM:volume|cluster://SVM/volume
----

