---
permalink: storage/task_system_manage_cluster_ntp_configure.html 
sidebar: sidebar 
keywords: ntp, cluster, query, fqdn, dns server 
summary: 'Você pode instruir cada nó em um cluster a consultar um servidor de Protocolo de Tempo de Rede (NTP) para obter atualizações.  O cluster contata apenas os servidores configurados e solicita informações NTP deles.' 
---
= Configure os servidores Network Time Protocol (NTP) para que o cluster possa realizar consultas.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instruir cada nó em um cluster a consultar um servidor de Protocolo de Tempo de Rede (NTP) em busca de atualizações.  O cluster contata apenas os servidores configurados e solicita informações NTP deles.

O NTP é usado para sincronizar relógios em uma rede.  A conexão a um servidor NTP interno ou externo deve fazer parte da configuração inicial do cluster.

Configure o NTP no cluster para apontar para um servidor NTP local.  Você pode usar o endereço IP ou o nome de host FQDN.  O servidor NTP padrão no momento da criação do cluster é definido como us.pool.ntp.org; no entanto, uma conexão com este site nem sempre pode ser estabelecida, dependendo da localização física do cluster SolidFire .

A utilização do FQDN depende de as configurações de DNS de cada nó de armazenamento estarem implementadas e operacionais.  Para isso, configure os servidores DNS em cada nó de armazenamento e certifique-se de que as portas estejam abertas, consultando a página de Requisitos de Porta de Rede.

Você pode inserir até cinco servidores NTP diferentes.


NOTE: Você pode usar endereços IPv4 e IPv6.

.O que você vai precisar
Você precisa ter privilégios de administrador de cluster para configurar essa opção.

.Passos
. Configure uma lista de IPs e/ou FQDNs nas configurações do servidor.
. Certifique-se de que o DNS esteja configurado corretamente nos nós.
. Clique em *Cluster* > *Configurações*.
. Em Configurações do Protocolo de Tempo de Rede, selecione *Não*, que utiliza a configuração NTP padrão.
. Clique em *Salvar alterações*.




== Encontre mais informações

* link:../storage/task_system_manage_cluster_ntp_configure_to_listen_for_ntp_broadcasts.html["Configure o cluster para escutar transmissões NTP."]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

