---
permalink: storage/task_monitor_system_alerts.html 
sidebar: sidebar 
keywords: system alerts, view, cluster faults, system errors 
summary: Você pode visualizar alertas para obter informações sobre falhas no cluster ou erros no sistema.  Os alertas podem ser informações, avisos ou erros e são um bom indicador de quão bem o cluster está funcionando.  A maioria dos erros se resolve automaticamente. 
---
= Visualizar alertas do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar alertas para obter informações sobre falhas no cluster ou erros no sistema.  Os alertas podem ser informações, avisos ou erros e são um bom indicador de quão bem o cluster está funcionando.  A maioria dos erros se resolve automaticamente.

Você pode usar o método de API ListClusterFaults para automatizar o monitoramento de alertas.  Isso permite que você seja notificado sobre todos os alertas que ocorrerem.

. Na interface do usuário do Element, selecione *Relatórios* > *Alertas*.
+
O sistema atualiza os alertas na página a cada 30 segundos.

+
Para cada evento, você verá as seguintes informações:

+
|===


| Item | Descrição 


 a| 
EU IA
 a| 
Identificador único associado a um alerta de cluster.



 a| 
Gravidade
 a| 
O grau de importância do alerta. Valores possíveis:

** Aviso: Problema menor que poderá necessitar de atenção em breve.  As atualizações do sistema ainda são permitidas.
** Erro: Uma falha que pode causar degradação de desempenho ou perda de alta disponibilidade (HA).  Em geral, os erros não devem afetar o serviço.
** Crítico: Uma falha grave que afeta o serviço.  O sistema não consegue atender às solicitações de API ou de entrada/saída do cliente.  Operar nesse estado pode levar à potencial perda de dados.
** bestPractice: Uma prática recomendada para a configuração do sistema não está sendo utilizada.




 a| 
Tipo
 a| 
O componente afetado pela falha.  Pode ser um nó, unidade, cluster, serviço ou volume.



 a| 
Nó
 a| 
ID do nó ao qual esta falha se refere.  Incluído para falhas de nó e de acionamento, caso contrário, definido como - (traço).



 a| 
ID da unidade
 a| 
Identificação da unidade à qual esta falha se refere.  Incluído para falhas de acionamento, caso contrário, definido como - (traço).



 a| 
Código de erro
 a| 
Um código descritivo que indica a causa da falha.



 a| 
Detalhes
 a| 
Descrição da falha com detalhes adicionais.



 a| 
Data
 a| 
A data e a hora em que a falha foi registrada.

|===
. Clique em *Mostrar detalhes* para visualizar informações específicas sobre um alerta.
. Para visualizar os detalhes de todos os alertas na página, clique na coluna Detalhes.
+
Após o sistema resolver um alerta, todas as informações sobre o alerta, incluindo a data em que foi resolvido, são movidas para a área "Resolvidos".





== Encontre mais informações

* xref:reference_monitor_cluster_fault_codes.adoc[Códigos de falha do painel de instrumentos]
* link:../api/concept_element_api_about_the_api.html["Gerencie o armazenamento com a API Element."]

