---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: Você pode emparelhar um volume com outro volume em um cluster remoto se tiver credenciais de administrador do cluster remoto. 
---
= Emparelhe volumes usando um ID de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode emparelhar um volume com outro volume em um cluster remoto se tiver acesso de administrador de cluster a ambos os clusters nos quais os volumes serão emparelhados. Este método utiliza o ID do volume no cluster remoto para iniciar uma conexão.

.O que você vai precisar
* Certifique-se de que os clusters que contêm os volumes estejam emparelhados.
* Crie um novo volume no cluster remoto.
+

NOTE: Você pode atribuir uma origem e um destino de replicação após o processo de emparelhamento.  Uma origem ou destino de replicação pode ser qualquer volume em um par de volumes.  Você deve criar um volume de destino que não contenha dados e que tenha as mesmas características do volume de origem, como tamanho, configuração de tamanho de bloco para os volumes (512e ou 4k) e configuração de QoS.  Se você atribuir um volume existente como destino da replicação, os dados desse volume serão sobrescritos.  O volume alvo pode ser maior ou igual em tamanho ao volume de origem, mas não pode ser menor.

* Saiba o ID do volume de destino.


.Passos
. Selecione *Gestão* > *Volumes*.
. Clique no ícone *Ações* do volume que deseja emparelhar.
. Clique em *Emparelhar*.
. Na caixa de diálogo *Emparelhar Volume*, selecione *Iniciar Emparelhamento*.
. Selecione *Sim* para indicar que você tem acesso ao cluster remoto.
. Selecione um *Modo de Replicação* na lista:
+
** *Em tempo real (assíncrono)*: As gravações são confirmadas ao cliente após serem confirmadas no cluster de origem.
** *Em tempo real (síncrono)*: As gravações são confirmadas ao cliente após serem efetuadas nos clusters de origem e de destino.
** *Somente snapshots*: Apenas os snapshots criados no cluster de origem são replicados.  As gravações ativas do volume de origem não são replicadas.


. Selecione um cluster remoto da lista.
. Escolha um ID de volume remoto.
. Clique em *Iniciar Emparelhamento*.
+
O sistema abre uma aba do navegador web que se conecta à interface de usuário do Element no cluster remoto.  Poderá ser necessário que você faça login no cluster remoto com as credenciais de administrador do cluster.

. Na interface do usuário do Element no cluster remoto, selecione *Concluir Emparelhamento*.
. Confirme os detalhes em *Confirmar Emparelhamento de Volume*.
. Clique em *Concluir Emparelhamento*.
+
Após a confirmação do emparelhamento, os dois clusters iniciam o processo de conexão dos volumes para o emparelhamento.  Durante o processo de emparelhamento, você pode ver mensagens na coluna *Status do Volume* da janela *Pares de Volume*.  O par de volumes é exibido. `PausedMisconfigured` até que o par de volumes de origem e destino seja atribuído.

+
Após concluir o emparelhamento com sucesso, recomenda-se atualizar a tabela de Volumes para remover a opção *Emparelhar* da lista *Ações* do volume emparelhado.  Se você não atualizar a tabela, a opção *Par* permanecerá disponível para seleção.  Se você selecionar a opção *Emparelhar* novamente, uma nova aba será aberta e, como o volume já está emparelhado, o sistema exibirá uma mensagem de erro. `StartVolumePairing Failed: xVolumeAlreadyPaired` Mensagem de erro na janela *Pair Volume* da página Element UI.





== Encontre mais informações

* xref:reference_replication_volume_pairing_messages.adoc[mensagens de emparelhamento de volume]
* xref:reference_replication_volume_pairing_warnings.adoc[Avisos de emparelhamento de volumes]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Atribua uma origem e um destino de replicação aos volumes emparelhados.]

