---
permalink: storage/task_monitor_volume_performance.html 
sidebar: sidebar 
keywords: volume performance, view, view alerts 
summary: Você pode visualizar informações detalhadas de desempenho para todos os volumes no cluster.  Você pode classificar as informações por ID de volume ou por qualquer uma das colunas de desempenho.  Você também pode filtrar as informações por determinados critérios. 
---
= Desempenho do volume de visualização
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar informações detalhadas de desempenho para todos os volumes no cluster.  Você pode classificar as informações por ID de volume ou por qualquer uma das colunas de desempenho.  Você também pode filtrar as informações por determinados critérios.

Você pode alterar a frequência com que o sistema atualiza as informações de desempenho na página clicando na lista *Atualizar a cada* e escolhendo um valor diferente.  O intervalo de atualização padrão é de 10 segundos se o cluster tiver menos de 1000 volumes; caso contrário, o padrão é de 60 segundos.  Se você selecionar a opção "Nunca", a atualização automática da página será desativada.

Você pode reativar a atualização automática clicando em *Ativar atualização automática*.

. Na interface do usuário do Element, selecione *Relatórios* > *Desempenho de Volume*.
. Na lista de volumes, clique no ícone Ações do volume desejado.
. Clique em *Ver detalhes*.
+
Na parte inferior da página, é exibida uma tabela contendo informações gerais sobre o volume.

. Para obter informações mais detalhadas sobre o volume, clique em *Ver mais detalhes*.
+
O sistema exibe informações detalhadas, bem como gráficos de desempenho para o volume.





== Encontre mais informações

xref:reference_monitor_volume_performance_details.adoc[Detalhes de desempenho de volume]
