---
permalink: storage/task-element-replication-create-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, element, source, destination 
summary: Você pode usar o SnapMirror para replicar cópias instantâneas de um volume do Element para um sistema de destino ONTAP .  Em caso de desastre no site do Element, você pode fornecer dados aos clientes a partir do sistema ONTAP e, em seguida, reativar o volume de origem do Element quando o serviço for restaurado. 
---
= Criar uma relação de uma origem Element para um destino ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A relação entre o volume de origem no armazenamento primário e o volume de destino no armazenamento secundário é chamada de _relação de proteção de dados_.  Você pode usar o `snapmirror create` Comando para criar uma relação de proteção de dados de uma origem Element para um destino ONTAP , ou de uma origem ONTAP para um destino Element.

Você pode usar o SnapMirror para replicar cópias instantâneas de um volume do Element para um sistema de destino ONTAP .  Em caso de desastre no site do Element, você pode fornecer dados aos clientes a partir do sistema ONTAP e, em seguida, reativar o volume de origem do Element quando o serviço for restaurado.

.Antes de começar
* O nó Element que contém o volume a ser replicado deve ter sido disponibilizado ao ONTAP.
* O volume Element deve ter sido habilitado para replicação SnapMirror .
* Se você estiver usando o tipo de política "`mirror-vault`", um rótulo SnapMirror deve ter sido configurado para que as cópias de snapshot do Elemento sejam replicadas.
+
[NOTE]
====
Você só pode realizar esta tarefa nolink:concept_snapmirror_labels.html["Interface web do software Element"] ou usando olink:../api/concept_element_api_snapshots_overview.html["Métodos API"] .

====


.Sobre esta tarefa
Você deve especificar o caminho de origem do elemento no formato `<hostip:>/lun/<name>` , onde "`lun`" é a string real "`lun`" e `name` é o nome do volume do Elemento.

Um volume Element é aproximadamente equivalente a um LUN ONTAP .  O SnapMirror cria um LUN com o nome do volume do Element quando uma relação de proteção de dados entre o software Element e o ONTAP é inicializada.  O SnapMirror replica dados para um LUN existente se o LUN atender aos requisitos para replicação do software Element para o ONTAP.

As regras de replicação são as seguintes:

* Um volume ONTAP pode conter dados de apenas um volume Element.
* Não é possível replicar dados de um volume ONTAP para vários volumes Element.


No ONTAP 9.3 e versões anteriores, um volume de destino pode conter até 251 cópias de snapshot.  No ONTAP 9.4 e versões posteriores, um volume de destino pode conter até 1019 cópias de snapshot.

.Etapa
. A partir do cluster de destino, crie uma relação de replicação de uma origem Element para um destino ONTAP :
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
Para obter a sintaxe completa dos comandos, consulte a página do manual.

+
O exemplo a seguir cria um relacionamento de recuperação de desastres (DR) do SnapMirror usando a configuração padrão. `MirrorLatest` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
O exemplo a seguir cria uma relação de replicação unificada usando a configuração padrão. `MirrorAndVault` política:

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
O exemplo a seguir cria uma relação de replicação unificada usando o `Unified7year` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
O exemplo a seguir cria uma relação de replicação unificada usando o recurso personalizado. `my_unified` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.Depois que você terminar
Use o `snapmirror show` comando para verificar se a relação SnapMirror foi criada.  Para obter a sintaxe completa dos comandos, consulte a página do manual.
