---
permalink: storage/task_replication_pair_cluster_using_mvip.html 
sidebar: sidebar 
keywords: pair clusters, mvip, connection 
summary: É possível emparelhar dois clusters para replicação em tempo real usando o MVIP de um cluster para estabelecer uma conexão com o outro cluster.  Para usar este método, é necessário ter acesso de administrador de cluster em ambos os clusters.  O nome de usuário e a senha do administrador do cluster são usados para autenticar o acesso ao cluster antes que os clusters possam ser emparelhados. 
---
= Emparelhe clusters usando MVIP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível emparelhar dois clusters para replicação em tempo real usando o MVIP de um cluster para estabelecer uma conexão com o outro cluster.  Para usar este método, é necessário ter acesso de administrador de cluster em ambos os clusters.  O nome de usuário e a senha do administrador do cluster são usados para autenticar o acesso ao cluster antes que os clusters possam ser emparelhados.

. No cluster local, selecione *Proteção de Dados* > *Pares de Cluster*.
. Clique em *Emparelhar Cluster*.
. Clique em *Iniciar Emparelhamento* e clique em *Sim* para indicar que você tem acesso ao cluster remoto.
. Insira o endereço MVIP do cluster remoto.
. Clique em *Concluir emparelhamento no cluster remoto*.
+
Na janela *Autenticação Necessária*, insira o nome de usuário e a senha do administrador do cluster remoto.

. No cluster remoto, selecione *Proteção de Dados* > *Pares de Cluster*.
. Clique em *Emparelhar Cluster*.
. Clique em *Concluir Emparelhamento*.
. Clique no botão *Concluir Emparelhamento*.




== Encontre mais informações

* xref:task_replication_pair_cluster_using_pairing_key.adoc[Emparelhe clusters usando uma chave de emparelhamento.]
* https://www.youtube.com/watch?v=HbKxPZnNvn4&feature=youtu.be["Emparelhamento de clusters usando MVIP (vídeo)"]

