---
permalink: storage/task_troubleshoot_remove_failed_drives.html 
sidebar: sidebar 
keywords: troubleshoot, failed drives, remove 
summary: O sistema SolidFire coloca uma unidade em estado de falha se o autodiagnóstico da unidade informar ao nó que ela falhou ou se a comunicação com a unidade for interrompida por cinco minutos e meio ou mais.  O sistema exibe uma lista das unidades com falha.  Você deve remover uma unidade com falha da lista de unidades com falha no software NetApp Element . 
---
= Remova as unidades com falha do cluster.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema SolidFire coloca uma unidade em estado de falha se o autodiagnóstico da unidade informar ao nó que ela falhou ou se a comunicação com a unidade for interrompida por cinco minutos e meio ou mais.  O sistema exibe uma lista das unidades com falha.  Você deve remover uma unidade com falha da lista de unidades com falha no software NetApp Element .

Os dispositivos na lista de *Alertas* são exibidos como *blockServiceUnhealthy* quando um nó está offline.  Ao reiniciar o nó, se o nó e seus discos voltarem a ficar online dentro de cinco minutos e meio, os discos serão atualizados automaticamente e continuarão como discos ativos no cluster.

. Na interface do Element, selecione *Cluster* > *Unidades*.
. Clique em *Falhas* para visualizar a lista de unidades com falha.
. Anote o número do slot da unidade com falha.
+
Você precisa dessas informações para localizar a unidade com defeito no chassi.

. Remova as unidades com falha usando um dos seguintes métodos:
+
|===


| Opção | Passos 


 a| 
Para remover unidades individuais
 a| 
.. Clique em *Ações* para a unidade que deseja remover.
.. Clique em *Remover*.




 a| 
Para remover várias unidades
 a| 
.. Selecione todas as unidades que deseja remover e clique em *Ações em massa*.
.. Clique em *Remover*.


|===

