---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: É possível fazer backup de volumes residentes em um cluster para um cluster remoto em clusters de armazenamento que executam o software Element. 
---
= Faça backup de um volume em um cluster de armazenamento SolidFire .
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível fazer backup de volumes residentes em um cluster para um cluster remoto em clusters de armazenamento que executam o software Element.

Certifique-se de que os clusters de origem e destino estejam emparelhados.

Verlink:task_replication_pair_clusters.html["Emparelhe clusters para replicação"] .

Ao fazer backup ou restaurar de um cluster para outro, o sistema gera uma chave que será usada como autenticação entre os clusters.  Essa chave de gravação em massa de volume permite que o cluster de origem se autentique com o cluster de destino, proporcionando um nível de segurança ao gravar no volume de destino.  Como parte do processo de backup ou restauração, você precisa gerar uma chave de gravação em massa do volume de destino antes de iniciar a operação.

. No cluster de destino, *Gerenciamento* > *Volumes*.
. Clique no ícone Ações do volume de destino.
. No menu que aparecer, clique em *Restaurar de*.
. Na caixa de diálogo *Restauração Integrada*, em *Restaurar de*, selecione * SolidFire*.
. Selecione uma opção em *Formato de dados*:
+
** *Nativo*: Um formato comprimido que pode ser lido apenas por sistemas de armazenamento SolidFire .
** *Não comprimido*: Um formato não comprimido compatível com outros sistemas.


. Clique em *Gerar chave*.
. Copie a chave da caixa *Bulk Volume Write Key* para a sua área de transferência.
. No cluster de origem, acesse *Gerenciamento* > *Volumes*.
. Clique no ícone Ações do volume que deseja fazer backup.
. No menu que aparecer, clique em *Fazer backup para*.
. Na caixa de diálogo *Backup Integrado*, em *Fazer backup para*, selecione * SolidFire*.
. Selecione a mesma opção que você selecionou anteriormente no campo *Formato de dados*.
. Insira o endereço IP virtual de gerenciamento do cluster do volume de destino no campo *MVIP do Cluster Remoto*.
. Insira o nome de usuário do cluster remoto no campo *Nome de usuário do cluster remoto*.
. Insira a senha do cluster remoto no campo *Senha do Cluster Remoto*.
. No campo *Chave de gravação em massa do volume*, cole a chave que você gerou anteriormente no cluster de destino.
. Clique em *Iniciar Leitura*.

