---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: Você pode criar grupos de acesso a volumes mapeando iniciadores para uma coleção de volumes para acesso seguro.  Em seguida, você pode conceder acesso aos volumes do grupo com um segredo iniciador CHAP e um segredo de destino da conta. 
---
= Crie um grupo de acesso a volumes.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar grupos de acesso a volumes mapeando iniciadores para uma coleção de volumes para acesso seguro.  Em seguida, você pode conceder acesso aos volumes do grupo com um segredo iniciador CHAP e um segredo de destino da conta.

Se você usar o CHAP baseado em iniciador, poderá adicionar credenciais CHAP para um único iniciador em um grupo de acesso por volume, proporcionando mais segurança.  Isso permite que você aplique essa opção a grupos de acesso por volume que já existem.

.Passos
. Clique em *Gerenciamento* > *Grupos de Acesso*.
. Clique em *Criar Grupo de Acesso*.
. Insira um nome para o grupo de acesso ao volume no campo *Nome*.
. Adicione um iniciador ao grupo de acesso ao volume de uma das seguintes maneiras:
+
[cols="25,75"]
|===
| Opção | Descrição 


 a| 
Adicionando um iniciador Fibre Channel
 a| 
.. Em Adicionar Iniciadores, selecione um iniciador Fibre Channel existente na lista Iniciadores Fibre Channel Não Vinculados.
.. Clique em *Adicionar iniciador FC*.
+

NOTE: Você pode criar um iniciador durante esta etapa clicando no link *Criar Iniciador*, inserindo um nome para o iniciador e clicando em *Criar*.  O sistema adiciona automaticamente o iniciador à lista de Iniciadores após a sua criação.



Segue um exemplo do formato:

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
Adicionando um iniciador iSCSI
 a| 
Em Adicionar Iniciadores, selecione um iniciador existente na lista de Iniciadores.  *Nota:* Você pode criar um iniciador durante esta etapa se clicar no link *Criar Iniciador*, inserir um nome para o iniciador e clicar em *Criar*.  O sistema adiciona automaticamente o iniciador à lista de Iniciadores após a sua criação.

Segue um exemplo do formato:

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: Você pode encontrar o IQN do iniciador para cada volume selecionando *Ver detalhes* no menu Ações do volume na lista *Gerenciamento* > *Volumes* > *Ativos*.

Ao modificar um iniciador, você pode ativar o atributo requiredCHAP como True, o que permite definir o segredo do iniciador de destino.  Para obter detalhes, consulte as informações da API sobre o método de API ModifyInitiator.

link:../api/concept_element_api_about_the_api.html["Gerencie o armazenamento com a API Element."]

|===
. *Opcional:* Adicione mais iniciadores conforme necessário.
. Em Adicionar Volumes, selecione um volume da lista *Volumes*.
+
O volume aparece na lista *Volumes Anexados*.

. *Opcional:* Adicione mais volumes conforme necessário.
. Clique em *Criar Grupo de Acesso*.




== Encontre mais informações

xref:task_data_manage_vol_access_group_add_volumes.adoc[Adicionar volumes a um grupo de acesso]
