---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Você pode alterar a senha padrão do administrador da Interface de Gerenciamento de Plataforma Inteligente (IPMI) assim que tiver acesso remoto ao nó via IPMI.  Você pode querer fazer isso se houver alguma atualização de instalação.' 
---
= Alterar a senha IPMI padrão para nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha padrão do administrador da Interface de Gerenciamento de Plataforma Inteligente (IPMI) assim que tiver acesso remoto ao nó via IPMI.  Você pode querer fazer isso se houver alguma atualização de instalação.

Para obter detalhes sobre como configurar o acesso IPM para nós, consultelink:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configure o IPMI para cada nó."^] .

Você pode alterar a senha do IPM para estes nós:

* Nós H410S
* Nós H610S




== Alterar a senha IPMI padrão para nós H410S

Você deve alterar a senha padrão da conta de administrador IPMI em cada nó de armazenamento assim que configurar a porta de rede IPMI.

.O que você vai precisar
Você deve ter configurado o endereço IP do IPMI para cada nó de armazenamento.

.Passos
. Abra um navegador web em um computador que possa acessar a rede IPMI e navegue até o endereço IP do nó IPMI.
. Digite o nome de usuário `ADMIN` e senha `ADMIN` na tela de login.
. Após efetuar o login, clique na aba *Configuração*.
. Clique em *Usuários*.
. Selecione o `ADMIN` usuário e clique em *Modificar Usuário*.
. Selecione a caixa de seleção *Alterar senha*.
. Insira uma nova senha nos campos *Senha* e *Confirmar Senha*.
. Clique em *Modificar* e, em seguida, clique em *OK*.
. Repita este procedimento para quaisquer outros nós H410S com senhas IPMI padrão.




== Alterar a senha IPMI padrão para nós H610S

Você deve alterar a senha padrão da conta de administrador IPMI em cada nó de armazenamento assim que configurar a porta de rede IPMI.

.O que você vai precisar
Você deve ter configurado o endereço IP do IPMI para cada nó de armazenamento.

.Passos
. Abra um navegador web em um computador que possa acessar a rede IPMI e navegue até o endereço IP do nó IPMI.
. Digite o nome de usuário `root` e senha `calvin` na tela de login.
. Após efetuar o login, clique no ícone de navegação do menu no canto superior esquerdo da página para abrir a barra lateral.
. Clique em *Configurações*.
. Clique em *Gerenciamento de usuários*.
. Selecione o usuário *Administrador* na lista.
. Marque a caixa de seleção *Alterar senha*.
. Digite uma nova senha forte nos campos *Senha* e *Confirmar Senha*.
. Clique em *Salvar* na parte inferior da página.
. Repita este procedimento para quaisquer outros nós H610S com senhas IPMI padrão.




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

