---
permalink: storage/task_data_protection_clone_multiple_volumes_from_a_group_snapshot.html 
sidebar: sidebar 
keywords: multiple volumes, group snapshot, clone, create, data protection 
summary: Você pode clonar um grupo de volumes a partir de um instantâneo do grupo em um determinado ponto no tempo.  Esta operação requer que já exista um snapshot de grupo dos volumes, pois o snapshot de grupo é usado como base para criar os volumes.  Depois de criar os volumes, você pode usá-los como qualquer outro volume do sistema. 
---
= Clonando vários volumes a partir de um snapshot de grupo.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode clonar um grupo de volumes a partir de um instantâneo do grupo em um determinado ponto no tempo.  Esta operação requer que já exista um snapshot de grupo dos volumes, pois o snapshot de grupo é usado como base para criar os volumes.  Depois de criar os volumes, você pode usá-los como qualquer outro volume do sistema.

O tamanho do volume e a carga atual do cluster afetam o tempo necessário para concluir uma operação de clonagem.

. Clique em *Proteção de Dados* > *Instantâneos de Grupo*.
. Clique no ícone Ações do instantâneo de grupo que você deseja usar para os clones de volume.
. No menu que aparecer, selecione *Clonar volumes a partir do instantâneo do grupo*.
. Insira um *Novo Prefixo de Nome de Volume* na caixa de diálogo *Clonar Volumes a partir de Instantâneo de Grupo*.
+
O prefixo é aplicado a todos os volumes criados a partir do snapshot do grupo.

. *Opcional:* Selecione uma conta diferente à qual o clone pertencerá.
+
Se você não selecionar uma conta, o sistema atribuirá os novos volumes à conta de volumes atual.

. *Opcional:* Selecione um método de acesso diferente para os volumes no clone.
+
Se você não selecionar um método de acesso, o sistema usará o acesso ao volume atual.

. Clique em *Iniciar Clonagem*.

