---
permalink: storage/task_replication_pair_volumes_using_volume_id_or_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, volume id, replication 
summary: O processo de emparelhamento envolve a combinação de dois volumes usando um ID de volume ou uma chave de emparelhamento. 
---
= Emparelhe volumes usando um ID de volume ou uma chave de emparelhamento.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O processo de emparelhamento envolve a combinação de dois volumes usando um ID de volume ou uma chave de emparelhamento.

. Emparelhe os volumes selecionando um dos seguintes métodos:
+
** Utilizando um ID de volume: Utilize este método se você tiver acesso de administrador de cluster a ambos os clusters nos quais os volumes serão emparelhados. Este método utiliza o ID do volume no cluster remoto para iniciar uma conexão.
** Utilizando uma chave de emparelhamento: Utilize este método se você tiver acesso de administrador de cluster apenas ao cluster de origem.  Este método gera uma chave de emparelhamento que pode ser usada no cluster remoto para concluir o emparelhamento de volumes.
+

NOTE: A chave de emparelhamento de volume contém uma versão criptografada das informações do volume e pode conter informações confidenciais.  Compartilhe esta chave apenas de forma segura.







== Encontre mais informações

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[Emparelhe volumes usando um ID de volume]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[Emparelhe volumes usando uma chave de emparelhamento.]

