---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: Você pode usar a interface de usuário específica de cada nó de armazenamento para criar ou excluir pacotes de suporte, redefinir as configurações das unidades e reiniciar os serviços de rede ou de cluster. 
---
= Execute utilitários do sistema usando a interface de usuário por nó.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a interface de usuário específica de cada nó de armazenamento para criar ou excluir pacotes de suporte, redefinir as configurações das unidades e reiniciar os serviços de rede ou de cluster.

Você fez login na interface de usuário específica do nó de armazenamento.

. Clique em *Utilitários do Sistema*.
. Clique no botão do utilitário de sistema que deseja executar.
+
** *Controle de Potência*
+
Reinicia, desliga e liga/desliga o nó.

+

IMPORTANT: Esta operação causa perda temporária de conectividade de rede.

+
Especifique os seguintes parâmetros:

+
*** Ação: As opções incluem Reiniciar e Parar (desligar).
*** Atraso de ativação: Qualquer tempo adicional antes que o nó volte a ficar online.


** *Coletar registros de nós*
+
Cria um pacote de suporte no diretório /tmp/bundles do nó.

+
Especifique os seguintes parâmetros:

+
*** Nome do pacote: Nome exclusivo para cada pacote de suporte criado.  Caso nenhum nome seja fornecido, "supportbundle" e o nome do nó serão usados como nome do arquivo.
*** Argumentos extras: Este parâmetro é passado para o script sf_make_support_bundle.  Este parâmetro deve ser usado somente a pedido do Suporte da NetApp .
*** Tempo limite (em segundos): Especifique o número de segundos a aguardar por cada resposta de ping individual.


** *Excluir registros do nó*
+
Exclui todos os pacotes de suporte atuais no nó que foram criados usando *Criar Pacote de Suporte de Cluster* ou o método de API CreateSupportBundle.

** *Reiniciar unidades*
+
Inicializa as unidades e remove todos os dados atualmente presentes na unidade.  Você pode reutilizar a unidade em um nó existente ou em um nó atualizado.

+
Especifique o seguinte parâmetro:

+
*** Unidades: Lista de nomes de dispositivos (não IDs de unidade) a serem redefinidos.


** *Redefinir configuração de rede*
+
Ajuda a resolver problemas de configuração de rede para um nó individual e redefine a configuração de rede desse nó para as configurações padrão de fábrica.

** *Reiniciar nó*
+
Restaura as configurações de fábrica de um nó.  Todos os dados são removidos, mas as configurações de rede do nó são preservadas durante essa operação.  Os nós só podem ser reinicializados se não estiverem atribuídos a um cluster e estiverem no estado Disponível.

+

IMPORTANT: Ao usar esta opção, todos os dados, pacotes (atualizações de software), configurações e arquivos de log são excluídos do nó.

** *Reiniciar a rede*
+
Reinicia todos os serviços de rede em um nó.

+

IMPORTANT: Essa operação pode causar perda temporária de conectividade de rede.

** *Reiniciar serviços*
+
Reinicia os serviços de software Element em um nó.

+

IMPORTANT: Esta operação pode causar interrupção temporária do serviço do nó.  Você deve realizar esta operação somente sob a orientação do Suporte da NetApp .

+
Especifique os seguintes parâmetros:

+
*** Serviço: Nome do serviço a ser reiniciado.
*** Ação: Ação a ser executada no serviço.  As opções incluem iniciar, parar e reiniciar.





