---
permalink: storage/task_snapmirror_perform_failback_when_source_volume_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source volume, snapmirror 
summary: Você pode ressincronizar o volume de origem original e reverter o processo usando a interface do usuário do NetApp Element .  Este procedimento aplica-se a cenários em que o volume de origem original ainda existe. 
---
= Execute um failback quando o volume de origem ainda existir.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ressincronizar o volume de origem original e reverter o processo usando a interface do usuário do NetApp Element .  Este procedimento aplica-se a cenários em que o volume de origem original ainda existe.

. Na interface do usuário do Element, localize o relacionamento que você quebrou para realizar o failover.
. Clique no ícone Ações e clique em *Reverter Sincronização*.
. Confirme a ação.
+

NOTE: A operação de ressincronização reversa cria um novo relacionamento no qual os papéis dos volumes de origem e destino originais são invertidos (isso resulta em dois relacionamentos, pois o relacionamento original persiste).  Quaisquer novos dados do volume de destino original são transferidos para o volume de origem original como parte da operação de ressincronização reversa.  Você pode continuar acessando e gravando dados no volume ativo no lado de destino, mas precisará desconectar todos os hosts do volume de origem e executar uma atualização do SnapMirror antes de redirecionar de volta para o volume primário original.

. Clique no ícone Ações da relação inversa que você acabou de criar e clique em *Atualizar*.
+
Agora que você concluiu a resincronização reversa e garantiu que não há sessões ativas conectadas ao volume no destino e que os dados mais recentes estão no volume primário original, você pode executar as seguintes etapas para concluir o failback e reativar o volume primário original:

. Clique no ícone Ações da relação inversa e clique em *Quebrar*.
. Clique no ícone Ações do relacionamento original e clique em *Ressincronizar*.
+

NOTE: O volume primário original agora pode ser montado para retomar as cargas de trabalho de produção no volume primário original.  A replicação original do SnapMirror é retomada com base na política e no agendamento configurados para o relacionamento.

. Após confirmar que o status original do relacionamento é "`snapmirrored`", clique no ícone Ações do relacionamento inverso e clique em *Excluir*.




== Encontre mais informações

xref:concept_snapmirror_failback_scenarios.adoc[Cenários de failback do SnapMirror]
