---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: Você precisa configurar os nós individualmente antes de adicioná-los a um cluster.  Após instalar e conectar um nó em uma unidade de rack e ligá-lo, você pode configurar as definições de rede do nó usando a interface de usuário específica de cada nó ou a interface de usuário do terminal do nó. 
---
= Configure um nó de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa configurar os nós individualmente antes de adicioná-los a um cluster.  Após instalar e conectar os cabos de um nó em uma unidade de rack e ligá-lo, você pode configurar as definições de rede do nó usando a interface de usuário específica de cada nó ou a interface de usuário do terminal do nó (TUI).  Certifique-se de ter as informações de configuração de rede necessárias para o nó antes de prosseguir.

Existem duas opções para configurar nós de armazenamento:

* <<Configure um nó de armazenamento usando a interface de usuário por nó.,Interface do usuário por nó>>Utilize a interface de usuário por nó. (`https://<node_management_IP>:442`) para configurar as definições de rede do nó.
* <<Configure um nó de armazenamento usando a interface de usuário de texto (TUI).,TUI>>Utilize a interface de usuário do terminal do nó (TUI) para configurar o nó.


Não é possível adicionar um nó com endereços IP atribuídos por DHCP a um cluster.  Você pode usar o endereço IP do DHCP para configurar inicialmente o nó na interface de usuário (UI) específica do nó, na interface de usuário em tempo real (TUI) ou na API.  Durante essa configuração inicial, você pode adicionar informações de endereço IP estático para que possa adicionar o nó a um cluster.

Após a configuração inicial, você poderá acessar o nó usando o endereço IP de gerenciamento do nó.  Em seguida, você pode alterar as configurações do nó, adicioná-lo a um cluster ou usar o nó para criar um cluster.  Você também pode configurar um novo nó usando os métodos da API do software Element.


NOTE: A partir da versão 11.0 do Element, os nós podem ser configurados com endereços IPv4, IPv6 ou ambos para sua rede de gerenciamento.  Isso se aplica tanto a nós de armazenamento quanto a nós de gerenciamento, exceto para o nó de gerenciamento 11.3 e versões posteriores, que não suportam IPv6.  Ao criar um cluster, apenas um único endereço IPv4 ou IPv6 pode ser usado para o MVIP e o tipo de endereço correspondente deve ser configurado em todos os nós.



== Configure um nó de armazenamento usando a interface de usuário por nó.

Você pode configurar os nós usando a interface de usuário específica para cada nó.

.Sobre esta tarefa
* Você pode configurar o nó para ter um endereço IPv4 ou IPv6.
* Você precisa do endereço DHCP exibido na interface de usuário (TUI) para acessar um nó.  Não é possível usar endereços DHCP para adicionar um nó a um cluster.
+

IMPORTANT: Você deve configurar as interfaces de gerenciamento (Bond1G) e de armazenamento (Bond10G) para sub-redes separadas.  As interfaces Bond1G e Bond10G configuradas para a mesma sub-rede causam problemas de roteamento quando o tráfego de armazenamento é enviado pela interface Bond1G.  Caso seja necessário usar a mesma sub-rede para tráfego de gerenciamento e armazenamento, configure manualmente o tráfego de gerenciamento para usar a interface Bond10G.  Você pode fazer isso para cada nó usando a página *Configurações do Cluster* da interface de usuário de cada nó.



.Passos
. Em uma janela do navegador, insira o endereço IP DHCP de um nó.
+
Você precisa adicionar a extensão. `:442` para acessar o nó; por exemplo, `https://172.25.103.6:442`.

+
A aba *Configurações de Rede* abre com a seção *Bond1G*.

. Acesse as configurações de gerenciamento da rede 1G.
. Clique em *Aplicar alterações*.
. Clique em *Bond10G* para exibir as configurações da rede de armazenamento de 10G.
. Insira as configurações de rede de armazenamento de 10G.
. Clique em *Aplicar alterações*.
. Clique em *Configurações do cluster*.
. Digite o nome do host para a rede 10G.
. Digite o nome do cluster.
+

IMPORTANT: Esse nome deve ser adicionado à configuração de todos os nós antes que um cluster possa ser criado.  Todos os nós em um cluster devem ter nomes de cluster idênticos.  Os nomes dos clusters diferenciam maiúsculas de minúsculas.

. Clique em *Aplicar alterações*.




== Configure um nó de armazenamento usando a interface de usuário de texto (TUI).

Você pode usar a interface de usuário do terminal (TUI) para realizar a configuração inicial de novos nós.

Você deve configurar as interfaces Bond1G (Gerenciamento) e Bond10G (Armazenamento) para sub-redes separadas.  As interfaces Bond1G e Bond10G configuradas para a mesma sub-rede causam problemas de roteamento quando o tráfego de armazenamento é enviado pela interface Bond1G.  Caso seja necessário usar a mesma sub-rede para tráfego de gerenciamento e armazenamento, configure manualmente o tráfego de gerenciamento para usar a interface Bond10G.  Você pode fazer isso para cada nó usando a página *Cluster* > *Nós* da interface do usuário do Elemento.

.Passos
. Conecte um teclado e um monitor ao nó e, em seguida, ligue o nó.
+
O menu principal da interface de usuário de texto (TUI) do NetApp Storage aparece no terminal tty1.

+

NOTE: Se o nó não conseguir alcançar o servidor de configuração, a interface de usuário exibirá uma mensagem de erro.  Verifique a conexão com o servidor de configuração ou a conexão de rede para resolver o erro.

. Selecione *Rede* > *Configuração de Rede*.
+

TIP: Para navegar pelo menu, pressione as teclas de seta para cima ou para baixo.  Para ir para outro botão ou para os campos a partir dos botões, pressione *Tab*.  Para navegar entre os campos, use as teclas de seta para cima ou para baixo.

. Selecione *Bond1G (Gerenciamento)* ou *Bond10G (Armazenamento)* para configurar as definições de rede de 1G e 10G para o nó.
. Para os campos Modo de vínculo e Status, pressione *Tab* para selecionar o botão Ajuda e identificar as opções disponíveis.
+
Todos os nós em um cluster devem ter nomes de cluster idênticos.  Os nomes dos clusters diferenciam maiúsculas de minúsculas.  Se um servidor DHCP estiver em execução na rede com endereços IP disponíveis, o endereço 1GbE aparecerá no campo Endereço.

. Pressione a tecla *Tab* para selecionar o botão *OK* e salvar as alterações.
+
O nó é colocado em estado pendente e pode ser adicionado a um cluster existente ou a um novo cluster.





== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

