---
permalink: setup/task_setup_determine_which_solidfire_components_to_install.html 
sidebar: sidebar 
keywords: setup, element, solidfire active iq 
summary: 'Você pode querer verificar quais componentes do SolidFire , como o nó de gerenciamento, o Active IQ e o NetApp Monitoring Agent (NMA), devem ser instalados, dependendo das opções de configuração e implantação.' 
---
= Determine quais componentes do SolidFire instalar.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode querer verificar quais componentes do SolidFire , como o nó de gerenciamento, o Active IQ e o NetApp Monitoring Agent (NMA), devem ser instalados, dependendo das opções de configuração e implantação.

A tabela a seguir lista os componentes adicionais e indica se você deve instalá-los.

[cols="3*"]
|===
| Componente | Cluster de armazenamento SolidFire independente | Cluster NetApp HCI 


 a| 
Nó de gerenciamento
 a| 
Recomendado
 a| 
Instalado por padrão, obrigatório



 a| 
Active IQ
 a| 
Recomendado*
 a| 
Recomendado*



 a| 
Agente de monitoramento NetApp
 a| 
Não suportado
 a| 
Recomendado

|===
* O Active IQ é necessário para clusters de armazenamento SolidFire com licença de capacidade.

.Passos
. Determine quais componentes devem ser instalados.
. Conclua a instalação de acordo com olink:../mnode/task_mnode_install.html["instalar o nó de gerenciamento"] procedimento.
+

NOTE: Para configurar o Active IQ, use o `--telemetry_active` parâmetro no script de configuração para habilitar a coleta de dados para análises pelo Active IQ.

. Para obter informações sobre o Agente de Monitoramento da NetApp , consulte este link.link:../mnode/task_mnode_enable_activeIQ.html["procedimento"] .




== Para maiores informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

