---
permalink: setup/task_setup_create_a_volume_access_group_for_fibre_channel_clients.html 
sidebar: sidebar 
keywords:  
summary: 'Os grupos de acesso a volumes permitem a comunicação entre clientes Fibre Channel e volumes em um sistema de armazenamento SolidFire .  O mapeamento de iniciadores de clientes Fibre Channel (WWPN) para os volumes em um grupo de acesso a volumes permite a entrada/saída de dados segura entre uma rede Fibre Channel e um volume SolidFire .' 
---
= Crie um grupo de acesso por volume para clientes Fibre Channel.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os grupos de acesso a volumes permitem a comunicação entre clientes Fibre Channel e volumes em um sistema de armazenamento SolidFire .  O mapeamento de iniciadores de cliente Fibre Channel (WWPN) para os volumes em um grupo de acesso a volumes permite a entrada/saída de dados segura entre uma rede Fibre Channel e um volume SolidFire .

Você também pode adicionar iniciadores iSCSI a um grupo de acesso a volumes; isso concede aos iniciadores acesso aos mesmos volumes no grupo de acesso a volumes.

.Passos
. Clique em *Gerenciamento* > *Grupos de Acesso*.
. Clique em *Criar Grupo de Acesso*.
. Insira um nome para o grupo de acesso ao volume no campo *Nome*.
. Selecione e adicione os iniciadores Fibre Channel da lista *Iniciadores Fibre Channel não vinculados*.
+

NOTE: Você pode adicionar ou excluir iniciadores posteriormente.

. *Opcional:* Selecione e adicione um iniciador iSCSI da lista *Iniciadores*.
. Para associar volumes ao grupo de acesso, execute os seguintes passos:
+
.. Selecione um volume da lista *Volumes*.
.. Clique em *Anexar Volume*.


. Clique em *Criar Grupo de Acesso*.




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

