---
permalink: setup/task_setup_fc_add_fibre_channel_nodes_to_a_cluster.html 
sidebar: sidebar 
keywords:  
summary: Você pode adicionar nós Fibre Channel a um cluster quando for necessário mais armazenamento ou durante a criação do cluster.  Os nós Fibre Channel requerem configuração inicial quando são ligados pela primeira vez.  Após a configuração do nó, ele aparece na lista de nós pendentes e você pode adicioná-lo a um cluster. 
---
= Adicionar nós Fibre Channel a um cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar nós Fibre Channel a um cluster quando for necessário mais armazenamento ou durante a criação do cluster.  Os nós Fibre Channel requerem configuração inicial quando são ligados pela primeira vez.  Após a configuração do nó, ele aparece na lista de nós pendentes e você pode adicioná-lo a um cluster.

A versão do software em cada nó Fibre Channel de um cluster deve ser compatível.  Ao adicionar um nó Fibre Channel a um cluster, o cluster instala a versão do Element correspondente no novo nó, conforme necessário.

.Passos
. Selecione *Cluster* > *Nós*.
. Clique em *Pendente* para visualizar a lista de nós pendentes.
. Faça um dos seguintes:
+
** Para adicionar nós individuais, clique no ícone *Ações* do nó que deseja adicionar.
** Para adicionar vários nós, selecione a caixa de seleção dos nós que deseja adicionar e, em seguida, *Ações em massa*.
+

NOTE: Se o nó que você está adicionando tiver uma versão do Element diferente da versão em execução no cluster, o cluster atualizará o nó de forma assíncrona para a versão do Element em execução no nó mestre do cluster.  Após a atualização do nó, ele se adiciona automaticamente ao cluster.  Durante esse processo assíncrono, o nó ficará em um estado pendingActive.



. Clique em *Adicionar*.
+
O nó aparece na lista de nós ativos.





== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

