---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: Você pode criar um novo cluster depois de configurar os nós individuais do Fibre Channel.  Ao criar um cluster, uma conta de usuário administrador do cluster é criada automaticamente para você.  O administrador do cluster tem permissão para gerenciar todos os atributos do cluster e pode criar outras contas de administrador do cluster. 
---
= Crie um novo cluster com nós Fibre Channel.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um novo cluster depois de configurar os nós individuais do Fibre Channel.  Ao criar um cluster, uma conta de usuário administrador do cluster é criada automaticamente para você.  O administrador do cluster tem permissão para gerenciar todos os atributos do cluster e pode criar outras contas de administrador do cluster.

Durante a configuração de um novo nó, endereços IP de gerenciamento (MIP) de 1G ou 10G são atribuídos a cada nó.  Você deve usar um dos endereços IP dos nós criados durante a configuração para abrir a página Criar um novo cluster.  O endereço IP que você utiliza depende da rede escolhida para o gerenciamento do cluster.

.O que você vai precisar
Você configurou os nós individuais do Fibre Channel.

.Passos
. Em uma janela do navegador, insira o endereço MIP de um nó.
. Em Criar um novo cluster, insira as seguintes informações:
+
** VIP de gerenciamento: IP virtual roteável na rede 1GbE ou 10GbE para tarefas de gerenciamento de rede.
** VIP iSCSI (armazenamento): IP virtual na rede 10GbE para armazenamento e descoberta iSCSI.
+

NOTE: Não é possível alterar o SVIP depois de criar o cluster.

** Nome de usuário: O nome de usuário principal do administrador do cluster para acesso autenticado ao cluster.  Você deve salvar o nome de usuário para referência futura.
+

NOTE: Você pode usar letras maiúsculas e minúsculas, caracteres especiais e números para o nome de usuário.

** Senha: Senha para acesso autenticado ao cluster.  Você deve salvar o nome de usuário para referência futura.  A proteção de dados bidirecional está ativada por padrão.  Você não pode alterar essa configuração.


. Leia o Contrato de Licença do Usuário Final e clique em *Concordo*.
. *Opcional*: Na lista de nós, certifique-se de que as caixas de seleção dos nós que não devem ser incluídos no cluster não estejam marcadas.
. Clique em *Criar Cluster*.
+
O sistema pode levar vários minutos para criar o cluster, dependendo do número de nós no cluster.  Em uma rede configurada corretamente, um pequeno cluster de cinco nós deve levar menos de um minuto.  Após a criação do cluster, a janela "Criar um novo cluster" redireciona para o endereço URL MVIP do cluster e exibe a interface web.





== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element para vCenter Server"^]

