---
permalink: api/concept_element_api_virtual_network_naming_conventions.html 
sidebar: sidebar 
keywords: storage,system,naming,convention,virtual,network 
summary: Os sistemas de armazenamento NetApp Element utilizam números que aumentam monotonicamente como identificadores únicos para todos os objetos no sistema. 
---
= Convenções de nomenclatura de redes virtuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas de armazenamento NetApp Element utilizam números que aumentam monotonicamente como identificadores únicos para todos os objetos no sistema.

Ao criar um novo volume, o novo ID do volume é um incremento de exatamente 1.  Essa convenção também se aplica a redes virtuais em clusters de armazenamento que executam o software Element.  A primeira rede virtual que você cria em um cluster Element tem um VirtualNetworkID de 1.  Este ID não é a mesma coisa que um número de tag VLAN.

Você pode usar VirtualNetworkID e VirtualNetworkTag (tag VLAN) de forma intercambiável onde indicado nos métodos da API.



== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

