---
permalink: api/reference_element_api_getclusterstructure.html 
sidebar: sidebar 
keywords: storage,cluster,structure,config,configuration,info,get,getting,getclusterstructure 
summary: Você pode usar o método GetClusterStructure para fazer backup das informações de configuração do cluster de armazenamento atual.  Se a configuração do cluster de armazenamento for alterada enquanto este método estiver em execução, o conteúdo do backup da configuração será imprevisível.  Você pode salvar esses dados em um arquivo de texto e restaurá-los em outros clusters, ou no mesmo cluster em caso de desastre. 
---
= ObterEstruturaDoCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetClusterStructure` Método para fazer backup das informações de configuração do cluster de armazenamento atual.  Se a configuração do cluster de armazenamento for alterada enquanto este método estiver em execução, o conteúdo do backup da configuração será imprevisível.  Você pode salvar esses dados em um arquivo de texto e restaurá-los em outros clusters, ou no mesmo cluster em caso de desastre.



== Parâmetro

Este método não possui parâmetro de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
resultado
 a| 
Um objeto JSON contendo as informações de configuração atuais do cluster de armazenamento.
 a| 
xref:reference_element_api_clusterstructure.adoc[estrutura de cluster]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetClusterStructure",
  "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
	"id": 1,
	"result" : <clusterStructure object containing configuration information>
	}
----


== Novidade desde a versão

10,3
