---
permalink: api/reference_element_api_snapmirrorendpoint.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorEndpoint 
summary: O objeto snapMirrorEndpoint contém informações sobre os sistemas de armazenamento SnapMirror remotos que se comunicam com o cluster de armazenamento Element.  Você pode recuperar essas informações com o método de API ListSnapMirrorEndpoints. 
---
= snapMirrorEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto snapMirrorEndpoint contém informações sobre os sistemas de armazenamento SnapMirror remotos que se comunicam com o cluster de armazenamento Element.  Você pode recuperar essas informações com o método de API ListSnapMirrorEndpoints.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
snapMirrorEndpointID
 a| 
O identificador único do objeto no cluster local.
 a| 
inteiro



 a| 
gerenciamento de IP
 a| 
O endereço IP de gerenciamento do cluster do ponto de extremidade.
 a| 
corda



 a| 
nome do cluster
 a| 
O nome do cluster ONTAP .  Esse valor é preenchido automaticamente com o valor de "`clusterName`" do objeto snapMirrorClusterIdentity.
 a| 
corda



 a| 
nome de usuário
 a| 
Nome de usuário para gerenciamento do sistema ONTAP .
 a| 
corda



 a| 
endereços IP
 a| 
Lista dos endereços IP de armazenamento entre clusters para todos os nós do cluster.  Você pode obter esses endereços IP com o método ListSnapMirrorNetworkInterfaces.
 a| 
matriz de strings



 a| 
está conectado
 a| 
O estado de conectividade do link de controle com o cluster ONTAP .
 a| 
booleano

|===