---
permalink: api/reference_element_api_deleteclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,delete,deleting,DeleteClusterInterfacePreference 
summary: O método DeleteClusterInterfacePreference permite que sistemas integrados a clusters de armazenamento que executam o software Element excluam uma preferência de interface de cluster existente.  Este método destina-se a uso interno. 
---
= Preferência de Interface de Cluster Excluir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `DeleteClusterInterfacePreference` Este método permite que sistemas integrados com clusters de armazenamento que executam o software Element excluam uma preferência de interface de cluster existente.  Este método destina-se a uso interno.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
O nome da preferência de interface do cluster a ser excluída.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valor de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "DeleteClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id": 1,
    "result": {}
}
----


== Novidade desde a versão

11,0
