---
permalink: api/reference_element_api_listnetworkinterfacestats.html 
sidebar: sidebar 
keywords: network,interface,stats,statistics,interfaces,list,listing,listnetworkinterfacestats 
summary: 'Você pode usar o método ListNetworkInterfaceStats para listar as estatísticas de cada interface de rede em um nó.  Este método de API destina-se ao uso em nós individuais; a autenticação por ID de usuário e senha é necessária para acessar nós individuais.  No entanto, você pode usar esse método no cluster se o parâmetro `force` receber o valor `true` na chamada do método.  Quando o parâmetro é usado no cluster, todas as interfaces são listadas.' 
---
= ListNetworkInterfaceStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListNetworkInterfaceStats` Método para listar estatísticas como o número de pacotes descartados e vários tipos de erros para cada interface de rede em um nó.  Este método de API destina-se ao uso em nós individuais; a autenticação por ID de usuário e senha é necessária para acessar nós individuais.  No entanto, você pode usar esse método no cluster se o parâmetro `force` receber o valor `true` na chamada do método.  Quando o parâmetro é usado no cluster, as estatísticas de rede para todas as interfaces são listadas.



== Parâmetro

Este método não possui parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


| Estatísticas da interface de rede | Uma lista de informações estatísticas da rede, como o número de pacotes descartados e vários tipos de erros de rede, para cada interface de rede de um nó de armazenamento. | xref:reference_element_api_networkinterfacestats.adoc[Estatísticas da interface de rede]variedade 
|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method": "ListNetworkInterfaceStats",
"params": {},
"id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "networkInterfaceStats": [
        {
            "rxErrors": 1,
            "rxPackets": 1,
            "txErrors": 1,
            "rxDropped": 1,
            "txCarrierErrors": 1,
            "rxOverErrors": 1,
            "rxMissedErrors": 1,
            "txPackets": 1,
            "name": "if_name",
            "rxLengthErrors": 1,
            "collisions": 1,
            "rxFifoErrors": 1,
            "txBytes": 1,
            "rxBytes": 1,
            "rxFrameErrors": 1,
            "rxCrcErrors": 1,
            "txFifoErrors": 1
        }
    ]
}
----


== Novidade desde a versão

12,3
