---
permalink: api/reference_element_api_modifyvolumepair.html 
sidebar: sidebar 
keywords: volume,pair,pairs,modify,modifying,edit,editing,changing,change,modifyvolumepair,paired 
summary: 'Você pode usar o método ModifyVolumePair para pausar ou reiniciar a replicação entre um par de volumes.  Este método é definido no volume de origem (o volume com acesso de leitura/gravação).' 
---
= Modificar par de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyVolumePair` Método para pausar ou reiniciar a replicação entre um par de volumes.  Este método é definido no volume de origem (o volume com acesso de leitura/gravação).



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do volume
 a| 
Número de identificação do volume a ser modificado.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
pausadoManual
 a| 
A replicação remota pode ser pausada ou reiniciada no volume de origem (leitura/gravação). Valores possíveis:

* verdadeiro: Pausar a replicação do volume.
* falso: Reiniciar a replicação de volume.


Se nenhum valor for especificado, nenhuma alteração na replicação será realizada.
 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
modo
 a| 
Modo de replicação de volume. Valores possíveis:

* Assíncrono: as operações de escrita são confirmadas quando concluídas localmente.  O cluster não espera que as gravações sejam replicadas para o cluster de destino.
* Sincronização: A origem confirma a gravação quando os dados são armazenados localmente e no cluster remoto.
* SnapshotsOnly: Somente os snapshots criados no cluster de origem são replicados.  As gravações ativas do volume de origem não são replicadas.

 a| 
corda
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método não possui valor de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ModifyVolumePair",
  "params": {
    "pausedManual": false,
    "volumeID": 5,
    "mode": "sync"
   },
  "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id" : 1,
   "result" : {}
}
----


== Novidade desde a versão

9,6
