---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: Você pode usar o método SetSnmpInfo para configurar o SNMP versão 2 e versão 3 nos nós do cluster.  Os valores definidos por meio dessa interface se aplicam a todos os nós do cluster, e os valores passados substituem todos os valores definidos em qualquer chamada anterior à função SetSnmpInfo. 
---
= SetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetSnmpInfo` Método para configurar o SNMP versão 2 e versão 3 em nós de cluster.  Os valores definidos por meio dessa interface se aplicam a todos os nós do cluster, e os valores passados substituem todos os valores definidos em qualquer chamada anterior. `SetSnmpInfo` .



== Parâmetros


NOTE: O método SetSnmpInfo está obsoleto nas versões 6.0 e posteriores do Element.  Use oxref:reference_element_api_enablesnmp.adoc[Habilitar SNMP] exref:reference_element_api_setsnmpacl.adoc[Definir ACL SNMP] métodos em vez disso.

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
redes
 a| 
Lista de redes e o tipo de acesso que elas têm aos servidores SNMP em execução nos nós do cluster.  Consulte o SNMPxref:reference_element_api_network_snmp.adoc[rede] objeto para valores possíveis.  Este parâmetro é necessário apenas para SNMP v2.
 a| 
xref:reference_element_api_network_snmp.adoc[rede]variedade
 a| 
Nenhum
 a| 
Não



 a| 
habilitado
 a| 
Se definido como verdadeiro, o SNMP é ativado em cada nó do cluster.
 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
snmpV3Enabled
 a| 
Se definido como verdadeiro, o SNMP v3 é habilitado em cada nó do cluster.
 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
usmUsers
 a| 
Se o SNMP v3 estiver ativado, esse valor deverá ser passado no lugar do parâmetro de redes.  Este parâmetro é necessário apenas para SNMP v3.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação com SNMP v3 ativado

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== Exemplo de solicitação com SNMP v2 ativado

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== Novidade desde a versão

9,6
