---
permalink: api/reference_element_api_listprotocolendpoints.html 
sidebar: sidebar 
keywords: protocol,endpoints,endpoint,list,listing,listprotocolendpoints 
summary: Você pode usar o método ListProtocolEndpoints para recuperar informações sobre todos os endpoints de protocolo no cluster.  Os endpoints do protocolo controlam o acesso aos seus respectivos contêineres de armazenamento de volume virtual. 
---
= ListProtocolEndpoints
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListProtocolEndpoints` Método para recuperar informações sobre todos os endpoints de protocolo no cluster.  Os endpoints do protocolo controlam o acesso aos seus respectivos contêineres de armazenamento de volume virtual.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IDs de ponto final do protocolo
 a| 
Uma lista de IDs de endpoints de protocolo para os quais se desejam obter informações.  Se você omitir esse parâmetro, o método retornará informações sobre todos os pontos de extremidade do protocolo.
 a| 
matriz UUID de protocolEndpointID
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
endpoints do protocolo
 a| 
Lista de objetos contendo informações sobre cada ponto de extremidade do protocolo no sistema.
 a| 
xref:reference_element_api_protocolendpoint.adoc[protocoloEndpoint]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "method": "ListProtocolEndpoints",
  "params": {}
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "protocolEndpoints": [
      {
        "primaryProviderID": 1,
        "protocolEndpointID": "1387e257-d2e3-4446-be6d-39db71583e7b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000016970687200000000",
        "secondaryProviderID": 2
      },
      {
        "primaryProviderID": 2,
        "protocolEndpointID": "1f16ed86-3f31-4c76-b004-a1251187700b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000026970687200000000",
        "secondaryProviderID": 3
      },
      {
        "primaryProviderID": 4,
        "protocolEndpointID": "c6458dfe-9803-4350-bb4e-68a3feb7e830",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000046970687200000000",
        "secondaryProviderID": 1
      },
      {
        "primaryProviderID": 3,
        "protocolEndpointID": "f3e7911d-0e86-4776-97db-7468c272213f",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000036970687200000000",
        "secondaryProviderID": 4
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
