---
permalink: api/reference_element_api_removenodes.html 
sidebar: sidebar 
keywords: node,nodes,cluster,remove,removing,removenodes 
summary: Você pode usar RemoveNodes para remover um ou mais nós que não devem mais participar do cluster. 
---
= Remover nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `RemoveNodes` Remover um ou mais nós que não devem mais participar do cluster.

Antes de remover um nó, você deve remover todas as unidades que o nó contém usando o `RemoveDrives` método.  Você não pode remover um nó até que o `RemoveDrives` O processo foi concluído e todos os dados foram migrados do nó.  Após a remoção de um nó, ele se registra como um nó pendente.  Você pode adicionar o nó novamente ou desligá-lo (desligar o nó o remove da lista de nós pendentes).



== remoção do nó mestre do cluster

Se você usar `RemoveNodes` Para remover o nó mestre do cluster, o método pode atingir o tempo limite antes de retornar uma resposta.  Se a chamada do método falhar ao remover o nó, faça a chamada do método novamente.  Observe que, se você estiver removendo o nó mestre do cluster juntamente com outros nós, deverá usar uma chamada separada para remover apenas o nó mestre do cluster.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ignorarAlteraçãoDeTolerânciaDoConjunto
 a| 
Ignore as alterações na tolerância a falhas dos nós do conjunto ao remover nós.

Se o cluster de armazenamento utiliza esquemas de proteção de dados que toleram múltiplas falhas de nós e a remoção dos nós diminuiria a tolerância a falhas do conjunto, a remoção do nó normalmente falhará com um erro.  Você pode definir esse parâmetro como verdadeiro para desativar a verificação de tolerância do conjunto, garantindo que a remoção do nó seja bem-sucedida.
 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
nós
 a| 
Lista de IDs dos nós a serem removidos.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método não possui valor de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "RemoveNodes",
   "params": {
     "nodes"  : [3,4,5]
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1
  "result" : {},
}
----


== Novidade desde a versão

9,6
