---
permalink: api/reference_element_api_liststoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,containers,list,listing,liststoragecontainers 
summary: Você pode usar o método ListStorageContainers para recuperar informações sobre todos os contêineres de armazenamento de volume virtual conhecidos pelo sistema. 
---
= Listar contêineres de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListStorageContainers` Método para recuperar informações sobre todos os contêineres de armazenamento de volume virtual conhecidos pelo sistema.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IDs de contêineres de armazenamento
 a| 
Uma lista de IDs de contêineres de armazenamento para os quais se deseja recuperar informações.  Se você omitir esse parâmetro, o método retornará informações sobre todos os contêineres de armazenamento no sistema.
 a| 
matriz UUID
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
contêineres de armazenamento
 a| 
Lista de objetos contendo informações sobre todos os contêineres de armazenamento no sistema.
 a| 
xref:reference_element_api_storagecontainer.adoc[contêiner de armazenamento]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListStorageContainers",
   "params": {
      "storageContainerIDs": ["efda8307-b916-4424-979e-658a3f16894d"]
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 6395,
  "result": {
    "storageContainers": [
      {
        "accountID": 64,
        "initiatorSecret": "EJ:08An1MyNQmL!7",
        "name": "VvolContainer",
        "protocolEndpointType": "SCSI",
        "status": "active",
        "storageContainerID": "efda8307-b916-4424-979e-658a3f16894d",
        "targetSecret": "g38}zWBK%206jQr~",
        "virtualVolumes": []
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
