---
permalink: api/reference_element_api_getvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volume,access,group,groups,LUN,mapping,assignment,get,getting,GetVolumeAccessGroupLunAssignments 
summary: Você pode usar o método GetVolumeAccessGroupLunAssignments para recuperar detalhes sobre os mapeamentos de LUN de um grupo de acesso a volumes específico. 
---
= GetVolumeAccessGroupLunAssignments
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetVolumeAccessGroupLunAssignments` Método para recuperar detalhes sobre os mapeamentos de LUN de um grupo de acesso a volumes específico.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do grupo de acesso ao volume
 a| 
Um ID de grupo de acesso a volume exclusivo usado para retornar informações.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volumeAccessGroupLunAssignments
 a| 
Uma lista de todas as portas físicas Fibre Channel, ou de uma porta para um único nó.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetVolumeAccessGroupLunAssignments",
   "params": {
      "volumeAccessGroupID": 5
    },
  "id" : 1
   }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1,
  "result" : {
    "volumeAccessGroupLunAssignments" : {
       "volumeAccessGroupID" : 5,
       "lunAssignments" : [
          {"volumeID" : 5, "lun" : 0},
          {"volumeID" : 6, "lun" : 1},
          {"volumeID" : 7, "lun" : 2},
          {"volumeID" : 8, "lun" : 3}
       ],
       "deletedLunAssignments" : [
           {"volumeID" : 44, "lun" : 44}
       ]
    }
  }
}
----


== Novidade desde a versão

9,6
