---
permalink: api/reference_element_api_createvolume.html 
sidebar: sidebar 
keywords: create,volume,volumes,creating,CreateVolume 
summary: Você pode usar o método CreateVolume para criar um novo volume vazio no cluster.  Assim que a criação do volume for concluída, o volume estará disponível para conexão via iSCSI. 
---
= CriarVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CreateVolume` Método para criar um novo volume vazio no cluster.  Assim que o volume for criado, ele estará disponível para conexão via iSCSI.

Volumes criados sem valores de QoS especificados utilizam os valores padrão.  Você pode visualizar os valores padrão de um volume usando o `GetDefaultQoS` método.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


| `access` | O modo de acesso ao volume.  Se este parâmetro for incluído, o único valor suportado será `snapMirrorTarget` . | corda | Nenhum | Não 


| `accountID` | O ID da conta proprietária deste volume. | inteiro | Nenhum | Sim 


| `associateWithQoSPolicy`  a| 
Associe o volume à política de QoS especificada. Valores possíveis:

* `true`Associe o volume à política de QoS especificada no parâmetro QoSPolicyID.
* `false`Não associe o volume à política de QoS especificada no parâmetro QoSPolicyID.  Quando definido como falso, qualquer associação de política existente é removida, independentemente de você especificar uma política de QoS no parâmetro QoSPolicy.

| booleano | verdadeiro | Não 


| `attributes` | Lista de pares nome-valor em formato de objeto JSON.  O tamanho total do atributo deve ser inferior a 1000 bytes, ou 1 KB, incluindo os caracteres de formatação JSON. | objeto JSON | Nenhum | Não 


| `dontMoveforIopsRebalance`  a| 
Impeça a movimentação de um volume durante o balanceamento de carga com IOPS reais.  Essa configuração está disponível a partir do Element 12.8 e só entra em vigor quandolink:reference_element_api_enablefeature.html["VolumeLoadBalanceOnActualIOPS"] está ativado. Valores possíveis:

* `true`O balanceamento de carga por volume não é baseado em IOPS reais.
* `false`O Volume realiza o balanceamento de carga com base nas IOPS reais.


*Nota*: O balanceamento para alta disponibilidade (falha de nó) tem precedência sobre `VolumeLoadBalanceOnActualIOPS` e `dontMoveforIopsRebalance` .
| booleano | falso | Não 


| `enable512e`  a| 
Ativar a emulação de setores de 512 bytes. Valores possíveis:

* `true`O volume oferece emulação de setor de 512 bytes.
* `false`A emulação 512e não está habilitada.

| booleano | Nenhum | Sim 


| `enableSnapMirrorReplication`  a| 
Determina se o volume pode ser usado para replicação com endpoints do SnapMirror . Valores possíveis:

* `true`
* `false`

| booleano | falso | Não 


| `fifoSize` | Especifica o número máximo de snapshots FIFO (First-In-First-Out) suportados pelo volume.  Observe que os snapshots FIFO e não-FIFO utilizam o mesmo conjunto de slots de snapshot disponíveis em um volume.  Use esta opção para limitar o consumo de snapshots FIFO nos slots de snapshot disponíveis.  Caso seja omitido, o valor padrão será 24. | inteiro | 24 | Não 


| `minFifoSize` | Especifica o número mínimo de slots de snapshot FIFO (First-In-First-Out) reservados pelo volume.  Isso garante que, se você estiver usando snapshots FIFO e snapshots não-FIFO em um volume, os snapshots não-FIFO não consumirão involuntariamente muitos slots FIFO.  Isso também garante que pelo menos essa quantidade de snapshots FIFO esteja sempre disponível.  Como os snapshots FIFO e não-FIFO compartilham o mesmo pool, o `minFifoSize` reduz o número total de possíveis snapshots não-FIFO na mesma proporção.  Se omitido, o valor padrão é 0. | inteiro | 0 | Não 


| `name` | Nome do grupo de acesso ao volume (pode ser especificado pelo usuário).  Não precisa ser original, mas é recomendável.  Deve ter entre 1 e 64 caracteres. | corda | Nenhum | Sim 


| `qos`  a| 
Configurações iniciais de qualidade de serviço para este volume.  Se nenhum valor for especificado, serão utilizados os valores padrão. Valores possíveis:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

| Objeto QoS | Nenhum | Não 


| `qosPolicyID` | O ID da política cujas configurações de QoS devem ser aplicadas aos volumes especificados.  Este parâmetro é mutuamente exclusivo com o `qos` parâmetro. | inteiro | Nenhum | Não 


| `totalSize` | Tamanho total do volume, em bytes.  O tamanho é arredondado para o megabyte mais próximo. | inteiro | Nenhum | Sim 
|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
volume
 a| 
Objeto contendo informações sobre o volume recém-criado.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
ID do volume
 a| 
O ID do volume recém-criado.
 a| 
inteiro



 a| 
curva
 a| 
A curva é um conjunto de pares chave-valor.  As chaves representam os tamanhos de entrada/saída em bytes.  Os valores representam o custo de realizar uma IOP em um tamanho de E/S específico.  A curva é calculada em relação a uma operação de 4096 bytes configurada para 100 IOPS.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "CreateVolume",
   "params": {
      "name": "testit",
      "accountID": 22,
      "dontMoveForIopsRebalance": true,
      "totalSize": 100000000000,
      "enable512e": false,
      "attributes": {},
      "qos": {
         "minIOPS": 500,
         "maxIOPS": 27000,
         "burstIOPS": 27000,
         "burstTime": 60
      }
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id": 1,
    "result": {
        "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
        },
        "volume": {
            "access": "readWrite",
            "accountID": 22,
            "attributes": {},
            "blockSize": 4096,
            "createTime": "2024-04-02T13:03:02Z",
            "currentProtectionScheme": "doubleHelix",
            "deleteTime": "",
            "dontMoveForIopsRebalance": true,
            "enable512e": false,
            "enableSnapMirrorReplication": false,
            "fifoSize": 24,
            "iqn": "iqn.2010-01.com.solidfire:mysqldata.677",
            "lastAccessTime": null,
            "lastAccessTimeIO": null,
            "minFifoSize": 0,
            "name": "testit",
            "previousProtectionScheme": null,
            "purgeTime": "",
            "qos": {
                "burstIOPS": 27000,
                "burstTime": 60,
                "curve": {
                    "1048576": 15000,
                    "131072": 1950,
                    "16384": 270,
                    "262144": 3900,
                    "32768": 500,
                    "4096": 100,
                    "524288": 7600,
                    "65536": 1000,
                    "8192": 160
                },
                "maxIOPS": 27000,
                "minIOPS": 500
            },
            "qosPolicyID": null,
            "scsiEUIDeviceID": "3365657500000140f47acc0100000000",
            "scsiNAADeviceID": "6f47acc1000000003365657500000140",
            "sliceCount": 0,
            "status": "active",
            "totalSize": 1000000716800,
            "virtualVolumeID": null,
            "volumeAccessGroups": [],
            "volumeConsistencyGroupUUID": "8ed68e57-13ee-47df-8381-29b125142718",
            "volumeID": 320,
            "volumePairs": [],
            "volumeUUID": "e0e2c938-4ecd-4de9-a1be-f6b17c93ce5d"
        },
        "volumeID": 320
    }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_getdefaultqos.adoc[Obter QoS padrão]
