---
permalink: api/reference_element_api_modifyqospolicy.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,qos,policy,policies,modifyqospolicy 
summary: Você pode usar o método ModifyQoSPolicy para modificar uma política de QoS existente no sistema. 
---
= ModificarPolítica de QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyQoSPolicy` Método para modificar uma política de QoS existente no sistema.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
qosPolicyID
 a| 
O ID da política a ser modificada.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
nome
 a| 
Se fornecido, o nome da política de QoS (por exemplo, ouro, platina, prata) será alterado para esse valor.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
qos
 a| 
Se fornecidas, as configurações de QoS para esta política serão alteradas para essas configurações.  Você pode fornecer valores parciais de QoS e alterar apenas algumas das configurações de QoS.
 a| 
Objeto QoS
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
Política de QoS
 a| 
Detalhes da política de QoS recentemente modificada.
 a| 
xref:reference_element_api_qospolicy.adoc[Política de QoS]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 1950,
  "method": "ModifyQoSPolicy",
  "params": {
    "qosPolicyID": 2,
    "qos": {
      "minIOPS": 51,
      "maxIOPS": 15002,
      "burstIOPS": 15002
    }
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1950,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15002,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15002,
        "minIOPS": 51
      },
      "qosPolicyID": 2,
      "volumeIDs": [
        2
      ]
    }
  }
}
----


== Novidade desde a versão

10,0
