---
permalink: api/reference_element_api_modifysnapmirrorendpoint.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,endpoint,modifysnapmirrorendpoint 
summary: A interface web do software Element utiliza o método ModifySnapMirrorEndpoint para alterar o nome e os atributos de gerenciamento de um endpoint SnapMirror . 
---
= ModificarPonto de extremidade do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do software Element utiliza o `ModifySnapMirrorEndpoint` Método para alterar o nome e os atributos de gerenciamento de um endpoint do SnapMirror .



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do ponto de extremidade do SnapMirror
 a| 
O endpoint do SnapMirror a ser modificado.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
gerenciamento de IP
 a| 
O novo endereço IP de gerenciamento para o sistema ONTAP .
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
nome de usuário
 a| 
O novo nome de usuário de gerenciamento para o sistema ONTAP .
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
senha
 a| 
A nova senha de gerenciamento para o sistema ONTAP .
 a| 
corda
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
snapMirrorEndpoint
 a| 
Informações sobre o endpoint SnapMirror modificado.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint]

|===


== Novidade desde a versão

10,0
