---
permalink: api/reference_element_api_setremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,host,hosts,set,setting,setremotelogginghosts 
summary: Você pode usar o método SetRemoteLoggingHosts para configurar o registro remoto de logs dos nós do cluster de armazenamento para um ou mais servidores de log centralizados.  O registro remoto é realizado via TCP usando a porta padrão 514.  Esta API não adiciona nada aos hosts de registro existentes.  Em vez disso, substitui o que existe atualmente por novos valores especificados por este método da API.  Você pode usar GetRemoteLoggingHosts para determinar quais são os hosts de registro atuais e, em seguida, usar SetRemoteLoggingHosts para definir a lista desejada de hosts de registro atuais e novos. 
---
= DefinirHostsDeRegistroRemoto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetRemoteLoggingHosts` Método para configurar o registro remoto de logs dos nós do cluster de armazenamento para um ou mais servidores de log centralizados.  O registro remoto é realizado via TCP usando a porta padrão 514.  Esta API não adiciona nada aos hosts de registro existentes.  Em vez disso, substitui o que existe atualmente por novos valores especificados por este método da API.  Você pode usar `GetRemoteLoggingHosts` para determinar quais são os hosts de registro atuais e, em seguida, usar `SetRemoteLoggingHosts` Para definir a lista desejada de hosts de registro atuais e novos.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
hosts remotos
 a| 
Lista de hosts que são destinatários de mensagens de log.
 a| 
xref:reference_element_api_loggingserver.adoc[Servidor de registro]variedade
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "method": "SetRemoteLoggingHosts",
   "params": {
     "remoteHosts": [
        {
          "host": "172.16.1.20",
          "port": 10514
        },
        {
          "host": "172.16.1.25"
        }
      ]
   }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id" : 1,
    "result" : {}
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_getremotelogginghosts.adoc[ObterHostsDeLogRemoto]
