---
permalink: api/reference_element_api_createsnapmirrorvolume.html 
sidebar: sidebar 
keywords: SnapMirror,endpoints,create,creating,volume,volumes,CreateSnapMirrorVolume 
summary: A interface web do Element utiliza o método CreateSnapMirrorVolume para criar um volume no sistema ONTAP remoto. 
---
= CriarVolume de Espelhamento Instantâneo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do Element utiliza o `CreateSnapMirrorVolume` Método para criar um volume no sistema ONTAP remoto.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
snapMirrorEndpointID
 a| 
O ID do ponto de extremidade do sistema de armazenamento ONTAP remoto que se comunica com o cluster de armazenamento Element.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
vserver
 a| 
O nome do Vserver.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
nome
 a| 
O nome do volume ONTAP de destino.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
tipo
 a| 
O tipo de volume. Valores possíveis:

* rw: Volume de leitura e gravação
* ls: Volume de compartilhamento de carga
* dp: Volume de proteção de dados


Se nenhum tipo for fornecido, o tipo padrão será dp.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
agregar
 a| 
O agregado ONTAP que contém o qual o volume será criado.  Você pode usar o ListSnapMirrorAggregates para obter informações sobre os agregados ONTAP disponíveis.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
tamanho
 a| 
O tamanho do volume em bytes.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
snapMirrorVolume
 a| 
Informações sobre um volume do SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolume.adoc[snapMirrorVolume]

|===


== Novidade desde a versão

10,1
