---
permalink: api/reference_element_api_createsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,relationships,create,creating,CreateSnapMirrorRelationship 
summary: A interface web do Element utiliza o método CreateSnapMirrorRelationship para criar uma relação de proteção de dados estendida SnapMirror entre um endpoint de origem e um endpoint de destino. 
---
= CriarRelacionamentoSnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do Element utiliza o `CreateSnapMirrorRelationship` Método para criar uma relação de proteção de dados estendida do SnapMirror entre um endpoint de origem e um endpoint de destino.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
snapMirrorEndpointID
 a| 
O ID do ponto de extremidade do sistema de armazenamento ONTAP remoto que se comunica com o cluster de armazenamento Element.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
volume de origem
 a| 
O volume de origem na relação.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
Nenhum
 a| 
Sim



 a| 
volume de destino
 a| 
O volume de destino no relacionamento.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
Nenhum
 a| 
Sim



 a| 
tipo de relacionamento
 a| 
O tipo de relacionamento.  Em sistemas de armazenamento que executam o software Element, esse valor é sempre "`extended_data_protection`".
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
nomeDaPolítica
 a| 
Especifica o nome da política ONTAP SnapMirror para o relacionamento.  Caso não seja especificado, o nome da política padrão é MirrorLatest.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
nomeDoAgenda
 a| 
O nome da tarefa cron preexistente no sistema ONTAP que é usada para atualizar o relacionamento SnapMirror .  Se nenhum agendamento for definido, as atualizações do snapMirror não serão agendadas e deverão ser feitas manualmente.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
taxa de transferência máxima
 a| 
Especifica a taxa máxima de transferência de dados entre os volumes em kilobytes por segundo.  O valor padrão, 0, é ilimitado e permite que a relação SnapMirror utilize totalmente a largura de banda de rede disponível.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
snapMirrorRelationship
 a| 
Informações sobre o relacionamento SnapMirror recém-criado.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Novidade desde a versão

10,1
