---
permalink: api/reference_element_api_createclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,create,creating,CreateClusterInterfacePreference 
summary: O método CreateClusterInterfacePreference permite que sistemas integrados a clusters de armazenamento que executam o software Element criem e armazenem informações arbitrárias no cluster de armazenamento.  Este método destina-se a uso interno. 
---
= Preferência de Interface de Cluster Criar
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `CreateClusterInterfacePreference` Este método permite que sistemas integrados com clusters de armazenamento que executam o software Element criem e armazenem informações arbitrárias no cluster de armazenamento.  Este método destina-se a uso interno.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
O nome da preferência de interface do cluster.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
valor
 a| 
O valor da preferência da interface do cluster.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método não possui valor de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
		"method": "CreateClusterInterfacePreference",
		"params": {
			"name": "prefname",
			"value": "testvalue"
		},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
	"id": 1,
	"result": {}
}
----


== Novidade desde a versão

11,0
