---
permalink: api/reference_element_api_getsoftwareencryptionatrestinfo.html 
sidebar: sidebar 
keywords: system, api, security, get, getting, software encryption at rest 
summary: Você pode usar o método GetSoftwareEncryptionAtRestInfo para obter informações sobre como o cluster criptografa os dados em repouso. 
---
= GetSoftwareEncryptionAtRestInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetSoftwareEncryptionAtRestInfo` Método para obter informações sobre a criptografia de software em repouso que o cluster usa para criptografar dados em repouso.



== Parâmetros

Este método não possui parâmetros de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

[cols="4*"]
|===
| Parâmetro | Descrição | Tipo | Opcional 


| masterKeyInfo | Informações sobre a chave mestra de criptografia em repouso do software atual. | Informações da chave de criptografia | Verdadeiro 


| rekeyMasterKeyAsyncResultID | O ID do resultado assíncrono da operação de recodificação atual ou mais recente (se houver), caso ainda não tenha sido excluído. `GetAsyncResult` A saída incluirá um `newKey` campo que contém informações sobre a nova chave mestra e um `keyToDecommission` Campo que contém informações sobre a chave antiga. | inteiro | Verdadeiro 


| estado | O estado atual da criptografia de software em repouso.  Os valores possíveis são `disabled` ou `enabled` . | corda | Falso 


| versão | Um número de versão que é incrementado cada vez que a criptografia de software em repouso é ativada. | inteiro | Falso 
|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
 "method": "getsoftwareencryptionatrestinfo"
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id": 1,
    "result": {
        "masterKeyInfo": {
            "keyCreatedTime": "2021-09-20T23:15:56Z",
            "keyID": "4d80a629-a11b-40ab-8b30-d66dd5647cfd",
            "keyManagementType": "internal"
        },
        "state": "enabled",
        "version": 1
    }
}
----


== Novidade desde a versão

12,3

[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

