---
permalink: api/reference_element_api_modifyinitiators.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,initiators,initiator,attribute,attributes,modifyinitiators 
summary: Você pode usar o método ModifyInitiators para alterar os atributos de um ou mais iniciadores existentes. 
---
= ModificarIniciadores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyInitiators` Método para alterar os atributos de um ou mais iniciadores existentes.

Não é possível alterar o nome de um iniciador existente.  Se precisar alterar o nome de um iniciador, exclua-o primeiro com oxref:reference_element_api_deleteinitiators.adoc[ExcluirIniciadores] método e crie um novo com oxref:reference_element_api_createinitiators.adoc[CriarIniciadores] método.

Se o método ModifyInitiators não conseguir alterar um dos iniciadores fornecidos como parâmetro, ele retornará um erro e não modificará nenhum iniciador (não é possível a conclusão parcial).



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
iniciadores
 a| 
Uma lista de objetos contendo as características de cada iniciador a ser modificado.  Possíveis objetos:

* `alias`: (Opcional) Um novo nome amigável para atribuir ao iniciador.  (corda)
* `attributes`: (Opcional) Um novo conjunto de atributos JSON para atribuir ao iniciador.  (Objeto JSON)
* `chapUsername`: (Opcional) Um novo nome de usuário CHAP exclusivo para este iniciador.  (corda)
* `forceDuringUpgrade`Conclua a modificação do iniciador durante uma atualização.
* `initiatorID`: (Obrigatório) O ID do iniciador a ser modificado.  (inteiro)
* `initiatorSecret`: (Opcional) Um novo segredo CHAP usado para autenticar o iniciador.  (corda)
* `requireChap`: (Opcional) Verdadeiro se o CHAP for necessário para este iniciador.  (booleano)
* `targetSecret`: (Opcional) Um novo segredo CHAP usado para autenticar o alvo (ao usar autenticação CHAP mútua).  (corda)
* `virtualNetworkIDs`: (Opcional) A lista de identificadores de rede virtual associados a este iniciador.  Se você definir uma ou mais redes virtuais, este iniciador só poderá fazer login nessas redes virtuais.  Se você não definir nenhuma rede virtual, esse iniciador poderá fazer login em todas as redes.
* `volumeAccessGroupID`: (Opcional) O ID do grupo de acesso ao volume ao qual o iniciador deve ser adicionado.  Se o iniciador estava anteriormente em um grupo de acesso a volume diferente, ele será removido do grupo de acesso a volume antigo.  Se essa chave estiver presente, mas for nula, o iniciador será removido do seu grupo de acesso a volumes atual, mas não será adicionado a nenhum novo grupo de acesso a volumes.  (inteiro)

 a| 
matriz de objetos JSON
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
iniciadores
 a| 
Lista de objetos que descrevem os iniciadores recém-modificados.
 a| 
xref:reference_element_api_initiator.adoc[iniciador]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 6683,
  "method": "ModifyInitiators",
  "params": {
    "initiators": [
      {
        "initiatorID": 2,
        "alias": "alias1",
        "volumeAccessGroupID": null
      },
      {
        "initiatorID": 3,
        "alias": "alias2",
        "volumeAccessGroupID": 1
      }
    ]
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 6683,
  "result": {
    "initiators": [
      {
        "alias": "alias1",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:395543635",
        "volumeAccessGroups": []
      },
      {
        "alias": "alias2",
        "attributes": {},
        "initiatorID": 3,
        "initiatorName": "iqn.1993-08.org.debian:01:935573135",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

* xref:reference_element_api_createinitiators.adoc[CriarIniciadores]
* xref:reference_element_api_deleteinitiators.adoc[ExcluirIniciadores]

