---
permalink: api/reference_element_api_listvirtualvolumebindings.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,cluster,bound,protocol,endpoint,binding,bindings,list,listing,listvirtualvolumebindings 
summary: Você pode usar o método ListVirtualVolumeBindings para obter uma lista de todos os volumes virtuais no cluster que estão vinculados a endpoints de protocolo. 
---
= ListarVinculaçõesDeVolumeVirtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVirtualVolumeBindings` Método para obter uma lista de todos os volumes virtuais no cluster que estão vinculados a endpoints de protocolo.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IDs de vinculação de volume virtual
 a| 
Uma lista de IDs de vinculação de volume virtual para os quais recuperar informações.  Se você omitir esse parâmetro, o método retornará informações sobre todas as associações de volume virtual.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
encadernações
 a| 
Uma lista de objetos que descrevem todos os volumes virtuais no cluster que estão vinculados a endpoints de protocolo.
 a| 
xref:reference_element_api_binding_vvols.adoc[vinculativo]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVirtualVolumeBindings",
    "params": {
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "bindings": [
      {
        "protocolEndpointID": "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b",
        "protocolEndpointInBandID": "naa.6f47acc2000000016a67746700000000",
        "protocolEndpointType": "SCSI",
        "virtualVolumeBindingID": 177,
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeSecondaryID": "0xe200000000a6"
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
