---
permalink: api/reference_element_api_createidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,create,creating 
summary: 'Você pode usar o método CreateIpdConfiguration para criar uma possível relação de confiança para autenticação usando um provedor de identidade (IdP) de terceiros para o cluster.  É necessário um certificado de provedor de serviços SAML para a comunicação com o IdP.  Este certificado é gerado conforme necessário e retornado por esta chamada de API.' 
---
= Criar configuração Idp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CreateIpdConfiguration` Método para criar uma relação de confiança potencial para autenticação usando um provedor de identidade (IdP) de terceiros para o cluster.  É necessário um certificado de provedor de serviços SAML para a comunicação com o IdP.  Este certificado é gerado conforme necessário e retornado por esta chamada de API.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
idpMetadata
 a| 
Metadados do IdP para armazenar.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
idpName
 a| 
Nome usado para identificar um provedor IdP para autenticação única SAML 2.0.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
Informações de configuração do idp
 a| 
Informações sobre a configuração do provedor de identidade (IdP) de terceiros.
 a| 
link:reference_element_api_idpconfiginfo.html["Informações de configuração do idp"]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
    "method": "CreateIdpConfiguration",
    "params": {
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
             <EntityDescriptor
               xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"
               xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"
               xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"
               xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"
               ...</Organization>
             </EntityDescriptor>",
        "idpName": "https://provider.name.url.com"
    },
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": false,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ... </Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MIID...SlBHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Novidade desde a versão

12,0
