---
permalink: api/reference_element_api_getdriveconfig.html 
sidebar: sidebar 
keywords: drive,config,configuration,get,getting,getdriveconfig 
summary: Você pode usar o método GetDriveConfig para obter informações sobre as unidades, como a quantidade esperada de unidades de partição e de bloco, bem como o número de unidades de partição e de bloco atualmente conectadas ao nó. 
---
= GetDriveConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetDriveConfig` Método para obter informações sobre as unidades, incluindo a quantidade esperada de unidades de partição e de bloco, bem como o número de unidades de partição e de bloco atualmente conectadas ao nó.



== Parâmetros

Este método não possui parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
driveConfig
 a| 
Informações sobre as unidades de disco conectadas ao nó.
 a| 
xref:reference_element_api_drive.adoc[dirigir]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetDriveConfig",
   "params": {},
   "id" : 1
}
----


== Exemplo de resposta

As respostas para este método são semelhantes ao exemplo a seguir.  Devido ao seu tamanho, a resposta contém informações apenas para uma unidade de um nó de armazenamento.

[listing]
----
{
	"id": 1,
	"result": {
			"driveConfig": {
					"drives": [
						{
							"canonicalName": "sda",
							"connected": true,
							"dev": 2052,
							"devPath": "/dev/sdimm0p4",
							"driveType": "Slice",
							"name": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"path": "/dev/sda4",
							"pathLink": "/dev/sdimm0p4",
							"product": "VRFSD3400GNCVMTKS1",
							"scsiCompatId": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"scsiState": "Running",
							"securityAtMaximum": false,
							"securityEnabled": false,
							"securityFrozen": true,
							"securityLocked": false,
							"securitySupported": true,
							"serial": "205581853",
							"size": 299988156416,
							"slot": -1,
							"uuid": "9d4b198b-5ff9-4f7c-04fc-3bc4e2f38974",
							"vendor": "Viking",
							"version": "612ABBF0"
						}
					],
					"numBlockActual": 10,
					"numBlockExpected": 10,
					"numSliceActual": 1,
					"numSliceExpected": 1,
					"numTotalActual": 11,
					"numTotalExpected": 11
			}
	}
}
----