---
permalink: api/reference_element_api_clonemultiplevolumes.html 
sidebar: sidebar 
keywords: volume,volumes,clone,cloning,multiple,CloneMultipleVolumes 
summary: Você pode usar o método CloneMultipleVolumes para criar um clone de um grupo de volumes especificados.  É possível atribuir um conjunto consistente de características a um grupo de múltiplos volumes quando eles são clonados em conjunto. 
---
= Clonar múltiplos volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CloneMultipleVolumes` Método para criar um clone de um grupo de volumes especificados.  É possível atribuir um conjunto consistente de características a um grupo de múltiplos volumes quando eles são clonados em conjunto.

Antes de usar o parâmetro groupSnapshotID para clonar os volumes em um snapshot de grupo, você deve primeiro criar o snapshot de grupo usando oxref:reference_element_api_creategroupsnapshot.adoc[Criar instantâneo de grupo] Método da API ou interface web.  O uso do groupSnapshotID é opcional ao clonar vários volumes.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
acesso
 a| 
Novo método de acesso padrão para os novos volumes, caso não seja substituído por informações passadas na matriz do volume.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
ativarSnapMirrorReplication
 a| 
Determina se o volume pode ser usado para replicação com endpoints do SnapMirror . Valores possíveis:

* verdadeiro
* falso

 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
ID do instantâneo do grupo
 a| 
ID do snapshot do grupo a ser usado como base para o clone.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não



 a| 
novoIDdaconta
 a| 
Novo ID de conta para os volumes, caso não seja substituído por informações passadas na matriz de volumes.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não



 a| 
volumes
 a| 
Conjunto de membros que você especificar para os novos volumes.  Membros:

* ID do volume: (Obrigatório)
* Acesso: (Opcional) Pode ser um dos seguintes: somente leitura, leitura e gravação, bloqueado ou destino de replicação.
* Atributos: (Opcional) Lista de pares nome-valor em formato de objeto JSON.
* Nome: (Opcional) Novo nome para o clone.
* newAccountID: (Opcional) ID da conta para os novos volumes.
* newSize: (Opcional) Tamanho total do volume, em bytes.  O tamanho é arredondado para o megabyte mais próximo.


Caso os membros opcionais não sejam especificados, os valores serão herdados dos volumes de origem.
 a| 
matriz de objetos JSON
 a| 
Nenhum
 a| 
Sim (volumeID)

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
manipulador assíncrono
 a| 
Um valor retornado de uma chamada de método assíncrona.
 a| 
inteiro



 a| 
ID de clone do grupo
 a| 
ID único do novo clone do grupo.
 a| 
inteiro



 a| 
membros
 a| 
Lista de IDs de volume para os pares de volumes de origem e destino.
 a| 
matriz de objetos JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "CloneMultipleVolumes",
   "params": {
       "volumes": [
           {
              "volumeID": 5
              "name":"foxhill",
              "access":"readOnly"
              },
           {
              "volumeID": 18
              },
           {
             "volumeID": 20
              }
     ]
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "asyncHandle": 12,
    "groupCloneID": 4,
    "members": [
     {
      "srcVolumeID": 5,
      "volumeID": 29
     },
     {
      "srcVolumeID": 18,
      "volumeID": 30
     },
     {
      "srcVolumeID": 20,
      "volumeID": 31
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
