---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: Você pode usar o método ListVirtualVolumes para listar os volumes virtuais atualmente presentes no sistema.  Você pode usar esse método para listar todos os volumes virtuais ou apenas um subconjunto deles. 
---
= ListarVolumesVirtuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVirtualVolumes` Método para listar os volumes virtuais atualmente presentes no sistema.  Você pode usar esse método para listar todos os volumes virtuais ou apenas um subconjunto deles.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
detalhes
 a| 
O nível de detalhamento da resposta. Valores possíveis:

* Verdadeiro: Inclua mais detalhes sobre cada VVol na resposta.
* falso: Inclua o nível padrão de detalhes sobre cada VVol na resposta.

 a| 
booleano
 a| 
Falso
 a| 
Não



 a| 
limite
 a| 
Número máximo de volumes virtuais a serem listados.
 a| 
inteiro
 a| 
10000
 a| 
Não



 a| 
recursivo
 a| 
Especifica se as informações sobre os filhos de cada VVol devem ser incluídas na resposta ou não. Valores possíveis:

* Verdadeiro: Inclua informações sobre os filhos de cada VVol na resposta.
* falso: Não inclua informações sobre os filhos de cada VVol na resposta.

 a| 
booleano
 a| 
Falso
 a| 
Não



 a| 
startVirtualVolumeID
 a| 
O ID do volume virtual a partir do qual iniciar a lista na resposta.
 a| 
Tipo UUID
 a| 
Nenhum
 a| 
Não



 a| 
IDs de volume virtuais
 a| 
Uma lista de IDs de volumes virtuais para os quais se desejam recuperar informações.  Se você omitir esse parâmetro, o método retornará informações apenas sobre esses volumes virtuais.
 a| 
array UUID de virtualVolumeID
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
nextVirtualVolumeID
 a| 
O ID do próximo volume virtual na lista.
 a| 
UUID



 a| 
volumes virtuais
 a| 
Uma lista de objetos que descrevem os volumes virtuais atualmente presentes no sistema.
 a| 
xref:reference_element_api_virtualvolume.adoc[volume virtual]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
