---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: Você pode usar o método GetNodeActiveTlsCiphers em um único nó para obter uma lista das cifras TLS que são atualmente aceitas nesse nó.  Você pode usar esse método em nós de gerenciamento e armazenamento. 
---
= ObterCifrasTlsAtivasDoNó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNodeActiveTlsCiphers` Método em um único nó para obter uma lista das cifras TLS que são atualmente aceitas nesse nó.  Você pode usar esse método em nós de gerenciamento e armazenamento.



== Parâmetro

Este método não possui parâmetros de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
Cifras obrigatórias
 a| 
Lista de conjuntos de cifras TLS obrigatórios para o nó.  Essas são cifras que estão sempre ativas no nó.
 a| 
corda



 a| 
Cifras suplementares
 a| 
Lista de conjuntos de cifras TLS suplementares para o nó.
 a| 
corda

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----