---
permalink: api/reference_element_api_listauthsessionbyclusteradmin.html 
sidebar: sidebar 
keywords: cluster admin,sessions,auth sessions,list 
summary: Você pode usar o método ListAuthSessionsByClusterAdmin para listar todas as sessões de autenticação associadas ao ClusterAdminID especificado.  Se o ClusterAdminID especificado corresponder a um grupo de usuários, todas as sessões de autenticação de todos os membros desse grupo serão listadas. 
---
= ListAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListAuthSessionsByClusterAdmin` Método para listar todas as sessões de autenticação associadas ao especificado. `ClusterAdminID` .  Se o especificado `ClusterAdminID` Ao mapear um grupo de usuários, todas as sessões de autenticação de todos os membros desse grupo serão listadas.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do administrador do cluster
 a| 
Identificador único para o administrador do cluster.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
sessões
 a| 
Lista de informações da sessão para as sessões de autenticação.
 a| 
link:reference_element_api_authsessioninfo.html["informações da sessão de autenticação"]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
    "method": "ListAuthSessionsByClusterAdmin",
    "clusterAdminID": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Novidade desde a versão

12,0
