---
permalink: api/reference_element_api_setsnmpacl.html 
sidebar: sidebar 
keywords: setsnmpACL,set,setting,snmp,acl,permissions,access,control,list 
summary: Você pode usar o método SetSnmpACL para configurar as permissões de acesso SNMP nos nós do cluster.  Os valores definidos por meio dessa interface se aplicam a todos os nós do cluster, e os valores passados substituem todos os valores definidos em qualquer chamada anterior à função SetSnmpACL.  Observe também que os valores definidos com esta interface substituem todos os valores de rede ou usmUsers definidos com o SetSnmpInfo. 
---
= Definir ACL SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetSnmpACL` Método para configurar permissões de acesso SNMP nos nós do cluster.  Os valores definidos por meio dessa interface se aplicam a todos os nós do cluster, e os valores passados substituem todos os valores definidos em qualquer chamada anterior. `SetSnmpACL` .  Observe também que os valores definidos com esta interface substituem todos os valores de rede ou usmUsers definidos com a `SetSnmpInfo` método.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
redes
 a| 
Lista de redes e o tipo de acesso que elas têm aos servidores SNMP em execução nos nós do cluster.  Consulte o objeto de rede SNMP para obter os valores de rede possíveis.  Este parâmetro é necessário se o SNMP v3 estiver desativado.
 a| 
xref:reference_element_api_network_snmp.adoc[rede]
 a| 
Nenhum
 a| 
Não



 a| 
usmUsers
 a| 
Lista de usuários e o tipo de acesso que eles têm aos servidores SNMP em execução nos nós do cluster.  Este parâmetro é necessário se o SNMP v3 estiver ativado.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "SetSnmpACL",
  "params": {
    "usmUsers"  : [
      {
         "name": "jdoe",
         "access": "rouser",
         "secLevel": "priv",
         "password": "mypassword",
         "passphrase": "mypassphrase",
      }
    ]
  },
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_setsnmpinfo.adoc[SetSnmpInfo]
