---
permalink: api/reference_element_api_removeclusteradmin.html 
sidebar: sidebar 
keywords: cluster,admin,remove,removing,removeclusteradmin 
summary: 'Você pode usar o método RemoveClusterAdmin para remover um administrador de cluster, um administrador de cluster LDAP ou um administrador de cluster de um provedor de identidade (IdP) de terceiros.  Não é possível remover a conta de administrador do cluster "admin".' 
---
= RemoverAdministradorDeCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `RemoveClusterAdmin` Método para remover um administrador de cluster, um administrador de cluster LDAP ou um administrador de cluster de um provedor de identidade (IdP) de terceiros.  Não é possível remover a conta de administrador do cluster "admin".



== Parâmetro

Quando um administrador de cluster IdP que possui sessões autenticadas associadas a um provedor de identidade (IdP) de terceiros é removido, essas sessões serão encerradas ou possivelmente perderão os direitos de acesso na sessão atual.  A perda dos direitos de acesso dependerá se o administrador do cluster IdP removido corresponde a um dos vários administradores de cluster IdP dos atributos SAML de um determinado usuário.  O conjunto restante de administradores de cluster IdP correspondentes resulta em um conjunto reduzido de direitos de acesso agregados.  Outros tipos de usuários administradores de cluster são desconectados quando seus administradores de cluster são removidos.

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do administrador do cluster
 a| 
ClusterAdminID para o administrador do cluster remover.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "RemoveClusterAdmin",
   "params": {
     "clusterAdminID"  : 2
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
 "id" : 1
 "result" : { }
}
----


== Novidade desde a versão

9,6
