---
permalink: api/reference_element_api_listvolumestatsbyaccount.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,account,listvolumestatsbyaccount,activity 
summary: Você pode usar o método ListVolumeStatsByAccount para listar as principais métricas de atividade de volume para cada conta.  Os valores são a soma de todos os volumes pertencentes à conta. 
---
= ListVolumeStatsByAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumeStatsByAccount` Método para listar as principais métricas de volume de atividade para cada conta.  Os valores são a soma de todos os volumes pertencentes à conta.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
incluirVolumesVirtuais
 a| 
Por padrão, os volumes virtuais são incluídos na resposta.  Para excluir volumes virtuais, defina como falso.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
contas
 a| 
Uma lista de IDs de contas para as quais devem ser retornadas as estatísticas de volume.  Caso seja omitido, serão retornadas as estatísticas de todas as contas.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
Estatísticas de volume
 a| 
Lista de informações sobre a atividade de volume para cada conta.*Nota:* O membro volumeID é 0 para cada entrada, pois os valores representam a soma de todos os volumes pertencentes à conta.
 a| 
xref:reference_element_api_volumestats.adoc[Estatísticas de volume]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method": "ListVolumeStatsByAccount",
  "params": {"accounts": [3]},
  "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 3,
        "nonZeroBlocks": 155040175,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T20:42:26.231661Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [],
        "volumeID": 0,
        "volumeSize": 1127428915200,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 120211025
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
