---
permalink: api/reference_element_api_deletevolume.html 
sidebar: sidebar 
keywords: volume,volumes,delete,deleting,DeleteVolume 
summary: 'Você pode usar o método DeleteVolume para marcar um volume ativo para exclusão.  Quando marcado, o volume é apagado (excluído permanentemente) após o intervalo de limpeza expirar.' 
---
= ExcluirVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteVolume` Método para marcar um volume ativo para exclusão.  Quando marcado, o volume é apagado (excluído permanentemente) após o término do intervalo de limpeza.

Após uma solicitação para excluir um volume, todas as conexões iSCSI ativas com o volume são imediatamente encerradas e nenhuma outra conexão é permitida enquanto o volume estiver nesse estado.  Um volume marcado não é retornado em solicitações de descoberta de destino.

Quaisquer instantâneos de um volume que tenha sido marcado para exclusão não serão afetados.  Os instantâneos são mantidos até que o volume seja removido completamente do sistema.  Se um volume estiver marcado para exclusão e houver uma operação de leitura ou gravação em massa em andamento, essa operação será interrompida.

Se o volume que você excluir estiver emparelhado com outro volume, a replicação entre os volumes emparelhados será suspensa e nenhum dado será transferido para ou a partir dele enquanto estiver em estado de exclusão.  O volume remoto com o qual o volume excluído estava emparelhado entra em um estado PausedMisconfigured e os dados não são mais enviados para ele nem recebidos do volume excluído.  Enquanto o volume excluído não for completamente removido, ele poderá ser restaurado e as transferências de dados retomadas.  Se o volume excluído for removido completamente do sistema, o volume com o qual estava emparelhado entrará no estado ParadoMal Configurado e o status de emparelhamento do volume será removido.  O volume apagado torna-se permanentemente indisponível.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do volume
 a| 
O ID do volume a ser excluído.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volume
 a| 
Objeto contendo informações sobre o volume excluído.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
ID do volume
 a| 
O ID do volume excluído.
 a| 
inteiro



 a| 
curva
 a| 
A curva é um conjunto de pares chave-valor.  As chaves representam os tamanhos de entrada/saída em bytes.  Os valores representam o custo de realizar uma IOP em um tamanho de E/S específico.  A curva é calculada em relação a uma operação de 4096 bytes configurada para 100 IOPS.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "DeleteVolume",
   "params": {
      "volumeID"  : 5
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "volume": {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
      },
      "blockSize": 4096,
      "createTime": "2016-03-28T16:16:13Z",
      "deleteTime": "2016-03-31T22:59:42Z",
      "enable512e": true,
      "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
      "name": "1459181777648",
      "purgeTime": "2016-04-01T06:59:42Z",
      "qos": {
        "burstIOPS": 150,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 100,
        "minIOPS": 60
      },
      "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
      "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
      "sliceCount": 1,
      "status": "deleted",
      "totalSize": 1000341504,
      "virtualVolumeID": null,
      "volumeAccessGroups": [
        1
      ],
      "volumeID": 5,
      "volumePairs": []
    }
  }
}
----


== Novidade desde a versão

9,6
