---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: Você pode usar o método ListEvents para listar os eventos detectados no cluster, classificados do mais antigo para o mais recente. 
---
= ListEventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListEvents` Método para listar os eventos detectados no cluster, ordenados do mais antigo para o mais recente.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
driveID
 a| 
Especifica que somente os eventos com este ID de unidade serão retornados.
 a| 
inteiro
 a| 
0
 a| 
Não



 a| 
endEventID
 a| 
Identifica o fim de um intervalo de IDs de eventos a serem retornados.
 a| 
inteiro
 a| 
(ilimitado)
 a| 
Não



 a| 
hora de publicação
 a| 
Especifica que apenas os eventos publicados antes desse horário serão retornados.
 a| 
corda
 a| 
0
 a| 
Não



 a| 
hora do relatório final
 a| 
Especifica que apenas os eventos relatados antes desse horário serão retornados.
 a| 
corda
 a| 
0
 a| 
Não



 a| 
tipo de evento
 a| 
Especifica o tipo de eventos a serem retornados.  Verxref:reference_element_api_event.adoc[evento] para possíveis tipos de eventos.
 a| 
corda
 a| 
0
 a| 
Não



 a| 
maxEvents
 a| 
Especifica o número máximo de eventos a serem retornados.
 a| 
inteiro
 a| 
(ilimitado)
 a| 
Não



 a| 
ID do nó
 a| 
Especifica que apenas os eventos com este ID de nó serão retornados.
 a| 
inteiro
 a| 
 a| 



 a| 
ID do serviço
 a| 
Especifica que apenas os eventos com este ID de serviço serão retornados.
 a| 
 a| 
 a| 



 a| 
ID do evento inicial
 a| 
Identifica o início de uma série de eventos que se repetirão.
 a| 
inteiro
 a| 
0
 a| 
Não



 a| 
tempo de publicação inicial
 a| 
Especifica que apenas os eventos publicados após esse horário serão retornados.
 a| 
corda
 a| 
0
 a| 
Não



 a| 
hora de iniciar o relatório
 a| 
Especifica que apenas os eventos relatados após esse horário serão retornados.
 a| 
corda
 a| 
0
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
eventos
 a| 
Lista de eventos.
 a| 
xref:reference_element_api_event.adoc[evento]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Novidade desde a versão

9,6
