---
permalink: api/reference_element_api_getpatchinfo.html 
sidebar: sidebar 
keywords: get,patch,info,patches,getpatchinfo 
summary: Você pode usar o método GetPatchInfo para obter informações sobre os patches instalados em um nó. 
---
= Informações do Patch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetPatchInfo` Método para obter informações sobre as atualizações de software do Element instaladas em um nó de armazenamento.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


| `force`  a| 
Forçar a execução do método em todos os nós do cluster de armazenamento.  Você só precisa disso quando estiver enviando a API para um endereço IP de cluster em vez de um único nó. Valores possíveis:

* `true`
* `false`

| booleano | `false` | Não 
|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


| remendos | Objeto contendo informações sobre os patches instalados neste nó. | objeto JSON 
|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetPatchInfo",
   "params": {
      "force": false,
      },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id": 1,
    "result": {
        "patches": {
          "SUST936": {
          "date": "Wed 09 Dec 2020 10:41:59 PM UTC",
          "description": "BMC fixes",
          "newFiles": [
              "None"
          ],
          "patchedFiles": [
              "Patched_file_1.bin",
              "Patched_file_2.dat",
              "Patched_file_3.tgz"
          ]
          }
        }
    }
}

----


== Novidade desde a versão

12,3
