---
permalink: api/reference_element_api_clearclusterfaults.html 
sidebar: sidebar 
keywords: cluster,clear,clearing,fault,faults,support bundles,ClearClusterFaults 
summary: Você pode usar o método ClearClusterFaults para limpar informações sobre falhas atuais e detectadas anteriormente.  É possível corrigir tanto falhas resolvidas quanto não resolvidas. 
---
= Limpar falhas de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ClearClusterFaults` Método para limpar informações sobre falhas atuais e previamente detectadas.  É possível corrigir tanto falhas resolvidas quanto não resolvidas.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
tipos de falha
 a| 
Determina os tipos de falhas a serem corrigidas. Valores possíveis:

* atual:
+
Falhas detectadas atualmente e que ainda não foram resolvidas.

* Resolvido: Falhas que foram previamente detectadas e resolvidas.
* Todos: Falhas atuais e falhas resolvidas.  O estado da falha pode ser determinado pelo campo "`resolved`" do objeto de falha.

 a| 
corda
 a| 
resolvido
 a| 
Não

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ClearClusterFaults",
   "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1,
    "result" : {}
}
----


== Novidade desde a versão

9,6
