---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: Você pode usar o método DisableEncryptionAtRest para remover a criptografia que foi aplicada anteriormente ao cluster usando o método EnableEncryptionAtRest.  Este método de desativação é assíncrono e retorna uma resposta antes que a criptografia seja desativada.  Você pode usar o método GetClusterInfo para consultar o sistema e verificar quando o processo foi concluído. 
---
= Desativar a criptografia em repouso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DisableEncryptionAtRest` método para remover a criptografia que foi aplicada anteriormente ao cluster usando o `EnableEncryptionAtRest` método.  Este método de desativação é assíncrono e retorna uma resposta antes que a criptografia seja desativada.  Você pode usar o `GetClusterInfo` Método para consultar o sistema e verificar quando o processo foi concluído.

[NOTE]
====
* Não é possível usar esse método para desativar a criptografia de software em repouso.  Para desativar a criptografia de software em repouso, você precisalink:reference_element_api_createcluster.html["criar um novo cluster"] Com a criptografia de software em repouso desativada.
* Para visualizar o estado atual da criptografia em repouso, da criptografia de software em repouso ou de ambas no cluster, utilize o link:../api/reference_element_api_getclusterinfo.html["método para obter informações do cluster"]. Você pode usar o `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["Método para obter informações que o cluster usa para criptografar dados em repouso."].


====


== Parâmetros

Este método não possui parâmetros de entrada.



== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== Novidade desde a versão

9,6

[discrete]
== Encontre mais informações

* link:../api/reference_element_api_getclusterinfo.html["Obter informações do cluster"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

