---
permalink: api/reference_element_api_removevolumesfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: remove,removing,volume,volumes,access,group,removevolumesfromvolumeaccessgroup 
summary: Você pode usar o método RemoveVolumesFromVolumeAccessGroup para remover volumes de um grupo de acesso a volumes específico. 
---
= Remover volumes do grupo de acesso a volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `RemoveVolumesFromVolumeAccessGroup` Método para remover volumes de um grupo de acesso a volumes específico.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do grupo de acesso ao volume
 a| 
ID do grupo de acesso ao volume do qual remover volumes.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
volumes
 a| 
IDs de volume dos volumes a serem removidos do grupo de acesso a volumes.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
grupoDeAcessoDeVolume
 a| 
Um objeto contendo informações sobre o grupo de acesso ao volume recém-modificado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[grupoDeAcessoDeVolume]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "RemoveVolumesFromVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "volumes": [1,2]
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        346
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": []
    }
  }
}
----


== Novidade desde a versão

9,6
