---
permalink: api/reference_element_api_listbackuptargets.html 
sidebar: sidebar 
keywords: backup,target,targets,info,list,listing,listbackuptargets 
summary: Você pode usar o método ListBackupTargets para obter informações sobre todos os destinos de backup que foram criados. 
---
= Listar destinos de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListBackupTargets` Método para obter informações sobre todos os destinos de backup que foram criados.



== Parâmetros

Este método não possui parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
alvos de backup
 a| 
Objetos retornados para cada destino de backup.  Objetos incluídos:

* Atributos: Lista de pares nome-valor em formato de objeto JSON.  (Objeto JSON)
* backupTargetID: Identificador único atribuído ao destino do backup.  (inteiro)
* nome: Nome do destino do backup.  (corda)

 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListBackupTargets",
   "params": {},
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result": {
     "backupTargets": [
       {
        "attributes" : {},
        "backupTargetID" : 1,
        "name" : "mytargetbackup"
       }
    ]
  }
}
----


== Novidade desde a versão

9,6
