---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: Você pode usar o método StartVolumePairing para criar uma chave codificada a partir de um volume que será usada para emparelhar com outro volume.  A chave criada por este método é utilizada no método CompleteVolumePairing para estabelecer um emparelhamento de volumes. 
---
= IniciarEmparelhamentoDeVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `StartVolumePairing` Método para criar uma chave codificada a partir de um volume que é usada para emparelhar com outro volume.  A chave que este método cria é usada no `CompleteVolumePairing` Método para estabelecer um emparelhamento de volume.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
modo
 a| 
O modo de volume no qual iniciar o processo de emparelhamento.  O modo só pode ser definido se o volume for o volume de origem. Valores possíveis:

* `Async`As solicitações de escrita são confirmadas quando concluídas localmente.  O cluster não espera que as gravações sejam replicadas para o cluster de destino.  (Padrão se nenhum parâmetro de modo for especificado.)
* `Sync`A origem confirma a gravação quando os dados são armazenados localmente e no cluster remoto.
* `SnapshotsOnly`Somente os snapshots criados no cluster de origem são replicados.  As gravações ativas do volume de origem não são replicadas.

 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
ID do volume
 a| 
O ID do volume no qual iniciar o processo de emparelhamento.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
tecla de emparelhamento de volume
 a| 
Uma sequência de caracteres que é usada peloxref:reference_element_api_completevolumepairing.adoc[Emparelhamento de Volume Completo] Método da API.
 a| 
corda

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_completevolumepairing.adoc[Emparelhamento de Volume Completo]
