---
permalink: api/reference_element_api_rekeysoftwareencryptionatrestmasterkey.html 
sidebar: sidebar 
keywords: system, api, element, security, rekey, software encryption at rest 
summary: 'Você pode usar o método RekeySoftwareEncryptionAtRestMasterKey para gerar uma nova chave mestra de criptografia de software em repouso usada para criptografar DEKs (Chaves de Criptografia de Dados).' 
---
= RekeySoftwareEncryptionAtRestMasterKey
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `RekeySoftwareEncryptionAtRestMasterKey` Método para recodificar a chave mestra de criptografia em repouso do software usada para criptografar DEKs (Chaves de Criptografia de Dados).  Durante a criação do cluster, a criptografia de software em repouso é configurada para usar o Gerenciamento de Chaves Internas (IKM).  Este método de recodificação pode ser usado após a criação do cluster para utilizar tanto o IKM quanto o Gerenciamento de Chaves Externas (EKM).



== Parâmetros

Este método possui os seguintes parâmetros de entrada.  Se o `keyManagementType` Se nenhum parâmetro for especificado, a operação de renegociação de chave será realizada usando a configuração de gerenciamento de chaves existente.  Se o `keyManagementType` se especificado e o provedor de chaves for externo, o `keyProviderID` O parâmetro também deve ser usado.

[cols="4*"]
|===
| Parâmetro | Descrição | Tipo | Opcional 


| keyManagementType | O tipo de gerenciamento de chaves utilizado para gerenciar a chave mestra.  Os valores possíveis são:
`Internal` Recodificação usando gerenciamento de chaves interno.
`External` Recodificação usando gerenciamento de chaves externo.  Caso esse parâmetro não seja especificado, a operação de renegociação de chave será realizada utilizando a configuração de gerenciamento de chaves existente. | corda | Verdadeiro 


| ID do provedor de chave | O ID do provedor de chaves a ser utilizado.  Este é um valor único retornado como parte de um dos `CreateKeyProvider` métodos.  O documento de identificação só é necessário quando `keyManagementType` é `External` e, caso contrário, é inválido. | inteiro | Verdadeiro 
|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

[cols="4*"]
|===
| Parâmetro | Descrição | Tipo | Opcional 


| manipulador assíncrono | Determine o status da operação de recodificação usando este método. `asyncHandle` valor com `GetAsyncResult` . `GetAsyncResult` A saída incluirá um `newKey` campo que contém informações sobre a nova chave mestra e um `keyToDecommission` Campo que contém informações sobre a chave antiga. | inteiro | Falso 
|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
 "method": "rekeysoftwareencryptionatrestmasterkey",
 "params": {
   "keyManagementType": "external",
   "keyProviderID": "<ID number>"
 }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "asyncHandle": 1
}
----


== Novidade desde a versão

12,3

[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

