---
permalink: api/reference_element_api_disablefeature.html 
sidebar: sidebar 
keywords: SNMP,disable,disabling,DisableFeature,vvols,virtual volumes 
summary: Você pode usar o método DisableFeature para desativar o VolumeLoadBalanceOnActualIOPS. 
---
= Desativar recurso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DisableFeature` método para desativar o `VolumeLoadBalanceOnActualIOPS` recurso. `VolumeLoadBalanceOnActualIOPS` Está desativado por padrão.

[NOTE]
====
Se você tentar desativar outro recurso, como VVols, a seguinte mensagem de erro será exibida:

[listing]
----
{"error":{"code":500,"message":"VolumeLoadBalanceOnActualIOPS is the only feature that can be disabled","name":"xAPINotPermitted"},"id":null}
----
====


== Parâmetro

Este método possui o seguinte parâmetro de entrada.

[cols="1a,3a,1a,1a,1a"]
|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
recurso
 a| 
Desativar um recurso de cluster.  Valor possível:

* `VolumeLoadBalanceOnActualIOPS`Desative o balanceamento de fatias com base em IOPS reais em vez de IOPS mínimos.

 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DisableFeature",
    "params": {
        "feature" : "VolumeLoadBalanceOnActualIOPS"
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Novidade desde a versão

12,8
