---
permalink: api/reference_element_api_cluster.html 
sidebar: sidebar 
keywords: objects,object,cluster 
summary: O objeto cluster contém informações que o nó usa para se comunicar com o cluster.  Você pode recuperar essas informações com o método de API GetClusterConfig. 
---
= conjunto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto cluster contém informações que o nó usa para se comunicar com o cluster.  Você pode recuperar essas informações com o método de API GetClusterConfig.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
cipi
 a| 
Interface de rede utilizada para comunicação em cluster.
 a| 
corda



 a| 
conjunto
 a| 
Nome único do cluster.
 a| 
corda



 a| 
criptografiaCapaz
 a| 
Indica se o nó suporta criptografia de unidade.
 a| 
booleano



 a| 
conjunto
 a| 
Os nós que participam do cluster.
 a| 
matriz de strings



 a| 
fipsDriveConfiguration
 a| 
Indica se o nó suporta unidades com certificação FIPS 140-2.
 a| 
booleano



 a| 
mipi
 a| 
Interface de rede utilizada para gerenciamento de nós.
 a| 
corda



 a| 
nome
 a| 
O nome do cluster.
 a| 
corda



 a| 
ID do nó
 a| 
O ID do nó no cluster.
 a| 
corda



 a| 
ID do nó pendente
 a| 
O ID do nó pendente no cluster.
 a| 
inteiro



 a| 
papel
 a| 
Identifica a função do nó.
 a| 
inteiro



 a| 
sipi
 a| 
A interface de rede utilizada para o tráfego de armazenamento.
 a| 
corda



 a| 
estado
 a| 
O estado atual do nó. Valores possíveis:

* Disponível: O nó não foi configurado com um nome de cluster.
* Pendente: O nó está pendente para um cluster específico com nome e pode ser adicionado.
* Ativo: O nó é um membro ativo de um cluster e não pode ser adicionado a outro cluster.
* Pendente Ativo: O nó está sendo restaurado para a imagem de software de fábrica e ainda não é um membro ativo de um cluster.  Ao concluir, passará para o estado Ativo.

 a| 
corda



 a| 
versão
 a| 
A versão do software em execução no nó.
 a| 
corda

|===


== Modificabilidade dos membros e estados dos nós

Esta tabela indica se os parâmetros do objeto podem ou não ser modificados em cada estado possível do nó.

|===


| Nome do parâmetro | Estado disponível | Estado pendente | Estado ativo 


 a| 
cipi
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
conjunto
 a| 
Sim
 a| 
Sim
 a| 
Não



 a| 
criptografiaCapaz
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
conjunto
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
mipi
 a| 
Sim
 a| 
Sim
 a| 
Não



 a| 
nome
 a| 
Sim
 a| 
Sim
 a| 
Sim



 a| 
ID do nó
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
ID do nó pendente
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
papel
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
sipi
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
estado
 a| 
Não
 a| 
Não
 a| 
Não



 a| 
versão
 a| 
Não
 a| 
Não
 a| 
Não

|===


== Encontre mais informações

xref:reference_element_api_getclusterconfig.adoc[GetClusterConfig]
