---
permalink: api/reference_element_api_modifykeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,modifying,modify,change,edit 
summary: 'Você pode usar o método ModifyKeyServerKmip para modificar um servidor de chaves KMIP (Key Management Interoperability Protocol) existente para os atributos especificados.  Embora o único parâmetro obrigatório seja o keyServerID, uma solicitação contendo apenas o keyServerID não executará nenhuma ação e não retornará nenhum erro.  Quaisquer outros parâmetros que você especificar substituirão os valores existentes para o servidor de chaves pelo keyServerID especificado.  O servidor de chaves é contatado durante a operação para garantir que esteja funcionando corretamente.  É possível fornecer vários nomes de host ou endereços IP com o parâmetro kmipKeyServerHostnames, mas somente se os servidores de chaves estiverem em uma configuração em cluster.' 
---
= ModifyKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyKeyServerKmip` Método para modificar um servidor de chaves KMIP (Key Management Interoperability Protocol) existente para os atributos especificados.  Embora o único parâmetro obrigatório seja o keyServerID, uma solicitação contendo apenas o keyServerID não executará nenhuma ação e não retornará nenhum erro.  Quaisquer outros parâmetros que você especificar substituirão os valores existentes para o servidor de chaves pelo keyServerID especificado.  O servidor de chaves é contatado durante a operação para garantir que esteja funcionando corretamente.  É possível fornecer vários nomes de host ou endereços IP com o parâmetro kmipKeyServerHostnames, mas somente se os servidores de chaves estiverem em uma configuração em cluster.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do servidor de chaves
 a| 
O ID do servidor de chaves KMIP a ser modificado.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
kmipCaCertificado
 a| 
O certificado de chave pública da autoridade certificadora raiz do servidor de chaves externo.  Isso será usado para verificar o certificado apresentado pelo servidor de chaves externo na comunicação TLS.  Para clusters de servidores principais onde servidores individuais usam diferentes CAs, forneça uma string concatenada contendo os certificados raiz de todas as CAs.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
kmipClientCertificate
 a| 
Um certificado PKCS#10 X.509 codificado em Base64 no formato PEM, usado pelo cliente Solidfire KMIP.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
kmipKeyServerHostnames
 a| 
Matriz de nomes de host ou endereços IP associados a este servidor de chaves KMIP.  Só é necessário fornecer vários nomes de host ou endereços IP se os servidores principais estiverem em uma configuração de cluster.
 a| 
matriz de strings
 a| 
Nenhum
 a| 
Não



 a| 
kmipKeyServerName
 a| 
O nome do servidor de chaves KMIP.  Este nome é usado apenas para fins de exibição e não precisa ser único.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
kmipKeyServerPort
 a| 
O número da porta associada a este servidor de chaves KMIP (normalmente 5696).
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
kmipKeyServer
 a| 
Um objeto contendo detalhes sobre o servidor de chaves recém-modificado.
 a| 
link:reference_element_api_keyserverkmip.html["Servidor de chaves Kmip"]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ModifyKeyServerKmip",
  "params": {
    "keyServerID": 15
    "kmipCaCertificate": "CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "kirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"kirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Novidade desde a versão

11,7
