---
permalink: api/reference_element_api_clusterinfo.html 
sidebar: sidebar 
keywords: element, api, object, objects, clusterInfo 
summary: O objeto clusterInfo contém informações que o nó usa para se comunicar com o cluster.  Você pode obter essas informações com o método de API GetClusterInfo. 
---
= clusterInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto clusterInfo contém informações que o nó usa para se comunicar com o cluster.  Você pode obter essas informações com o método de API GetClusterInfo.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
atributos
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON



 a| 
esquema de proteção padrão
 a| 
O esquema de proteção usado por padrão para novos volumes, a menos que um esquema de proteção seja fornecido com o...xref:reference_element_api_createvolume.adoc[CriarVolume] chamada de método.  Este esquema de proteção deve sempre estar no conjunto de esquemas de proteção ativados.
 a| 
corda



 a| 
esquemas de proteção ativados
 a| 
Uma lista de todos os esquemas de proteção que foram ativados neste cluster de armazenamento.
 a| 
matriz de strings



 a| 
criptografiaEmRepouso
 a| 
O estado da funcionalidade de Criptografia em Repouso. Valores possíveis:

* Ativação: A criptografia em repouso está sendo ativada.
* Ativado: A criptografia em repouso está ativada.
* Desativação: A criptografia em repouso está sendo desativada.
* Desativado: A criptografia em repouso está desativada.

 a| 
corda



 a| 
conjunto
 a| 
Os nós que participam do cluster.
 a| 
matriz de strings



 a| 
mvip
 a| 
O endereço IP flutuante (virtual) do cluster na rede de gerenciamento.
 a| 
corda



 a| 
Interface mvip
 a| 
A interface física associada ao endereço MVIP.
 a| 
corda



 a| 
mvipNodeID
 a| 
O nó que detém o endereço MVIP mestre.
 a| 
inteiro



 a| 
mvipVlanTag
 a| 
O identificador VLAN para o endereço MVIP.
 a| 
corda



 a| 
nome
 a| 
O nome único do cluster.
 a| 
corda



 a| 
contagem de repetições
 a| 
O número de réplicas de cada conjunto de dados a serem armazenadas no cluster.  O valor válido é "2".
 a| 
inteiro



 a| 
criptografiadesoftwareemrepouso
 a| 
Criptografia de estado em repouso baseada em software.
 a| 
corda



 a| 
Esquemas de proteção suportados
 a| 
Lista de todos os esquemas de proteção suportados neste cluster de armazenamento.
 a| 
matriz de strings



 a| 
svip
 a| 
O endereço IP flutuante (virtual) do cluster na rede de armazenamento (iSCSI).
 a| 
corda



 a| 
Interface svip
 a| 
A interface física associada ao endereço SVIP principal.
 a| 
corda



 a| 
svipNodeID
 a| 
O nó que detém o endereço SVIP mestre.
 a| 
inteiro



 a| 
svipVlanTag
 a| 
O identificador VLAN para o endereço SVIP principal.
 a| 
corda



 a| 
ID único
 a| 
O ID exclusivo do cluster.
 a| 
corda



 a| 
uuid
 a| 
O identificador único do cluster.
 a| 
UUID



 a| 
volumeLoadBalanceOnActualIopsState
 a| 
O status do balanceamento de fatias é baseado no IOPS real, em vez do recurso de IOPS mínimo.  Disponível a partir do Elemento 12.8.
 a| 
corda

|===
[discrete]
== Encontre mais informações

* link:reference_element_api_getclusterinfo.html["Obter informações do cluster"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

