---
permalink: api/reference_element_api_deletekeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,deleting,delete 
summary: 'Você pode usar o método DeleteKeyProviderKmip para excluir o provedor de chaves KMIP (Key Management Interoperability Protocol) inativo especificado.' 
---
= DeleteKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteKeyProviderKmip` Método para excluir o provedor de chaves KMIP (Key Management Interoperability Protocol) inativo especificado.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do provedor de chave
 a| 
O ID do provedor de chaves a ser excluído.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.  A operação de exclusão é considerada bem-sucedida desde que não haja erros.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DeleteKeyProviderKmip",
  "params": {
    "keyProviderID": "1"
    },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Novidade desde a versão

11,7
