---
permalink: api/reference_element_api_getkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,retrieving,get,retrieve 
summary: 'Você pode usar o método GetKeyProviderKmip para recuperar informações sobre o provedor de chaves do Protocolo de Interoperabilidade de Gerenciamento de Chaves (KMIP) especificado.' 
---
= GetKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetKeyProviderKmip` Método para recuperar informações sobre o provedor de chaves do Protocolo de Interoperabilidade de Gerenciamento de Chaves (KMIP) especificado.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do provedor de chave
 a| 
O ID do objeto provedor de chaves KMIP a ser retornado.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
kmipKeyProvider
 a| 
Um objeto contendo detalhes sobre o provedor de chaves solicitado.
 a| 
link:reference_element_api_keyproviderkmip.html["Provedor de chave Kmip"]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetKeyProviderKmip",
  "params": {
    "keyProviderID": 15
    },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result":
    {
    "kmipKeyProvider": {
        "keyProviderID": 15,
        "kmipCapabilities": "SSL",
        "keyProviderIsActive": true,
        "keyServerIDs": [
            1
        ],
        "keyProviderName": "ProviderName"
    }
   }
}
----


== Novidade desde a versão

11,7
