---
permalink: api/reference_element_api_deletekeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,deleting,delete 
summary: 'Você pode usar o método DeleteKeyServerKmip para excluir um servidor de chaves KMIP (Key Management Interoperability Protocol) existente.  Você pode excluir um servidor de chaves, a menos que seja o último atribuído ao seu provedor e que esse provedor esteja fornecendo chaves que estejam atualmente em uso.' 
---
= DeleteKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteKeyServerKmip` Método para excluir um servidor de chaves KMIP (Key Management Interoperability Protocol) existente.  Você pode excluir um servidor de chaves, a menos que seja o último atribuído ao seu provedor e que esse provedor esteja fornecendo chaves que estejam atualmente em uso.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do servidor de chaves
 a| 
O ID do servidor de chaves KMIP a ser excluído.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não retorna valores.  A operação de exclusão é considerada bem-sucedida se não houver erros.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DeleteKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Novidade desde a versão

11,7
