---
permalink: api/reference_element_api_getontapversioninfo.html 
sidebar: sidebar 
keywords: ontap,version,info,information,get,getting,api,support,getontapversioninfo 
summary: A interface web do Element usa o GetOntapVersionInfo para obter informações sobre o suporte à versão da API do cluster ONTAP em um relacionamento SnapMirror . 
---
= Informações sobre a versão do GetOntap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do Element usa `GetOntapVersionInfo` Para obter informações sobre o suporte à versão da API do cluster ONTAP em um relacionamento SnapMirror .



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
snapMirrorEndpointID
 a| 
Se fornecido, o sistema lista as informações de versão do endpoint com o snapMirrorEndpointID especificado.  Caso não seja fornecida, o sistema lista as informações de versão de todos os endpoints SnapMirror conhecidos.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
ontapVersionInfo
 a| 
Informações sobre a versão do software do endpoint ONTAP .
 a| 
xref:reference_element_api_ontapversioninfo.adoc[ontapVersionInfo]variedade

|===


== Novidade desde a versão

10,1
