---
permalink: api/reference_element_api_modifyvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volumes,volume,defining,define,modify,modifying,edit,editing,change,changing,modifyvolumeaccessgrouplunassignments,access,group,lun,assignment 
summary: Você pode usar o método ModifyVolumeAccessGroupLunAssignments para definir atribuições de LUN personalizadas para volumes específicos. 
---
= Modificar atribuições de grupo de acesso a volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyVolumeAccessGroupLunAssignments` Método para definir atribuições LUN personalizadas para volumes específicos.

Este método altera apenas os valores de LUN definidos no parâmetro lunAssignments do grupo de acesso ao volume.  Todas as outras atribuições de LUN permanecem inalteradas.

Os valores de atribuição de LUN devem ser exclusivos para volumes em um grupo de acesso a volumes.  Não é possível definir valores LUN duplicados dentro de um grupo de acesso a volumes.  No entanto, você pode reutilizar os mesmos valores de LUN em diferentes grupos de acesso a volumes.


NOTE: Os valores válidos para LUN são de 0 a 16383.  O sistema gera uma exceção se você passar um valor LUN fora desse intervalo.  Nenhuma das atribuições de LUN especificadas será modificada se houver uma exceção.

CUIDADO:

Se você alterar a atribuição de um LUN para um volume com E/S ativa, a E/S poderá ser interrompida.  Você deve alterar a configuração do servidor antes de alterar as atribuições de LUN do volume.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do grupo de acesso ao volume
 a| 
ID exclusivo do grupo de acesso ao volume para o qual as atribuições de LUN serão modificadas.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
Tarefas de lun
 a| 
Os IDs de volume com novos valores LUN atribuídos.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volumeAccessGroupLunAssignments
 a| 
Um objeto contendo detalhes das atribuições de LUN do grupo de acesso a volume modificado.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ModifyVolumeAccessGroupLunAssignments",
   "params": {
       "volumeAccessGroupID" : 218,
       "lunAssignments" : [
           {"volumeID" : 832, "lun" : 0},
           {"volumeID" : 834, "lun" : 1}
        ]
    },
    "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroupLunAssignments": {
      "deletedLunAssignments": [],
      "lunAssignments": [
        {
          "lun": 0,
          "volumeID": 832
        },
        {
          "lun": 1,
          "volumeID": 834
        }
      ],
      "volumeAccessGroupID": 218
    }
  }
}
----


== Novidade desde a versão

9,6
