---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: Você pode usar o método ListVolumeStatsByVolumeAccessGroup para listar as medições de atividade total de todos os volumes que são membros dos grupos de acesso a volumes especificados. 
---
= ListVolumeStatsByVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumeStatsByVolumeAccessGroup` Método para listar as medições de atividade total para todos os volumes que são membros dos grupos de acesso a volumes especificados.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
incluirVolumesVirtuais
 a| 
Por padrão, os volumes virtuais são incluídos na resposta.  Para excluir volumes virtuais, defina como falso.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
gruposDeAcessoAoVolume
 a| 
Uma matriz de VolumeAccessGroupIDs para os quais a atividade de volume é retornada.  Caso seja omitido, serão retornadas as estatísticas para todos os grupos de acesso a volume.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
Estatísticas de volume
 a| 
Lista de informações de atividade de volume para todos os volumes no grupo de acesso a volumes especificado. *Observação:* O membro volumeID é 0 para cada entrada, pois os valores representam a soma de todos os volumes pertencentes à conta.
 a| 
xref:reference_element_api_volumestats.adoc[Estatísticas de volume]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
