---
permalink: api/reference_element_api_getnodesupportedtlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,supported,getnodesupportedtlsciphers 
summary: Você pode usar o método GetNodeSupportedTlsCiphers em um único nó para obter uma lista das cifras TLS que são atualmente suportadas nesse nó.  Você pode usar esse método em nós de gerenciamento e armazenamento. 
---
= Obter cifras TLS suportadas pelo nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNodeSupportedTlsCiphers` Método em um único nó para obter uma lista das cifras TLS que são atualmente suportadas nesse nó.  Você pode usar esse método em nós de gerenciamento e armazenamento.



== Parâmetro

Este método não possui parâmetros de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
Cifras obrigatórias
 a| 
Lista de conjuntos de cifras TLS obrigatórios para o nó.  Essas são cifras que estão sempre ativas no nó.
 a| 
corda



 a| 
Cifras suplementares padrão
 a| 
Lista de conjuntos de cifras TLS suplementares padrão para o nó.  Os algoritmos de criptografia suplementares são restaurados para esta lista quando você executa o método de API ResetNodeSupplementalTlsCiphers.
 a| 
corda



 a| 
cifras suplementares suportadas
 a| 
Lista de conjuntos de cifras TLS suplementares disponíveis que você pode configurar com o método de API SetNodeSupplementalTlsCiphers.
 a| 
corda

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetNodeSupportedTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1,
  "result" : {
	"defaultSupplementalCiphers": [
		"DHE-RSA-AES128-SHA256",
		"DHE-RSA-AES128-GCM-SHA256",
		"ECDHE-RSA-AES128-SHA256",
		"ECDHE-RSA-AES128-GCM-SHA256"
	],
	"mandatoryCiphers": [
		"DHE-RSA-AES256-SHA256",
		"DHE-RSA-AES256-GCM-SHA384",
		"ECDHE-RSA-AES256-SHA384",
		"ECDHE-RSA-AES256-GCM-SHA384"
	],
	"supportedSupplementalCiphers": [
		"DHE-RSA-AES128-SHA256",
		"DHE-RSA-AES128-GCM-SHA256",
		"ECDHE-RSA-AES128-SHA256",
		"ECDHE-RSA-AES128-GCM-SHA256",
		"DHE-RSA-AES256-SHA",
		"ECDHE-RSA-AES256-SHA",
		"DHE-RSA-CAMELLIA256-SHA",
		"DHE-RSA-AES128-SHA",
		"ECDHE-RSA-AES128-SHA",
		"DHE-RSA-CAMELLIA128-SHA"
	]
}
}
----