---
permalink: api/reference_element_api_createpublicprivatekeypair.html 
sidebar: sidebar 
keywords: SSL keys,public and private keys,certificate signing request,creating key pair 
summary: Você pode usar o método CreatePublicPrivateKeyPair para criar chaves SSL públicas e privadas.  Você pode usar essas chaves para gerar solicitações de assinatura de certificado.  Só pode haver um par de chaves em uso para cada cluster de armazenamento.  Antes de usar este método para substituir chaves existentes, certifique-se de que as chaves não estejam mais em uso por nenhum provedor. 
---
= CriarParDeChavesPúblicasPrivadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CreatePublicPrivateKeyPair` Método para criar chaves SSL públicas e privadas.  Você pode usar essas chaves para gerar solicitações de assinatura de certificado.  Só pode haver um par de chaves em uso para cada cluster de armazenamento.  Antes de usar este método para substituir chaves existentes, certifique-se de que as chaves não estejam mais em uso por nenhum provedor.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome comum
 a| 
O campo *Nome Comum* (CN) do nome distinto X.509.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
país
 a| 
O campo de nome distinto X.509 *País* (C).
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
endereço de email
 a| 
O campo de nome distinto X.509 *Endereço de e-mail* (MAIL).
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
localidade
 a| 
O campo *Nome da Localidade* do nome distinto X.509 (L).
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
organização
 a| 
O campo de nome distinto X.509 *Nome da Organização* (O).
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
Unidade organizacional
 a| 
O campo *Nome da Unidade Organizacional* (OU) do nome distinto X.509.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
estado
 a| 
O campo *Estado* ou *Nome da Província* do nome distinto X.509 (ST, SP ou S).
 a| 
corda
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método não possui valores de retorno.  Se não houver erros, a criação da chave é considerada bem-sucedida.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "CreatePublicPrivateKeyPair",
  "params": {
    "commonName": "Name",
    "country": "US",
    "emailAddress" : "email@domain.com"
   },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Novidade desde a versão

11,7
