---
permalink: api/reference_element_api_listvolumestats.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,listvolumestats,activity 
summary: 'Você pode usar o método ListVolumeStats para obter medições de atividade de alto nível para um único volume, uma lista de volumes ou todos os volumes (se omitir o parâmetro volumeIDs).  Os valores de medição são cumulativos desde a criação do volume.' 
---
= ListVolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumeStats` Método para obter medições de atividade de alto nível para um único volume, uma lista de volumes ou todos os volumes (se você omitir o parâmetro volumeIDs).  Os valores de medição são cumulativos desde a criação do volume.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
incluirVolumesVirtuais
 a| 
Por padrão, os volumes virtuais são incluídos na resposta.  Para excluir volumes virtuais, defina como falso.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
IDs de volume
 a| 
Uma lista de volumes dos quais se podem obter informações sobre atividades.
 a| 
matriz de inteiros
 a| 
Não
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
Estatísticas de volume
 a| 
Lista de informações sobre atividade de volume.
 a| 
xref:reference_element_api_volumestats.adoc[Estatísticas de volume]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVolumeStats",
    "params": {
        "volumeIDs": [1]
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 1,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 0,
        "burstIOPSCredit": 30000,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            47
          ],
          "primary": 33
        },
        "nonZeroBlocks": 22080699,
        "readBytes": 657262370816,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 160464446,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-03-09T19:39:15.771697Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
          1
        ],
        "volumeID": 1,
        "volumeSize": 107374182400,
        "volumeUtilization": 0,
        "writeBytes": 219117547520,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 53495495,
        "writeOpsLastSample": 0,
        "zeroBlocks": 4133701
      }
    ]
  }
}
----


== Novidade desde a versão

9,6
