---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: Você pode usar o método SetNodeSupplementalTlsCiphers para especificar a lista de cifras TLS suplementares.  Você pode usar este comando em nós de gerenciamento. 
---
= SetNodeSupplementalTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetNodeSupplementalTlsCiphers` Método para especificar a lista de cifras TLS suplementares.  Você pode usar este comando em nós de gerenciamento.



== Parâmetro


NOTE: Você deve chamar esse método no nó de gerenciamento. Por exemplo:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
Cifras suplementares
 a| 
Os nomes dos conjuntos de cifras suplementares usam o esquema de nomenclatura OpenSSL.  O uso de nomes de conjuntos de cifras não diferencia maiúsculas de minúsculas.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
Cifras obrigatórias
 a| 
Lista de conjuntos de cifras TLS obrigatórios para o nó.  Essas são cifras que estão sempre ativas no nó.
 a| 
corda



 a| 
Cifras suplementares
 a| 
Lista de conjuntos de cifras TLS suplementares para o nó.
 a| 
corda

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----