---
permalink: api/reference_element_api_removevirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,networks,remove,removing,removevirtualnetwork 
summary: Você pode usar o método RemoveVirtualNetwork para remover uma rede virtual adicionada anteriormente. 
---
= RemoverRedeVirtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `RemoveVirtualNetwork` Método para remover uma rede virtual adicionada anteriormente.


NOTE: Este método requer o virtualNetworkID ou o virtualNetworkTag como parâmetro, mas não ambos.


NOTE: Não é possível remover uma rede virtual se houver iniciadores associados a ela.  Primeiro, desassocie os iniciadores e, em seguida, remova a rede virtual.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID de rede virtual
 a| 
ID da rede que identifica a rede virtual a ser removida.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
virtualNetworkTag
 a| 
Etiqueta de rede que identifica a rede virtual a ser removida.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "RemoveVirtualNetwork",
  "params": {
     "virtualNetworkID": 5
    }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result": {}
}
----


== Novidade desde a versão

9,6
