---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: Você pode usar o método TestPing para testar a conectividade de rede com todos os nós do cluster, tanto nas interfaces de 1G quanto nas de 10G, usando pacotes ICMP.  O teste utiliza os tamanhos de MTU apropriados para cada pacote, com base nas configurações de MTU na configuração de rede.  O TestPing não cria uma interface VLAN temporária. 
---
= TestPing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `TestPing` Método para testar a conectividade de rede em todos os nós do cluster, tanto nas interfaces de 1G quanto de 10G, utilizando pacotes ICMP.  O teste utiliza os tamanhos de MTU apropriados para cada pacote, com base nas configurações de MTU na configuração de rede. `TestPing` Não cria uma interface VLAN temporária.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
tentativas
 a| 
Especifica o número de vezes que o sistema deve repetir o ping de teste.
 a| 
inteiro
 a| 
5
 a| 
Não



 a| 
anfitriões
 a| 
Especifica uma lista de endereços ou nomes de host de dispositivos a serem pingados, separados por vírgulas.  Se nenhum host for especificado, o método enviará um ping para os hosts no cluster de armazenamento.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
interface
 a| 
A interface existente (base) a partir da qual os pings devem ser enviados. Valores possíveis:

* `Bond10G`Enviar pings a partir da interface Bond10G.
* `Bond1G`Enviar pings a partir da interface Bond1G.

 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
tamanho do pacote
 a| 
Especifica o número de bytes a serem enviados no pacote ICMP que é enviado para cada endereço IP.  O número de bytes deve ser menor que o MTU máximo especificado na configuração de rede.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não



 a| 
pingTimeoutMsec
 a| 
Especifica o número de milissegundos a aguardar por cada resposta de ping individual.
 a| 
inteiro
 a| 
500 milissegundos
 a| 
Não



 a| 
proibir a fragmentação
 a| 
Habilita o sinalizador DF (Não Fragmentar) para pacotes ICMP.
 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
sourceAddressV4
 a| 
O endereço IPv4 de origem a ser usado nos pacotes ICMP ping.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
sourceAddressV6
 a| 
O endereço IPv6 de origem a ser usado nos pacotes ICMP ping.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
tempo limite total em segundos
 a| 
Especifica o tempo, em segundos, que o ping deve aguardar uma resposta do sistema antes de emitir a próxima tentativa de ping ou encerrar o processo.
 a| 
inteiro
 a| 
5
 a| 
Não



 a| 
virtualNetworkTag
 a| 
O ID da VLAN a ser usado ao enviar os pacotes ping.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
detalhes
 a| 
Lista de cada endereço IP com o qual o nó conseguiu se comunicar e estatísticas de resposta do ping.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== Novidade desde a versão

5,0
