---
permalink: api/reference_element_api_setloginbanner.html 
sidebar: sidebar 
keywords: terms,use,banner,configure,set,setting,setloginbanner,login 
summary: Você pode usar o método SetLoginBanner para configurar o banner de Termos de Uso que os usuários veem ao fazer login na interface web do Element. 
---
= Definir banner de login
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetLoginBanner` Método para configurar o banner de Termos de Uso que os usuários veem ao fazer login na interface web do Element.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
bandeira
 a| 
O texto desejado para o banner dos Termos de Uso.  O comprimento máximo permitido é de 4.096 caracteres.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
habilitado
 a| 
O status do banner dos Termos de Uso. Valores possíveis:

* `true`O banner com os Termos de Uso é exibido ao fazer login na interface web.
* `false`O aviso de Termos de Uso não é exibido ao fazer login na interface web.

 a| 
booleano
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
bandeira
 a| 
Texto atual do banner dos Termos de Uso.  Esse valor pode conter texto mesmo quando o banner estiver desativado.
 a| 
corda



 a| 
habilitado
 a| 
O status do banner dos Termos de Uso. Valores possíveis:

* Verdadeiro: O banner dos Termos de Uso é exibido ao fazer login na interface web.
* falso: O banner dos Termos de Uso não é exibido ao fazer login na interface web.

 a| 
booleano

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 3920,
  "method": "SetLoginBanner",
  "params": {
    "banner": "Welcome to NetApp!",
    "enabled": true
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 3920,
  "result": {
    "loginBanner": {
      "banner": "Welcome to NetApp!",
      "enabled": true
    }
  }
}
----


== Novidade desde a versão

10,0
