---
permalink: api/reference_element_api_quiescesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,quiesce,quiescing,quiescescnapmirrorrelationship 
summary: 'A interface web do software Element utiliza o método QuiesceSnapMirrorRelationship para desativar futuras transferências de dados para um relacionamento SnapMirror .  Se uma transferência estiver em andamento, o status do relacionamento passa a ser "em repouso" até que a transferência seja concluída.  Se a transferência atual for interrompida, ela não será reiniciada.  Você pode reativar as transferências de dados para o relacionamento usando o método da API ResumeSnapMirrorRelationship.' 
---
= QuiesceSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do software Element utiliza o `QuiesceSnapMirrorRelationship` Método para desativar futuras transferências de dados para um relacionamento SnapMirror .  Se uma transferência estiver em andamento, o status do relacionamento passa a ser "em repouso" até que a transferência seja concluída.  Se a transferência atual for interrompida, ela não será reiniciada.  Você pode reativar as transferências de dados para o relacionamento usando o `ResumeSnapMirrorRelationship` Método da API.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
snapMirrorEndpointID
 a| 
O ID do ponto de extremidade do sistema de armazenamento ONTAP remoto que se comunica com o cluster de armazenamento Element.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
volume de destino
 a| 
O volume de destino no relacionamento SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
snapMirrorRelationship
 a| 
Um objeto contendo informações sobre o relacionamento SnapMirror inativo.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Novidade desde a versão

10,1
