---
permalink: api/reference_element_api_modifyclusteradmin.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,cluster,admin,settings,modifyclusteradmin 
summary: 'Você pode usar o método ModifyClusterAdmin para alterar as configurações de um administrador de cluster, administrador de cluster LDAP ou administrador de cluster de um provedor de identidade (IdP) de terceiros.  Não é possível alterar o acesso da conta de administrador do cluster.' 
---
= ModificarAdministradorDeCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyClusterAdmin` Método para alterar as configurações de um administrador de cluster, administrador de cluster LDAP ou administrador de cluster de um provedor de identidade (IdP) de terceiros.  Não é possível alterar o acesso da conta de administrador do cluster.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
acesso
 a| 
Controla quais métodos este administrador de cluster pode usar.
 a| 
matriz de strings
 a| 
Nenhum
 a| 
Não



 a| 
atributos
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
ID do administrador do cluster
 a| 
ClusterAdminID para o administrador do cluster, administrador do cluster LDAP ou administrador do cluster IdP modificar.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
senha
 a| 
Senha usada para autenticar este administrador de cluster.  Este parâmetro não se aplica a um administrador de cluster LDAP ou IdP.
 a| 
corda
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ModifyClusterAdmin",
   "params": {
     "clusterAdminID"  : 2,
     "password"   : "7925Brc429a"
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
 "id" : 1
 "result" : { }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_app_b_access_control.adoc[Controle de acesso]
