---
permalink: api/reference_element_api_createclustersupportbundle.html 
sidebar: sidebar 
keywords: CreateClusterSupportBundle,create,cluster,support,bundle,creating 
summary: Você pode usar o CreateClusterSupportBundle no nó de gerenciamento para reunir pacotes de suporte de todos os nós em um cluster.  Quando um pacote é criado, ele é armazenado no nó como um arquivo .tar.gz.  Você só pode executar esse método em um nó de gerenciamento; ele não funciona quando executado em um nó de armazenamento. 
---
= CriarPacote de Suporte de Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CreateClusterSupportBundle` no nó de gerenciamento para coletar pacotes de suporte de todos os nós em um cluster.  Os pacotes de suporte de nós individuais são compactados em arquivos tar.gz.  O pacote de suporte do cluster é um arquivo tar que contém os pacotes de suporte dos nós.  Você só pode executar esse método em um nó de gerenciamento; ele não funciona quando executado em um nó de armazenamento.



== Parâmetros


NOTE: Você deve chamar esse método no nó de gerenciamento. Por exemplo:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
permitirIncompleto
 a| 
Permite que o script continue a ser executado caso não seja possível coletar pacotes de um ou mais nós.
 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
nome do pacote
 a| 
Nome único para cada pacote de suporte criado.  Se nenhum nome for fornecido, "supportbundle" e o nome do nó serão usados como nome do arquivo.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
mvip
 a| 
O MVIP do cluster.  Os pacotes são coletados de todos os nós do cluster.  Este parâmetro é obrigatório caso o parâmetro `nodes` não seja especificado.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
nós
 a| 
Os endereços IP dos nós dos quais os pacotes serão coletados.  Use `nodes` ou `mvip`, mas não ambos, para especificar os nós dos quais coletar os pacotes.  Este parâmetro é obrigatório caso mvip não seja especificado.
 a| 
matriz de strings
 a| 
Nenhum
 a| 
Sim



 a| 
senha
 a| 
A senha de administrador do cluster.  *Nota:* Esta senha será exibida como texto ao ser digitada.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
nome de usuário
 a| 
O nome de usuário administrador do cluster.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method": "CreateClusterSupportBundle",
"params": {
          "bundlename": "clusterbundle",
          "mvip": "132.119.120.100"
     }
   },
 "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id":1,
  "result":{
   "details":{
      "bundleName":"clusterbundle",
      "extraArgs":"",
      "files":[
          "/tmp/supportbundles/clusterbundle.cl-4SD5.tar"
      ],
      "output":"timeout -s KILL 1790s /usr/local/bin/sfclustersupportbundle --quiet --name=\"clusterbundle\" --target-directory=\"/tmp/solidfire-dtemp.MM7f0m\" --user=\"admin\" --pass=\"admin\" --mvip=132.119.120.100"
       },
       "duration":"00:00:24.938127",
       "result":"Passed"
    }
}
----


== Novidade desde a versão

9,6
