---
permalink: api/reference_element_api_startclusterpairing.html 
sidebar: sidebar 
keywords: cluster,pair,pairing,start,starting,startclusterpairing 
summary: Você pode usar o método StartClusterPairing para criar uma chave codificada a partir de um cluster que será usada para emparelhar com outro cluster.  A chave criada por meio desse método da API é usada no método CompleteClusterPairing para estabelecer um emparelhamento de clusters.  Você pode emparelhar um cluster com, no máximo, quatro outros clusters. 
---
= IniciarEmparelhamentoDeClusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `StartClusterPairing` Método para criar uma chave codificada a partir de um cluster que é usada para emparelhar com outro cluster.  A chave criada por este método da API é usada em `CompleteClusterPairing` Método para estabelecer um emparelhamento de clusters.  Você pode emparelhar um cluster com, no máximo, quatro outros clusters.



== Parâmetro

Este método não possui parâmetro de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
chave de emparelhamento de cluster
 a| 
Uma sequência de caracteres que é usada peloxref:reference_element_api_completeclusterpairing.adoc[Emparelhamento de cluster completo] Método da API.
 a| 
corda



 a| 
clusterPairID
 a| 
Identificador único para o par de clusters.
 a| 
inteiro

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "StartClusterPairing",
   "params": {
      },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result": {
     "clusterPairID": 1,
     "clusterPairingKey": "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
   }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_completeclusterpairing.adoc[Emparelhamento de cluster completo]
