---
permalink: api/reference_element_api_setloginsessioninfo.html 
sidebar: sidebar 
keywords: authentication,login,session,info,timeout,setloginsessioninfo 
summary: Você pode usar o método SetLoginSessionInfo para definir o período de tempo durante o qual a autenticação de login de uma sessão é válida.  Após o período de login decorrido sem atividade no sistema, a autenticação expira.  Novas credenciais de login são necessárias para continuar acessando o cluster após o período de login ter expirado. 
---
= SetLoginSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetLoginSessionInfo` Método para definir o período de tempo durante o qual a autenticação de login de uma sessão é válida.  Após o período de login decorrido sem atividade no sistema, a autenticação expira.  Novas credenciais de login são necessárias para continuar acessando o cluster após o período de login ter expirado.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
tempo esgotado
 a| 
Período de expiração da autenticação do cluster.  Formatado em HH:mm:ss.  Por exemplo: 01:30:00, 00:90:00 e 00:00:5400 podem ser usados para totalizar um período de tempo limite de 90 minutos.  O valor mínimo de tempo limite é de 1 minuto.  Quando nenhum valor é fornecido, ou é definido como zero, a sessão de login não possui um valor de tempo limite.
 a| 
corda
 a| 
30 minutos
 a| 
Não

|===


== Valor de retorno

Este método não possui valor de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "SetLoginSessionInfo",
  "params": {
    "timeout" : "01:30:00"
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Novidade desde a versão

9,6
