---
permalink: api/reference_element_api_completevolumepairing.html 
sidebar: sidebar 
keywords: volume,pairing,CompleteVolumePairing,pair,volumes,complete,completing 
summary: Você pode usar o CompleteVolumePairing para concluir o emparelhamento de dois volumes. 
---
= Emparelhamento de Volume Completo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `CompleteVolumePairing` para completar o emparelhamento dos dois volumes.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do volume
 a| 
O ID do volume que completará o par de volumes.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
tecla de emparelhamento de volume
 a| 
A chave foi devolvida doxref:reference_element_api_startvolumepairing.adoc[IniciarEmparelhamentoDeVolumes] Método da API.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "CompleteVolumePairing",
   "params": {
        "volumeID" : 12,
        "volumePairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
        },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
"id": 1,
"result": {}
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_startvolumepairing.adoc[IniciarEmparelhamentoDeVolumes]
