---
permalink: api/reference_element_api_modifyaccount.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,accounts,settings,modifyaccount 
summary: Você pode usar o método ModifyAccount para modificar uma conta existente. 
---
= ModificarConta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyAccount` Método para modificar uma conta existente.

Ao bloquear uma conta, todas as conexões existentes dessa conta são encerradas imediatamente.  Ao alterar as configurações CHAP de uma conta, as conexões existentes permanecem ativas e as novas configurações CHAP são usadas em conexões ou reconexões subsequentes.  Para limpar os atributos de uma conta, especifique {} para o parâmetro de atributos.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID da conta
 a| 
ID da conta a ser modificada.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
atributos
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
ativarCap
 a| 
Especifica se as credenciais da conta CHAP podem ser usadas por um iniciador para acessar volumes.
 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
iniciadorSecreto
 a| 
O segredo CHAP a ser usado pelo iniciador.  Este segredo deve ter entre 12 e 16 caracteres e ser impenetrável.  O segredo CHAP do iniciador deve ser único e não pode ser o mesmo que o segredo CHAP do alvo.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
status
 a| 
Status da conta. Valores possíveis:

* Ativo: A conta está ativa e as conexões são permitidas.
* Bloqueado: A conta está bloqueada e as conexões foram recusadas.

 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
alvoSecreto
 a| 
O segredo CHAP a ser usado para o alvo (autenticação CHAP mútua).  Este segredo deve ter entre 12 e 16 caracteres e ser impenetrável.  O segredo CHAP de destino deve ser único e não pode ser o mesmo que o segredo CHAP de origem.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
nome de usuário
 a| 
Utilizado para alterar o nome de usuário associado à conta.  (Deve ter entre 1 e 64 caracteres).
 a| 
corda
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
conta
 a| 
Um objeto contendo informações sobre a conta modificada.
 a| 
xref:reference_element_api_account.adoc[conta]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao exemplo a seguir.  Neste exemplo, os atributos são limpos especificando {} para eles:

[listing]
----
{
   "method": "ModifyAccount",
   "params": {
     "accountID"  : 25,
     "status"   : "locked",
     "attributes" : {}
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "account": {
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "username": "user1",
        "accountID": 1,
        "volumes": [
        ],
        "enableChap": true,
        "initiatorSecret": "txz123456q890",
        "attributes": {
        },
        "status": active",
        "targetSecret": "rxe123b567890"
    }
}
----


== Novidade desde a versão

9,6
