---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: Você pode usar ListSnapshots para retornar os atributos de cada snapshot tirado no volume. 
---
= Instantâneos da lista
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `ListSnapshots` para retornar os atributos de cada instantâneo tirado no volume.

As informações sobre os snapshots que residem no cluster de destino serão exibidas no cluster de origem quando este método for chamado a partir do cluster de origem.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do volume
 a| 
Recupera instantâneos de um volume.  Caso o ID do volume não seja fornecido, todos os snapshots de todos os volumes serão retornados.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não



 a| 
ID do instantâneo
 a| 
Recupera informações para um ID de instantâneo individual.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
instantâneos
 a| 
Informações sobre cada instantâneo de cada volume.  Caso o ID do volume não seja fornecido, todos os snapshots de todos os volumes serão retornados.  As capturas de tela que pertencem a um grupo são retornadas com um ID de grupo.
 a| 
xref:reference_element_api_snapshot.adoc[instantâneo]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Novidade desde a versão

9,6
