---
permalink: api/reference_element_api_cluster_pairing_order_of_operations.html 
sidebar: sidebar 
keywords: cluster,pairing,pair,order,operations,clusters 
summary: É necessário estabelecer uma conexão entre um par de clusters de armazenamento que executam o software Element antes que a replicação remota possa ser utilizada. 
---
= ordem de operações de emparelhamento de clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É necessário estabelecer uma conexão entre um par de clusters de armazenamento que executam o software Element antes que a replicação remota possa ser utilizada.

Utilize o seguinte conjunto de métodos da API para estabelecer uma conexão de cluster:

* xref:reference_element_api_startclusterpairing.adoc[IniciarEmparelhamentoDeClusters]:
+
Este método da API cria e retorna uma chave de emparelhamento que é usada para estabelecer um par de clusters.  A chave é codificada e contém informações utilizadas para estabelecer comunicação entre clusters.  Um único cluster pode ser emparelhado com até quatro outros clusters.  No entanto, uma nova chave deve ser gerada para cada par de clusters.  Oxref:reference_element_api_startclusterpairing.adoc[IniciarEmparelhamentoDeClusters] O método gera uma nova chave cada vez que é chamado.  Use cada chave exclusiva com oxref:reference_element_api_completeclusterpairing.adoc[Emparelhamento de cluster completo] Método para emparelhar cada cluster adicional.

+

NOTE: Por motivos de segurança, a chave de emparelhamento não deve ser enviada a outros usuários por e-mail.  A chave contém um nome de usuário e uma senha.

* xref:reference_element_api_completeclusterpairing.adoc[Emparelhamento de cluster completo]:
+
Este método utiliza a chave de emparelhamento criada com oxref:reference_element_api_startclusterpairing.adoc[IniciarEmparelhamentoDeClusters] Método da API para criar um par de clusters.  Emita oxref:reference_element_api_completeclusterpairing.adoc[Emparelhamento de cluster completo] Método da API com o parâmetro clusterPairingKey para o destino.  O cluster de origem é o cluster que criou a chave.





== Encontre mais informações

* xref:reference_element_api_startclusterpairing.adoc[IniciarEmparelhamentoDeClusters]
* xref:reference_element_api_completeclusterpairing.adoc[Emparelhamento de cluster completo]

