---
permalink: api/reference_element_api_testremoteconnectivity.html 
sidebar: sidebar 
keywords: remote,connectivity,test,testing,testremoteconnectivity 
summary: Você pode usar o método TestRemoteConnectivity para enviar um ping para cada nó do cluster remoto e verificar a conexão remota do banco de dados do conjunto.  Para que este método retorne resultados úteis, os clusters devem ser emparelhados.  Caso a conexão com o banco de dados remoto falhe, a resposta do sistema listará as exceções. 
---
= TestarConectividadeRemota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `TestRemoteConnectivity` Método para pingar cada nó do cluster remoto e verificar a conexão remota do banco de dados do conjunto.  Para que este método retorne resultados úteis, os clusters devem ser emparelhados.  Caso a conexão com o banco de dados remoto falhe, a resposta do sistema listará as exceções.



== Parâmetros

Este método não possui parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
detalhes
 a| 
Tempos de resposta de ping individuais para cada nó.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "TestRemoteConnectivity",
    "params": {
      "force": "true"
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": null,
  "result": {
    "details": {
      "1": {
        "details": {
          "10.26.86.17": {
            "individualResponseTimes": [
              "00:00:00.006868",
              "00:00:00.005933",
              "00:00:00.006655",
              "00:00:00.006584",
              "00:00:00.006334"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006475",
            "successful": true
          },
          "10.26.86.18": {
            "individualResponseTimes": [
              "00:00:00.006201",
              "00:00:00.006187",
              "00:00:00.005990",
              "00:00:00.006029",
              "00:00:00.005917"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006065",
            "successful": true
          },
          "10.26.86.19": {
            "individualResponseTimes": [
              "00:00:00.005988",
              "00:00:00.006948",
              "00:00:00.005981",
              "00:00:00.005964",
              "00:00:00.005942"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006165",
            "successful": true,
          },
          "10.26.86.20": {
            "individualResponseTimes": [
              "00:00:00.005926",
              "00:00:00.006072",
              "00:00:00.005675",
              "00:00:00.009904",
              "00:00:00.006225"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006760",
            "successful": true
          }
        },
          "successful": true
      }
    },
  "duration": "00:00:00.595982",
  "result": "Passed"
  }
}
----


== Novidade desde a versão

9,6
