---
permalink: api/reference_element_api_clusterconfig.html 
sidebar: sidebar 
keywords: objects,object,clusterConfig 
summary: O objeto clusterConfig retorna informações que o nó usa para se comunicar com o cluster. 
---
= clusterConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `clusterConfig` O objeto retorna informações que o nó usa para se comunicar com o cluster.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
`cipi`
 a| 
Interface de rede utilizada para comunicação em cluster.
 a| 
corda



 a| 
`cluster`
 a| 
Nome único do cluster.
 a| 
corda



 a| 
`encryptionCapable`
 a| 
Especifica se o nó suporta criptografia.
 a| 
booleano



 a| 
`ensemble`
 a| 
Nós que participam do cluster.
 a| 
matriz de strings



 a| 
`fipsDriveConfiguration`
 a| 
Especifica se o nó suporta unidades com certificação FIPS 140-2.
 a| 
booleano



 a| 
`hasLocalAdmin`
 a| 
Especifica se o cluster possui um administrador local.
 a| 
booleano



 a| 
`mipi`
 a| 
Interface de rede utilizada para gerenciamento de nós.
 a| 
corda



 a| 
`name`
 a| 
Identificador único para o cluster.
 a| 
corda



 a| 
`nodeID`
 a| 
Identificador único para o nó.
 a| 
inteiro



 a| 
`pendingNodeID`
 a| 
Identificador único para o nó pendente.
 a| 
inteiro



 a| 
`role`
 a| 
Identifica a função do nó.
 a| 
corda



 a| 
`sipi`
 a| 
Interface de rede utilizada para armazenamento.
 a| 
corda



 a| 
`state`
 a| 
Indica o estado do nó.
 a| 
corda



 a| 
`version`
 a| 
Indica a versão do nó.
 a| 
corda

|===