---
permalink: api/reference_element_api_getprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,retrieve protection domains 
summary: Você pode usar o método GetProtectionDomainLayout para retornar todas as informações do domínio de proteção de um cluster, incluindo o chassi e o domínio de proteção personalizado em que cada nó está localizado. 
---
= Layout do domínio de proteção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetProtectionDomainLayout` Método para retornar todas as informações do domínio de proteção de um cluster, incluindo o chassi e o domínio de proteção personalizado em que cada nó está localizado.



== Parâmetro

Este método não possui parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
layoutDoDomínioDeProteção
 a| 
Lista de nós, cada um com seus respectivos domínios de proteção.
 a| 
lista JSON delink:reference_element_api_nodeprotectiondomains.html["domíniosDeProteçãoDeNó"] objetos.

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetProtectionDomainLayout",
  "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Novidade desde a versão

12,0
