---
permalink: api/reference_element_api_modifysnapmirrorrelationship.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,relationship,modifysnapmirrorrelationship 
summary: Você pode usar o ModifySnapMirrorRelationship para alterar os intervalos em que um snapshot agendado ocorre.  Você também pode excluir ou pausar um agendamento usando este método. 
---
= ModificarRelaçãoSnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `ModifySnapMirrorRelationship` Alterar os intervalos em que ocorre um instantâneo agendado.  Você também pode excluir ou pausar um agendamento usando este método.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
volume de destino
 a| 
O volume de destino no relacionamento SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Nenhum
 a| 
Sim



 a| 
taxa de transferência máxima
 a| 
Especifica a taxa máxima de transferência de dados entre os volumes em kilobytes por segundo.  O valor padrão, 0, é ilimitado e permite que a relação SnapMirror utilize totalmente a largura de banda de rede disponível.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não



 a| 
nomeDaPolítica
 a| 
Especifica o nome da política ONTAP SnapMirror para o relacionamento.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
nomeDoAgenda
 a| 
O nome da tarefa cron preexistente no sistema ONTAP que é usada para atualizar o relacionamento SnapMirror .
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
snapMirrorEndpointID
 a| 
O ID do ponto de extremidade do sistema de armazenamento ONTAP remoto que se comunica com o cluster de armazenamento Element.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
snapMirrorRelationship
 a| 
Um objeto contendo os atributos modificados do relacionamento SnapMirror .
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Novidade desde a versão

10,1
