---
permalink: api/reference_element_api_checkproposednodeadditions.html 
sidebar: sidebar 
keywords: proposed,node,additions,CheckProposedNodeAdditions,storage,checking 
summary: Você pode usar o método CheckProposedNodeAdditions para testar um conjunto de nós de armazenamento e verificar se é possível adicioná-los a um cluster de armazenamento sem erros ou violações das melhores práticas. 
---
= Verificar adições de nós propostas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CheckProposedNodeAdditions` Método para testar um conjunto de nós de armazenamento para verificar se é possível adicioná-los a um cluster de armazenamento sem erros ou violações das melhores práticas.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nós
 a| 
Uma lista de endereços IP de nós de armazenamento que estão prontos para serem adicionados a um cluster de armazenamento.
 a| 
matriz de strings
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
cluster proposto válido
 a| 
Indica se os nós de armazenamento propostos formariam ou não um cluster de armazenamento válido. Valores possíveis:

* verdadeiro
* falso

 a| 
booleano



 a| 
erros de cluster propostos
 a| 
Erros que ocorreriam se um cluster de armazenamento fosse criado usando os nós de armazenamento propostos.  Possíveis códigos de erro:

* `nodesNoCapacity`Os nós não possuíam capacidade utilizável.
* `nodesTooLarge`Os nós representam uma parcela excessiva da capacidade do cluster para o esquema de proteção ativa.
* `nodesConnectFailed`Não foi possível conectar-se aos nós para consultar a configuração de hardware.
* `nodesQueryFailed`Não foi possível consultar os nós para obter a configuração de hardware.
* `nodesClusterMember`Os endereços IP dos nós já estão em uso no cluster.
* `nonFipsNodeCapable`Não é possível adicionar um nó não compatível com FIPS ao cluster de armazenamento enquanto o recurso de criptografia de unidade FIPS 140-2 estiver ativado.
* `nonFipsDrivesCapable`Não é possível adicionar um nó com unidades não compatíveis com FIPS ao cluster enquanto o recurso de criptografia de unidade FIPS 140-2 estiver ativado.

 a| 
matriz de strings

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "CheckProposedNodeAdditions",
	"params": {
	"nodes": [
		"192.168.1.11",
		"192.168.1.12",
		"192.168.1.13",
		"192.168.1.14"
	]
},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
	"id": 1,
	"result": {
		"proposedClusterValid": true,
		"proposedClusterErrors": [ ]
	}
}
----


== Novidade desde a versão

11,0
