---
permalink: api/reference_element_api_getbackuptarget.html 
sidebar: sidebar 
keywords: backup,target,targets,get,getting,GetBackupTarget 
summary: Você pode usar o método GetBackupTarget para retornar informações sobre um destino de backup específico que você criou. 
---
= ObterAlvoDeBackup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetBackupTarget` Método para retornar informações sobre um destino de backup específico que você criou.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
atributos
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
backupTargetID
 a| 
Identificador único atribuído ao destino do backup.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
nome
 a| 
Nome do destino do backup.
 a| 
corda
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
destino de backup
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "method": "GetBackupTarget",
  "params": {
      "backupTargetID": 1
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result": {
     "backupTarget": {
     "attributes" : {
        "size" : 100
     },
     "backupTargetID" : 1,
     "name" : "mytargetbackup"
    }
  }
}
----


== Novidade desde a versão

9,6
