---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: Você pode usar o método ListVolumes para obter uma lista dos volumes que estão em um cluster.  Você pode especificar os volumes que deseja retornar na lista usando os parâmetros disponíveis. 
---
= Lista de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumes` Método para obter uma lista dos volumes que estão em um cluster.  Você pode especificar os volumes que deseja retornar na lista usando os parâmetros disponíveis.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
contas
 a| 
Somente os volumes pertencentes às contas que você especificar aqui serão retornados.  Exclusivo e mutuamente exclusivo do parâmetro volumeIDs.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Não



 a| 
incluirVolumesVirtuais
 a| 
Por padrão, os volumes virtuais são incluídos na resposta.  Para excluir volumes virtuais, defina como falso.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
está emparelhado
 a| 
Retorna volumes que estão emparelhados ou não emparelhados. Valores possíveis:

* verdadeiro: Retorna todos os volumes emparelhados.
* falso: Retorna todos os volumes não emparelhados.

 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
limite
 a| 
Permite definir o número máximo de resultados de volume que serão retornados.  Exclusivo e mutuamente exclusivo do parâmetro volumeIDs.
 a| 
inteiro
 a| 
10000
 a| 
Não



 a| 
startVolumeID
 a| 
Somente os volumes com um ID maior ou igual a esse valor serão retornados.  Exclusivo e mutuamente exclusivo do parâmetro volumeIDs.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não



 a| 
IDs de volume
 a| 
Uma lista de IDs de volume.  Se você especificar esse parâmetro, os outros parâmetros operarão somente nesse conjunto de volumes.  Exclusivos mutuamente com os parâmetros accounts, startVolumeID e limit.
 a| 
matriz de inteiros
 a| 
Não
 a| 
Não



 a| 
nomeDoVolume
 a| 
Somente as informações do objeto de volume que correspondem ao nome do volume são retornadas.
 a| 
corda
 a| 
Não
 a| 
Não



 a| 
status do volume
 a| 
Somente os volumes com status igual ao valor do status são retornados. Valores possíveis:

* criando
* captura de instantâneos
* ativo
* deletado

 a| 
corda
 a| 
Não
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volumes
 a| 
Lista de volumes.
 a| 
xref:reference_element_api_volume.adoc[volume]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Novidade desde a versão

9,6
