---
permalink: api/reference_element_api_listsnapmirroraggregates.html 
sidebar: sidebar 
keywords: snapmirror,aggregate,aggregates,list,listing,listsnapmirroraggregates 
summary: A interface web do software Element utiliza o método ListSnapMirrorAggregates para listar todos os agregados SnapMirror disponíveis no sistema ONTAP remoto.  Um agregado descreve um conjunto de recursos de armazenamento físico. 
---
= ListSnapMirrorAggregates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do software Element utiliza o `ListSnapMirrorAggregates` Método para listar todos os agregados SnapMirror disponíveis no sistema ONTAP remoto.  Um agregado descreve um conjunto de recursos de armazenamento físico.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
snapMirrorEndpointID
 a| 
Retorna apenas os agregados associados ao ID do endpoint especificado.  Caso nenhum ID de endpoint seja fornecido, o sistema listará os agregados de todos os endpoints SnapMirror conhecidos.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
snapMirrorAggregates
 a| 
Lista dos agregados disponíveis no sistema de armazenamento ONTAP .
 a| 
xref:reference_element_api_snapmirroraggregate.adoc[snapMirrorAggregate]variedade

|===


== Novidade desde a versão

10,1
