---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Você pode usar o método DeleteStorageContainers para remover até 2000 contêineres de armazenamento de Volume Virtual (VVol) do sistema de uma só vez.  Os contêineres de armazenamento que você remover não devem conter nenhum VVol.' 
---
= ExcluirContêineresDeArmazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteStorageContainers` Método para remover até 2000 contêineres de armazenamento de Volume Virtual (VVol) do sistema de uma só vez.  Os contêineres de armazenamento que você remover não devem conter nenhum VVol.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IDs de contêineres de armazenamento
 a| 
Uma lista dos IDs dos contêineres de armazenamento a serem excluídos.  Você pode especificar até 2000 IDs na lista.
 a| 
matriz UUID
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Novidade desde a versão

9,6
