---
permalink: api/reference_element_api_listsnapmirrornodes.html 
sidebar: sidebar 
keywords: snapmirror,node,nodes,list,listing,listsnapmirrornodes 
summary: A interface web do software Element utiliza o método ListSnapMirrorNodes para obter uma lista de nós em um cluster ONTAP remoto. 
---
= ListSnapMirrorNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface web do software Element utiliza o `ListSnapMirrorNodes` Método para obter uma lista de nós em um cluster ONTAP remoto.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
snapMirrorEndpointID
 a| 
Se fornecido, o sistema lista os nós do endpoint com o snapMirrorEndpointID especificado.  Caso não seja fornecido, o sistema lista os nós de todos os endpoints SnapMirror conhecidos.
 a| 
inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
snapMirrorNodes
 a| 
Lista dos nós no cluster ONTAP .
 a| 
xref:reference_element_api_snapmirrornode.adoc[snapMirrorNode]variedade

|===


== Novidade desde a versão

10,1
