---
permalink: api/reference_element_api_getschedule.html 
sidebar: sidebar 
keywords: snapshot,schedule,get,getting,getschedule 
summary: Você pode usar o GetSchedule para obter informações sobre um snapshot agendado. 
---
= Obter agendamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `GetSchedule` Para obter informações sobre um instantâneo agendado.

Você pode visualizar informações sobre uma programação específica se houver várias programações instantâneas no sistema.  Com esse método, você também pode obter informações sobre mais de um agendamento especificando IDs adicionais no parâmetro scheduleID.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do agendamento
 a| 
Identificador único da programação ou das várias programações a serem exibidas.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
agendar
 a| 
Uma matriz de atributos de agendamento.
 a| 
xref:reference_element_api_schedule.adoc[agendar]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method": "GetSchedule",
  "params": {
              "scheduleID" : 2
      },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Time Interval"
      },
       "hasError": false,
       "hours": 0,
       "lastRunStatus": "Success",
       "lastRunTimeStarted": "2015-03-23T21:25:00Z",
       "minutes": 2,
       "monthdays": [],
       "paused": false,
       "recurring": true,
       "runNextInterval": false,
       "scheduleID": 2,
       "scheduleInfo": {
          "name": "MCA2",
          "volumeID": "3"
       },
       "scheduleName": "MCAsnapshot2",
       "scheduleType": "Snapshot",
       "startingDate": "2015-03-23T19:28:57Z",
       "toBeDeleted": false,
       "weekdays": []
      }
   }
}
----


== Novidade desde a versão

9,6
