---
permalink: api/reference_element_api_secureerasedrives.html 
sidebar: sidebar 
keywords: drive,drives,secure,erase,reset,resetting,encryption,key,secureerasedrives 
summary: 'Você pode usar o método SecureEraseDrives para remover quaisquer dados residuais de unidades que tenham o status "disponível".  Você pode usar esse método ao substituir um disco rígido que esteja perto do fim de sua vida útil e que contenha dados confidenciais.  Este método utiliza um comando de Unidade de Apagamento de Segurança (Security Erase Unit) para gravar um padrão predeterminado na unidade e redefine a chave de criptografia da unidade.  Este método assíncrono pode levar vários minutos para ser concluído.' 
---
= Unidades SecureErase
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SecureEraseDrives` Método para remover quaisquer dados residuais de unidades que tenham o status "disponível".  Você pode usar esse método ao substituir um disco rígido que esteja perto do fim de sua vida útil e que contenha dados confidenciais.  Este método utiliza um comando de Unidade de Apagamento de Segurança (Security Erase Unit) para gravar um padrão predeterminado na unidade e redefine a chave de criptografia da unidade.  Este método assíncrono pode levar vários minutos para ser concluído.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
dirige
 a| 
Lista de IDs de unidades para apagar com segurança.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
manipulador assíncrono
 a| 
Identifica o valor utilizado para obter o resultado da operação.
 a| 
inteiro

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "SecureEraseDrives",
   "params": {
     "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id" : 1
   "result" : {
     "asyncHandle" : 1
   }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

* xref:reference_element_api_getasyncresult.adoc[ObterResultadoAssíncrono]
* xref:reference_element_api_listdrives.adoc[ListDrives]

