---
permalink: api/reference_element_api_getclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,preference,get,getting,getclusterinterfacepreference 
summary: O método GetClusterInterfacePreference permite que sistemas integrados a clusters de armazenamento que executam o software Element obtenham informações sobre uma preferência de interface de cluster existente.  Este método destina-se a uso interno. 
---
= GetClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `GetClusterInterfacePreference` Este método permite que sistemas integrados a clusters de armazenamento que executam o software Element obtenham informações sobre uma preferência de interface de cluster existente.  Este método destina-se a uso interno.



== Parâmetros

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
O nome da preferência de interface do cluster.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
preferência
 a| 
O nome e o valor da preferência de interface de cluster solicitada.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "GetClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
	"id": 1,
	"result": {
		"preference": {
			"name": "prefname",
			"value": "testvalue"
		}
	}
}
----


== Novidade desde a versão

11,0
