---
permalink: api/reference_element_api_createsupportbundle.html 
sidebar: sidebar 
keywords: create,creating,support,bundle,CreateSupportBundle 
summary: Você pode usar o CreateSupportBundle para criar um arquivo de pacote de suporte no diretório do nó.  Após a criação, o pacote é armazenado no nó como um arquivo tar.gz. 
---
= CriarPacoteDeSuporte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `CreateSupportBundle` Para criar um arquivo de pacote de suporte no diretório do nó.  Após a criação, o pacote é armazenado no nó como um arquivo tar (a opção de compressão gz está disponível através do parâmetro extraArgs).



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome do pacote
 a| 
Nome exclusivo para o pacote de suporte.  Caso nenhum nome seja fornecido, "supportbundle" e o nome do nó serão usados como nome do arquivo.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
argumentos extras
 a| 
Use '--compress gz' para criar o pacote de suporte como um arquivo tar.gz.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
tempo limiteSeg
 a| 
O número de segundos que o script do pacote de suporte é executado.
 a| 
inteiro
 a| 
1500
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
detalhes
 a| 
Detalhes do pacote de suporte. Valores possíveis:

* bundleName: O nome especificado no método CreateSupportBundleAPI.  Caso nenhum nome tenha sido especificado, será utilizado "supportbundle".
* extraArgs: Os argumentos passados com este método.
* Arquivos: Uma lista dos arquivos do pacote de suporte que o sistema criou.
* Saída: A saída da linha de comando do script que criou o pacote de suporte.
* timeoutSec: O número de segundos que o script do pacote de suporte é executado antes de ser interrompido.
* URL: URL do pacote de suporte criado.

 a| 
objeto JSON



 a| 
duração
 a| 
O horário usado para criar o pacote de suporte está no formato: HH:MM:SS.ssssss.
 a| 
corda



 a| 
resultado
 a| 
O sucesso ou o fracasso da operação do pacote de suporte.
 a| 
corda

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
 "method": "CreateSupportBundle",
"params": {
  "extraArgs": "--compress gz"
 },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
"id": 1,
"result": {
  "details": {
    "bundleName": "supportbundle",
    "extraArgs": "--compress gz",
    "files": [
         "supportbundle.nodehostname.tar.gz"
     ],
     "output": "timeout -s KILL 1500s /sf/scripts/sfsupportbundle --quiet --compress gz /tmp/solidfire-dtemp.1L6bdX/supportbundle<br><br>Moved '/tmp/solidfire-dtemp.1L6bdX/supportbundle.nodehostname.tar.gz' to /tmp/supportbundles",
      "timeoutSec": 1500,
      "url": [
          "https://nodeIP:442/config/supportbundles/supportbundle.nodehostname.tar.gz"
      ]
    },
    "duration": "00:00:43.101627",
    "result": "Passed"
  }
}
----


== Novidade desde a versão

9,6
