---
permalink: api/reference_element_api_getnvraminfo.html 
sidebar: sidebar 
keywords: nvram,info,get,getting,getnvraminfo 
summary: Você pode usar o método GetNvramInfo para obter informações de cada nó sobre a placa NVRAM . 
---
= GetNvramInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNvramInfo` Método para obter informações de cada nó sobre a placa NVRAM .



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
vigor
 a| 
O parâmetro `force` deve ser incluído neste método para que ele seja executado com sucesso em todos os nós do cluster.
 a| 
booleano
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
nvramInfo
 a| 
Conjunto de eventos e erros detectados no cartão NVRAM .
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetNvramInfo",
  "params": {
      "force": true
	  },
  "id" : 1
}
----


== Exemplo de resposta

Devido à extensão deste exemplo de resposta, ele está documentado em um tópico suplementar.



== Novidade desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_response_example_getnvraminfo.adoc[GetNvramInfo]
