---
permalink: api/reference_element_api_getclusterversioninfo.html 
sidebar: sidebar 
keywords: cluster,version,info,get,getting,getclusterversioninfo 
summary: Você pode usar o método GetClusterVersionInfo para obter informações sobre a versão do software Element em execução em cada nó do cluster.  Este método também retorna informações sobre nós que estão atualmente em processo de atualização de software. 
---
= GetClusterVersionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetClusterVersionInfo` Método para recuperar informações sobre a versão do software Element em execução em cada nó do cluster.  Este método também retorna informações sobre nós que estão atualmente em processo de atualização de software.



== membros do objeto de informações da versão do cluster

Este método possui os seguintes membros de objeto:

|===
| Nome | Descrição | Tipo 


 a| 
ID do nó
 a| 
ID do nó.
 a| 
inteiro



 a| 
revisão interna do nó
 a| 
Versão interna do software do nó.
 a| 
corda



 a| 
versão do nó
 a| 
Versão do software do nó.
 a| 
corda

|===


== Parâmetros

Este método não possui parâmetros de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
clusterAPIVersion
 a| 
A versão atual da API no cluster.
 a| 
corda



 a| 
versão do cluster
 a| 
Versão do software Element atualmente em execução no cluster.
 a| 
corda



 a| 
clusterVersionInfo
 a| 
Lista de nós no cluster com informações de versão para cada nó.
 a| 
matriz de objetos JSON



 a| 
versão do cluster pendente
 a| 
Caso esteja presente, esta é a versão para a qual o software do cluster está sendo atualizado ou revertido.
 a| 
corda



 a| 
Informações da versão do software
 a| 
O estado de uma atualização.  Membros do objeto:

* versãoatual:
+
A versão atual do software em um nó.

* nodeID: ID do nó que está sendo atualizado da versão atual para a versão pendente.  Este campo é 0 (zero) se não houver nenhuma atualização em andamento.
* packageName: Nome do pacote de software que está sendo instalado.
* pendingVersion: A versão do software que está sendo instalada.
* startTime: A data e hora em que a instalação foi iniciada, no formato UTC+0.

 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetClusterVersionInfo",
   "params": {},
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
 "id": 1,
 "result": {
   "clusterAPIVersion": "6.0",
   "clusterVersion": "6.1382",
   "clusterVersionInfo": [
   {
      "nodeID": 1,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   },
   {
      "nodeID": 2,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   },
   {
      "nodeID": 3,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   },
   {
      "nodeID": 4,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   }
 ],
   "softwareVersionInfo": {
      "currentVersion": "6.1382",
      "nodeID": 0,
      "packageName": "",
      "pendingVersion": "6.1382",
      "startTime": ""
    }
  }
}
----


== Novidade desde a versão

9,6
