---
permalink: api/reference_element_api_listfibrechannelportinfo.html 
sidebar: sidebar 
keywords: fibre,channel,port,ports,list,listing,listfibrechannelportinfo 
summary: Você pode usar o método ListFibreChannelPortInfo para listar informações sobre as portas Fibre Channel. 
---
= ListFibreChannelPortInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListFibreChannelPortInfo` Método para listar informações sobre as portas Fibre Channel.

Este método de API destina-se ao uso em nós individuais; um nome de usuário e uma senha são necessários para acessar nós Fibre Channel individuais.  No entanto, esse método pode ser usado no cluster se o parâmetro force estiver definido como verdadeiro.  Quando utilizado no cluster, todas as interfaces Fibre Channel são listadas.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
vigor
 a| 
Defina como verdadeiro para executar em todos os nós do cluster.
 a| 
booleano
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
Portas Fibre Channel
 a| 
Uma lista de todas as portas físicas Fibre Channel, ou de uma porta para um único nó.
 a| 
xref:reference_element_api_fibrechannelport.adoc[porta de canal de fibra]variedade

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListFibreChannelPortInfo",
    "params": {},
    "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": 1,
  "result": {
    "fibreChannelPortInfo": {
      "5": {
        "result": {
          "fibreChannelPorts": [
            {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 1,
             "model": "QLE2672",
             "nPortID": "0xc70084",
             "pciSlot": 3,
             "serial": "BFE1335E03500",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:98:a3:41",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:0a"
           },
           {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 2,
             "model": "QLE2672",
             "nPortID": "0x0600a4",
             "pciSlot": 3,
             "serial": "BFE1335E03500",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:9c:71:01",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:0b"
           },
           {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 1,
             "model": "QLE2672",
             "nPortID": "0xc70044",
             "pciSlot": 2,
             "serial": "BFE1335E04029",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:98:a3:41",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:08"
          },
          {
            "firmware": "7.04.00 (d0d5)",
            "hbaPort": 2,
            "model": "QLE2672",
            "nPortID": "0x060044",
            "pciSlot": 2,
            "serial": "BFE1335E04029",
            "speed": "8 Gbit",
            "state": "Online",
            "switchWwn": "20:01:00:2a:6a:9c:71:01",
            "wwnn": "5f:47:ac:c8:3c:e4:95:00",
            "wwpn": "5f:47:ac:c0:3c:e4:95:09"
          }
       ]
    }
  },
   "6": {
     "result": {
         "fibreChannelPorts": [
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 1,
           "model": "QLE2672",
           "nPortID": "0x060084",
           "pciSlot": 3,
           "serial": "BFE1335E04217",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:9c:71:01",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:02"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 2,
           "model": "QLE2672",
           "nPortID": "0xc700a4",
           "pciSlot": 3,
           "serial": "BFE1335E04217",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:98:a3:41",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:03"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 1,
           "model": "QLE2672",
           "nPortID": "0xc70064",
           "pciSlot": 2,
           "serial": "BFE1341E09515",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:98:a3:41",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:00"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 2,
           "model": "QLE2672",
           "nPortID": "0x060064",
           "pciSlot": 2,
           "serial": "BFE1341E09515",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:9c:71:01",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:01"
        }
     ]
    }
   }
  }
 }
}
----


== Novidade desde a versão

9,6
