---
permalink: api/reference_element_api_testdrives.html 
sidebar: sidebar 
keywords: drive,drives,test,testing,validating,hardware,testdrives 
summary: Você pode usar o método TestDrives para executar uma validação de hardware em todas as unidades do nó.  Este método detecta falhas de hardware nas unidades e as reporta nos resultados dos testes de validação. 
---
= TestDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `TestDrives` Método para executar uma validação de hardware em todas as unidades do nó.  Este método detecta falhas de hardware nas unidades e as reporta nos resultados dos testes de validação.



== Parâmetros

Você só pode usar o `TestDrives` método em nós que não estão "Ativos" em um cluster.


NOTE: Este teste demora aproximadamente 10 minutos.

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
vigor
 a| 
Defina como verdadeiro para testar as unidades no nó.
 a| 
booleano
 a| 
Nenhum
 a| 
Sim



 a| 
minutos
 a| 
Especifica o número de minutos para a execução do teste.
 a| 
inteiro
 a| 
10
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
detalhes
 a| 
Informações sobre o sucesso ou fracasso da operação de teste.
 a| 
objeto JSON

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "TestDrives",
   "params": {
              "force": true,
              "minutes" : 10
             },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma tabela contendo os resultados dos testes para cada unidade no nó.



== Novidade desde a versão

9,6
