---
permalink: api/reference_element_api_modifyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,group,modify,modifying,updating,changing,change,update,edit,editing,modifyvolumeaccessgroup 
summary: Você pode usar o método ModifyVolumeAccessGroup para atualizar iniciadores e adicionar ou remover volumes de um grupo de acesso a volumes. 
---
= Modificar grupo de acesso ao volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyVolumeAccessGroup` Método para atualizar iniciadores e adicionar ou remover volumes de um grupo de acesso a volumes.

Se um iniciador ou volume especificado for uma duplicata do que já existe, o grupo de acesso ao volume permanecerá inalterado.  Se você não especificar um valor para volumes ou iniciadores, a lista atual de iniciadores e volumes não será alterada.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do grupo de acesso ao volume
 a| 
O ID do grupo de acesso ao volume a ser modificado.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
nome
 a| 
O novo nome para este grupo de acesso a volume.
 a| 
corda
 a| 
Nenhum
 a| 
Não



 a| 
atributos
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
iniciadores
 a| 
Lista de IDs ou nomes de iniciadores (IQNs e WWPNs) a serem incluídos no grupo de acesso ao volume.  Se você passar uma lista de nomes de iniciadores, os iniciadores serão criados caso ainda não existam.  Se você passar uma lista de IDs de iniciadores, o método retornará um erro caso algum dos iniciadores ainda não exista.  Passar nomes de iniciadores está obsoleto; você deve usar IDs de iniciadores sempre que possível.
 a| 
Matriz de inteiros (recomendado) ou matriz de strings (obsoleto)
 a| 
Nenhum
 a| 
Não



 a| 
excluirIniciadoresÓrfãos
 a| 
Especifica se os objetos iniciadores devem ser excluídos após serem removidos de um grupo de acesso a volumes ou não. Valores possíveis:

* Verdadeiro: Exclui os objetos iniciadores após serem removidos de um grupo de acesso a volumes.
* falso: Não exclua objetos iniciadores depois que eles forem removidos de um grupo de acesso a volume. Este é o padrão.

 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
volumes
 a| 
Uma lista de IDs de volumes a serem modificados.
 a| 
matriz de inteiros
 a| 
Nenhum
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[grupoDeAcessoDeVolume]

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
grupoDeAcessoDeVolume
 a| 
Um objeto contendo informações sobre o grupo de acesso ao volume recém-modificado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[grupoDeAcessoDeVolume]

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ModifyVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "name": "accessgrouptest",
      "initiators": [115,114],
      "volumes": [
         346
    ],
      "attributes": {}
   }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        114,
        115
      ],
      "initiators": [
        "iqn.1998-01.com.vmware:desk1-esx1-577b283a",
        "iqn.1998-01.com.vmware:donesq-esx1-421b281b"
      ],
      "name": "accessgrouptest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== Novidade desde a versão

9,6



== Encontre mais informações

* xref:reference_element_api_addinitiatorstovolumeaccessgroup.adoc[AdicionarIniciadoresAoGrupoDeAcessoAoVolume]
* xref:reference_element_api_addvolumestovolumeaccessgroup.adoc[Adicionar volumes ao grupo de acesso a volumes]
* xref:reference_element_api_removeinitiatorsfromvolumeaccessgroup.adoc[RemoverIniciadoresDoGrupoDeAcessoPorVolume]
* xref:reference_element_api_removevolumesfromvolumeaccessgroup.adoc[Remover volumes do grupo de acesso a volumes]

