---
permalink: api/reference_element_api_fibrechannelport.html 
sidebar: sidebar 
keywords: object,objects,fibreChannelPort 
summary: O objeto fibreChannelPort contém informações sobre portas individuais em um nó ou sobre um nó inteiro no cluster.  Você pode recuperar essas informações usando o método ListNodeFibreChannelPortInfo. 
---
= porta de canal de fibra
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto fibreChannelPort contém informações sobre portas individuais em um nó ou sobre um nó inteiro no cluster.  Você pode obter essas informações usando o `ListNodeFibreChannelPortInfo` método.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
firmware
 a| 
A versão do firmware instalada na porta Fibre Channel.
 a| 
inteiro



 a| 
hbaPort
 a| 
O ID da porta individual do adaptador de barramento de host (HBA).
 a| 
inteiro



 a| 
modelo
 a| 
Modelo do HBA na porta.
 a| 
corda



 a| 
nPortID
 a| 
O ID exclusivo do nó da porta.
 a| 
corda



 a| 
slot pci
 a| 
O slot que contém a placa PCI no chassi do nó Fibre Channel.
 a| 
inteiro



 a| 
serial
 a| 
O número de série na porta Fibre Channel.
 a| 
corda



 a| 
velocidade
 a| 
A velocidade do HBA na porta.
 a| 
corda



 a| 
estado
 a| 
Valores possíveis:

* Desconhecido
* Não presente
* On-line
* Off-line
* Bloqueado
* Ignorado
* Diagnóstico
* Linkdown
* Erro
* Loopback
* Excluído

 a| 
corda



 a| 
switchWwn
 a| 
Nome mundial da porta de comutação Fibre Channel.
 a| 
corda



 a| 
wwnn
 a| 
Nome mundial do nó HBA.
 a| 
corda



 a| 
wwpn
 a| 
Nome mundial da porta atribuído à porta física do HBA.
 a| 
corda

|===


== Encontre mais informações

xref:reference_element_api_listnodefibrechannelportinfo.adoc[ListNodeFibreChannelPortInfo]
