---
permalink: api/reference_element_api_getvolumeaccessgroupefficiency.html 
sidebar: sidebar 
keywords: volume,volumes,get,getting,access,group,efficiency,GetVolumeAccessGroupEfficiency 
summary: Você pode usar o método GetVolumeAccessGroupEfficiency para obter informações sobre a eficiência de um grupo de acesso a volumes.  Somente o grupo de acesso ao volume fornecido como parâmetro neste método da API é usado para calcular a capacidade. 
---
= Obtenha a eficiência do grupo de acesso por volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetVolumeAccessGroupEfficiency` Método para obter informações de eficiência sobre um grupo de acesso a volume.  Somente o grupo de acesso ao volume fornecido como parâmetro neste método da API é usado para calcular a capacidade.



== Parâmetro

Este método possui o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID do grupo de acesso ao volume
 a| 
Especifica o grupo de acesso ao volume para o qual a capacidade é calculada.
 a| 
inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
compressão
 a| 
A quantidade de espaço economizado pela compressão de dados para todos os volumes no grupo de acesso a volumes.  Expressa-se como uma proporção em que o valor 1 significa que os dados foram armazenados sem compressão.
 a| 
flutuador



 a| 
desduplicação
 a| 
A quantidade de espaço economizada ao não duplicar dados para todos os volumes no grupo de acesso a volumes.  Expressa-se como uma proporção.
 a| 
flutuador



 a| 
provisionamento fino
 a| 
A proporção entre o espaço utilizado e a quantidade de espaço alocada para armazenamento de dados.  Expressa-se como uma proporção.
 a| 
flutuador



 a| 
carimbo de data/hora
 a| 
A última vez que os dados de eficiência foram coletados foi após a coleta de lixo.
 a| 
Cadeia de dados ISO 8601



 a| 
volumesfaltantes
 a| 
Os volumes que não puderam ser consultados para obtenção de dados de eficiência.  A ausência de volumes pode ser causada por uma coleta de lixo recente, perda temporária de rede ou reinicialização de serviços desde o ciclo de coleta de lixo.
 a| 
matriz de inteiros

|===


== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetVolumeAccessGroupEfficiency",
   "params": {
      "volumeAccessGroupID": 1
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.006012925331075,
       "deduplication": 1,
       "missingVolumes": [],
       "thinProvisioning": 1.009861932938856,
       "timestamp": "2014-03-10T17:05:27Z"
   }
}
----


== Novidade desde a versão

9,6
