---
permalink: api/reference_element_api_createcluster.html 
sidebar: sidebar 
keywords: CreateCluster,cluster,create,creating,initialize,initializing 
summary: 'Você pode usar o método CreateCluster para inicializar o nó em um cluster que possui os endereços "mvip" e "svip".  Cada novo cluster é inicializado usando o endereço IP de gerenciamento (MIP) do primeiro nó do cluster.  Este método também adiciona automaticamente todos os nós que estão sendo configurados ao cluster.  Você só precisa usar esse método uma vez a cada inicialização de um novo cluster.' 
---
= CriarCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CreateCluster` Método para inicializar o nó em um cluster que possui os endereços "mvip" e "svip".  Cada novo cluster é inicializado usando o endereço IP de gerenciamento (MIP) do primeiro nó do cluster.  Este método também adiciona automaticamente todos os nós que estão sendo configurados ao cluster.  Você só precisa usar esse método uma vez a cada inicialização de um novo cluster.


NOTE: Após fazer login no nó mestre do cluster e executar oxref:reference_element_api_getbootstrapconfig.adoc[GetBootStrapConfig] Para obter os endereços IP dos demais nós que você deseja incluir no cluster, você pode executar o método CreateCluster no nó mestre do cluster.



== Parâmetros

Este método possui os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
aceitarEula
 a| 
Ao criar este cluster, indique sua aceitação do Contrato de Licença de Usuário Final.  Para aceitar o EULA, defina este parâmetro como verdadeiro.
 a| 
booleano
 a| 
Nenhum
 a| 
Sim



 a| 
atributos
 a| 
Lista de pares nome-valor em formato de objeto JSON.
 a| 
objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
habilitar a criptografia de software em repouso
 a| 
Ative este parâmetro para usar criptografia baseada em software em repouso.  O valor padrão é falso em todos os clusters.  Após a ativação da criptografia de software em repouso, ela não pode ser desativada no cluster.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
mvip
 a| 
Endereço IP flutuante (virtual) para o cluster na rede de gerenciamento.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
nós
 a| 
Endereços CIP/SIP do conjunto inicial de nós que compõem o cluster.  O endereço IP deste nó deve estar na lista.
 a| 
matriz de strings
 a| 
Nenhum
 a| 
Sim



 a| 
número do pedido
 a| 
Número de pedido de venda alfanumérico.  Requerido em plataformas baseadas em software.
 a| 
corda
 a| 
Nenhum
 a| 
Não (plataformas baseadas em hardware)

Sim (plataformas baseadas em software)



 a| 
senha
 a| 
Senha inicial para a conta de administrador do cluster.
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
número de série
 a| 
Número de série alfanumérico de nove dígitos.  Pode ser necessário em plataformas baseadas em software.
 a| 
corda
 a| 
Nenhum
 a| 
Não (plataformas baseadas em hardware)

Sim (plataformas baseadas em software)



 a| 
svip
 a| 
Endereço IP flutuante (virtual) para o cluster na rede de armazenamento (iSCSI).
 a| 
corda
 a| 
Nenhum
 a| 
Sim



 a| 
nome de usuário
 a| 
Nome de usuário para o administrador do cluster.
 a| 
corda
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não possui valores de retorno.



== Exemplo de solicitação

As solicitações para esse método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "CreateCluster",
  "params": {
    "acceptEula": true,
    "mvip": "10.0.3.1",
    "svip": "10.0.4.1",
    "username": "Admin1",
    "password": "9R7ka4rEPa2uREtE",
    "attributes": {
      "clusteraccountnumber": "axdf323456"
    },
    "nodes": [
      "10.0.2.1",
      "10.0.2.2",
      "10.0.2.3",
      "10.0.2.4"
    ]
  },
  "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao exemplo a seguir:

[listing]
----
{
"id" : 1,
"result" : {}
}
----


== Novidade desde a versão

9,6

[discrete]
== Encontre mais informações

* link:reference_element_api_getbootstrapconfig.html["Obter configuração do Bootstrap"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do SolidFire e do Element Software"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element."^]

